### ISSUE TITLE
[BlockStore] System.OverflowException: Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by D3m0nKingx** [stratisproject/StratisBitcoinFullNode#1006]
```bash
crit: Stratis.Bitcoin.FullNode[0]
      BlockStore.DownloadAndStoreBlocks threw an unhandled exception
System.OverflowException: Arithmetic operation resulted in an overflow.
   at DBreeze.LianaTrie.LTrieWriteCache.GenerationNodeRead(Boolean useCache, Byte[] pointer, Byte[] cachedGenerationMapLine, Int32 MaximumNodeLineLength)
   at DBreeze.LianaTrie.LTrieGenerationNode.ReadSelf(Boolean useCache, Byte[] generationMapLine)
   at DBreeze.LianaTrie.LTrieRootNode.GetKey(Byte[] key, Boolean useCache, Boolean ValuesLazyLoadingIsOn)
   at DBreeze.Transactions.Transaction.Select[TKey,TValue](String tableName, TKey key, Boolean AsReadVisibilityScope)
   at Stratis.Bitcoin.Features.BlockStore.BlockRepository.<>c__DisplayClass37_0.<ExistAsync>b__0() in /home/ader/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs:line 458
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Stratis.Bitcoin.Features.BlockStore.LoopSteps.CheckNextChainedBlockExistStep.<ExecuteAsync>d__2.MoveNext() in /home/ader/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin.Features.BlockStore/LoopSteps/CheckNextChainedBlockExistStep.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Stratis.Bitcoin.Features.BlockStore.BlockStoreStepChain.<ExecuteAsync>d__2.MoveNext() in /home/ader/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin.Features.BlockStore/BlockStoreLoopStep.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Stratis.Bitcoin.Features.BlockStore.BlockStoreLoop.<DownloadAndStoreBlocksAsync>d__39.MoveNext() in /home/ader/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin.Features.BlockStore/BlockStoreLoop.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.BlockStore.BlockStoreLoop.<<StartLoop>b__38_0>d.MoveNext() in /home/ader/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin.Features.BlockStore/BlockStoreLoop.cs:line 216
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass12_0.<<StartAsync>b__0>d.MoveNext() in /home/ader/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Utilities/AsyncLoop.cs:line 129
``` 
Occurred same time as #1005 
Running on StratisD Testnet

**Comment by D3m0nKingx** [comment]
Closing this issue and #1005  per discussion with @Aprogiena that we've determined this to be most likely caused by a corruption in database files while transferring the datadir from a node running on a remote server using scp (secure copy). Steps that caused the problem:

Quoted from slack by @Aprogiena:
1. machine A: node runs, node closes normally (this I call run K-1)
2. transfer of data directory from machine A to machine B (using scp command from remote -> local machine)
3. machine B: run node, node crashes on this very bug (this I call run K)
4. further attempts to run node with this data dir on machine B fails
5. a new attempt to transfer data directory from A to B does not reproduce the problem after run
