### ISSUE TITLE
Miner shutdown not disposed properly 

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1089]
```
info: Stratis.Bitcoin.Connection.ConnectionManagerBehavior[0]
      Peer '[::ffff:52.174.146.39]:26178' offline, reason: 'unknown'.
info: Stratis.Bitcoin.Connection.ConnectionManagerBehavior[0]
      Peer '[::ffff:51.141.45.80]:26178' offline, reason: 'unknown'.
info: Stratis.Bitcoin.FullNode[0]
      Waiting for PeriodicLog to finish.
info: Stratis.Bitcoin.Features.Api.ApiFeature[0]
      API stopping on URL 'http://localhost:37221/'.
info: Stratis.Bitcoin.FullNode[0]
      Waiting for PosMining.Stake to finish.
info: Stratis.Bitcoin.FullNode[0]
      PosMining.Stake stopping
crit: Stratis.Bitcoin.FullNode[0]
      PosMining.Stake threw an unhandled exception
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Stratis.Bitcoin.Features.Miner.PowBlockAssembler..ctor(IConsensusLoop consensusLoop, Network network, MempoolSchedulerLock mempoolLock, ITxMempool mempool, IDateTimeProvider dateTimeProvider, ChainedBlock chainTip, ILoggerFactory loggerFactory, AssemblerOptions options) in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PowBlockAssembler.cs:line 192
   at Stratis.Bitcoin.Features.Miner.PosBlockAssembler..ctor(IConsensusLoop consensusLoop, Network network, MempoolSchedulerLock mempoolLock, ITxMempool mempool, IDateTimeProvider dateTimeProvider, StakeChain stakeChain, IStakeValidator stakeValidator, ChainedBlock chainTip, ILoggerFactory loggerFactory, AssemblerOptions options) in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PosBlockAssembler.cs:line 33
   at Stratis.Bitcoin.Features.Miner.PosAssemblerFactory.Create(ChainedBlock chainTip, AssemblerOptions options) in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\AssemblerFactory.cs:line 122
   at Stratis.Bitcoin.Features.Miner.PosMinting.<GenerateBlocksAsync>d__39.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 517
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Miner.PosMinting.<>c__DisplayClass37_0.<<Stake>b__0>d.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 406
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 136
info: Stratis.Bitcoin.FullNode[0]
      Waiting for wallet persist job to finish.
info: Stratis.Bitcoin.Features.MemoryPool.MempoolFeature[0]
      Saving Memory Pool...
info: Stratis.Bitcoin.Features.MemoryPool.MempoolFeature[0]
      ...Memory Pool Saved 0 transactions
info: Stratis.Bitcoin.FullNode[0]
      Waiting for MemoryPool.RelayWorker to finish.
info: Stratis.Bitcoin.Features.BlockStore.BlockStoreFeature[0]
      Stopping BlockStore...
info: Stratis.Bitcoin.FullNode[0]
      Waiting for BlockStore.RelayWorker to finish.
info: Stratis.Bitcoin.FullNode[0]
      Waiting for BlockStore.DownloadAndStoreBlocks to finish.
info: Stratis.Bitcoin.FullNode[0]
      Waiting for Consensus Loop to finish.
info: Stratis.Bitcoin.Features.Consensus.ConsensusFeature[0]
      Flushing Cache CoinView...
info: Stratis.Bitcoin.Base.BaseFeature[0]
      Flushing peers...
info: Stratis.Bitcoin.FullNode[0]
      Waiting for Periodic peer flush... to finish.
info: Stratis.Bitcoin.Base.BaseFeature[0]
      Flushing headers chain...
```

**Comment by dangershony** [comment]
I suspect this method is not thread safe
```
        public IAsyncLoop Stake(WalletSecret walletSecret)
        {
            this.logger.LogTrace("()");
            if (this.stakingLoop != null)
            {
                this.logger.LogTrace("(-)[ALREADY_MINING]");
                return this.stakingLoop;
            }

            this.rpcGetStakingInfoModel.Enabled = true;
            this.stakeCancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(new[] { this.nodeLifetime.ApplicationStopping });

            this.stakingLoop = this.asyncLoopFactory.Run("PosMining.Stake", async token =>
            {
                this.logger.LogTrace("()");


```

**Comment by dangershony** [comment]
This might be related as well.

```
info: Stratis.Bitcoin.Features.Miner.PosMinting[0]
      Node staking with 19570164.11390382 (326.02 % of the network weight 6002809.55743705), est. time to find new block is 00:00:19.
info: Stratis.Bitcoin.FullNode[0]
      PosMining.Stake stopping
crit: Stratis.Bitcoin.FullNode[0]
      PosMining.Stake threw an unhandled exception
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Stratis.Bitcoin.Features.Miner.PosMinting.<StakeAndSignBlockAsync>d__41.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 641
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Stratis.Bitcoin.Features.Miner.PosMinting.<GenerateBlocksAsync>d__39.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 529
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Miner.PosMinting.<>c__DisplayClass37_0.<<Stake>b__0>d.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 406
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 136
info: Stratis.Bitcoin.FullNode[0]
```
