### ISSUE TITLE
unhandled OperationCanceledExceptions

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1094]
I don't have a solid way of reproducing it- just randomly got it while running the node on testnet. 

```
fail: Stratis.Bitcoin.P2P.Peer.NetworkPeer[0]
      [372-[::ffff:31.201.238.146]:26178] Exception occurred: System.OperationCanceledException: The peer has been disconnected
         at Stratis.Bitcoin.P2P.Peer.NetworkPeer.<SendMessageAsync>d__106.MoveNext() in C:\StratisRepository\src\Stratis.Bitcoin\P2P\Peer\NetworkPeer.cs:line 686
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Base.ChainHeadersBehavior.<ProcessGetHeadersAsync>d__34.MoveNext() in C:\StratisRepository\src\Stratis.Bitcoin\Base\ChainHeadersBehavior.cs:line 273
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Base.ChainHeadersBehavior.<MessageReceivedAsync>d__32.MoveNext() in C:\StratisRepository\src\Stratis.Bitcoin\Base\ChainHeadersBehavior.cs:line 178
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Base.ChainHeadersBehavior.AttachedPeer_MessageReceived(NetworkPeer peer, IncomingMessage message) in C:\StratisRepository\src\Stratis.Bitcoin\Base\ChainHeadersBehavior.cs:line 159
```

and another similar one: 

I got this one when I had large number of peers and the tx was huge so it took long to send it. 

```
fail: Stratis.Bitcoin.Features.Wallet.Controllers.WalletController[0]
      Exception occurred: System.OperationCanceledException: The peer has been disconnected
         at Stratis.Bitcoin.P2P.Peer.NetworkPeer.<SendMessageAsync>d__106.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\P2P\Peer\NetworkPeer.cs:line 686
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.Wallet.Broadcasting.BroadcasterManagerBase.<PropagateTransactionToPeersAsync>d__12.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Wallet\Broadcasting\BroadcasterManagerBase.cs:line 79
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.Wallet.Broadcasting.FullNodeBroadcasterManager.<BroadcastTransactionAsync>d__2.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Wallet\Broadcasting\FullNodeBroadcasterManager.cs:line 35
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.SendTransaction(SendTransactionRequest request) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Wallet\Controllers\WalletController.cs:line 672
```

**Comment by Aprogiena** [comment]
tx, this is known and is actually fixed by #1079 together with all (hopefully) instances of this bug across whole codebase
