### ISSUE TITLE
[WalletController] unhandled OperationCanceledException if peer was disconnected during transaction sending

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1095]
I got this one when I had large number of peers and the tx was huge so it took long to send it. 

```
fail: Stratis.Bitcoin.Features.Wallet.Controllers.WalletController[0]
      Exception occurred: System.OperationCanceledException: The peer has been disconnected
         at Stratis.Bitcoin.P2P.Peer.NetworkPeer.<SendMessageAsync>d__106.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\P2P\Peer\NetworkPeer.cs:line 686
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.Wallet.Broadcasting.BroadcasterManagerBase.<PropagateTransactionToPeersAsync>d__12.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Wallet\Broadcasting\BroadcasterManagerBase.cs:line 79
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.Wallet.Broadcasting.FullNodeBroadcasterManager.<BroadcastTransactionAsync>d__2.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Wallet\Broadcasting\FullNodeBroadcasterManager.cs:line 35
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.SendTransaction(SendTransactionRequest request) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Wallet\Controllers\WalletController.cs:line 672
```

**Comment by Aprogiena** [comment]
ok, this was not known, similar to the other one, will add to #1079

**Comment by dangershony** [comment]
Can we consolidate in to one issue?

**Comment by noescape00** [comment]
Consolidated in https://github.com/stratisproject/StratisBitcoinFullNode/issues/1094
Therefore closing this one.
