### ISSUE TITLE
[shutdown] TCP bug when disposing the node

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1141]
```
info: Stratis.Bitcoin.FullNode[0]
      Waiting for DiscoverPeersAsync to finish.
info: Stratis.Bitcoin.FullNode[0]
      Waiting for PeerConnectorAddNode.ConnectAsync to finish.
^C
C:\Users\fullnodedan\Documents\Github\StratisBitcoinFullNode\src\Stratis.StratisD>info: Stratis.Bitcoin.FullNode[0]
      PeerConnectorAddNode.ConnectAsync stopping
info: Stratis.Bitcoin.FullNode[0]
      Waiting for PeerConnectorDiscovery.ConnectAsync to finish.
fail: Stratis.Bitcoin.P2P.Peer.NetworkPeerServer[0]
      [0.0.0.0:26178] Exception occurred: System.AggregateException: One or more errors occurred. (Cannot access a disposed object.
      Object name: 'System.Net.Sockets.Socket'.) ---> System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'System.Net.Sockets.Socket'.
         at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, Int32& bytesTransferred, IAsyncResult asyncResult)
         at System.Net.Sockets.TcpListener.EndAcceptTcpClient(IAsyncResult asyncResult)
         at System.Net.Sockets.TcpListener.<>c.<AcceptTcpClientAsync>b__28_1(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
         --- End of inner exception stack trace ---
         at Stratis.Bitcoin.P2P.Peer.NetworkPeerServer.<AcceptClientsAsync>d__34.MoveNext() in C:\Users\fullnodedan\Documents\Github\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerServ
er.cs:line 160
      ---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'System.Net.Sockets.Socket'.
         at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, Int32& bytesTransferred, IAsyncResult asyncResult)
         at System.Net.Sockets.TcpListener.EndAcceptTcpClient(IAsyncResult asyncResult)
         at System.Net.Sockets.TcpListener.<>c.<AcceptTcpClientAsync>b__28_1(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---

info: Stratis.Bitcoin.FullNode[0]
      Waiting for PeriodicLog to finish.
info: Stratis.Bitcoin.Features.Api.ApiFeature[0]
      API stopping on URL 'http://localhost:38221/'.
info: Stratis.Bitcoin.FullNode[0]
      Waiting for wallet persist job to finish.
info: Stratis.Bitcoin.Features.MemoryPool.MempoolFeature[0]
      Saving Memory Pool...
info: Stratis.Bitcoin.Features.MemoryPool.MempoolFeature[0]
      ...Memory Pool Saved 0 transactions
```

**Comment by Aprogiena** [comment]
By any chance, is this not because of the change that you suggested to log that exception in that code on error level instead of debug level

**Comment by noescape00** [comment]
>By any chance, is this not because of the change that you suggested to log that exception in that code on error level instead of debug level

looks like that's the case. 
Caller of the `AcceptClientsAsync()` already handles errors on a trace level but it looks like inside the `AcceptClientsAsync` exception handling was also implemented but on a Error level.

**Comment by Aprogiena** [comment]
this has been changed recently and that change is causing this imho

**Comment by dangershony** [comment]
Ah so this is expected just we are tracing out too much?

**Comment by Aprogiena** [comment]
Yes, in this async method that.net provides it is not possible to provide cancellation token. Therefore the actual cancellation of that call is done by closing the socket, but that immediately leads to the exception and that exception is expected, so logging it on error level is not a good idea because it is not an error
