### ISSUE TITLE
Staking null reference exception

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#1199]
Took a while to happen, below is the relevant log & stack trace:

```
[2018-03-11 04:53:59.8097 34] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake stopping
[2018-03-11 04:53:59.8392 34] FATAL: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake threw an unhandled exception
[2018-03-11 04:53:59.8392 34] ERROR: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake threw an unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Consensus.StakeValidator.CheckProofOfStake(ContextStakeInformation context, ChainedBlock prevChainedBlock, BlockStake prevBlockStake, Transaction transaction, UInt32 headerBits) in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\StakeValidator.cs:line 182
   at Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.CheckAndComputeStake(RuleContext context) in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\PosConsensusValidator.cs:line 192
   at Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.ExecuteBlock(RuleContext context, TaskScheduler taskScheduler) in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\PosConsensusValidator.cs:line 121
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<ValidateAndExecuteBlockAsync>d__42.MoveNext() in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 487
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<AcceptBlockAsync>d__40.MoveNext() in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 358
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Miner.PosMinting.CheckStake(Block block, ChainedBlock chainTip) in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 599
   at Stratis.Bitcoin.Features.Miner.PosMinting.<GenerateBlocksAsync>d__44.MoveNext() in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 561
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Miner.PosMinting.<>c__DisplayClass42_0.<<Stake>b__0>d.MoveNext() in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 427
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 136
```

**Comment by Aprogiena** [comment]
The crashing code reads as:
```
            ChainedBlock prevBlock = this.chain.GetBlock(coins.BlockHash);
            UnspentOutputs prevUtxo = coins.UnspentOutputs[0];

            // Verify signature.
            if (!this.VerifySignature(prevUtxo, transaction, 0, ScriptVerify.None))
            {
                this.logger.LogTrace("(-)[BAD_SIGNATURE]");
                ConsensusErrors.CoinstakeVerifySignatureFailed.Throw();
            }

            // Min age requirement.
            if (this.IsConfirmedInNPrevBlocks(prevUtxo, prevChainedBlock, this.consensusOptions.StakeMinConfirmations - 1))
            {
                this.logger.LogTrace("(-)[BAD_STAKE_DEPTH]");
                ConsensusErrors.InvalidStakeDepth.Throw();
            }

            this.CheckStakeKernelHash(context, prevChainedBlock, headerBits, prevBlock.Header.Time, prevBlockStake, prevUtxo, txIn.PrevOut, transaction.Time);
```

And the crash procurers on the last line. It seems obvious that `prevBlock`can be null. I would call it concurrent chain strikes again.

So basically what happened here is that the peer was informed about the better chain which orphaned  the tip, therefore concurrent chain no longer contained the tip, so null was returned and there is a check missing for that.

**Comment by dangershony** [comment]
Ah well spotted, another concurrent chain shenanigan.
We have this check in the `CheckKernal` method so we just need to add it in `CheckProofOfStake`
```
            if (prevBlock == null)
            {
                this.logger.LogTrace("(-)[REORG]");
                ConsensusErrors.ReadTxPrevFailed.Throw();
            }
```
