### ISSUE TITLE
Shutdown in ConsensusLoop is not handled properly

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1203]
In ConsensusLoop.cs on line 278:

`LookaheadResult lookaheadResult = this.Puller.NextBlock(this.nodeLifetime.ApplicationStopping);`

`NextBlock` will throw on the application shutdown and error message will be spawned in the console: 

```
[2018-03-13 17:12:09.1369 11] ERROR: Stratis.Bitcoin.Features.Consensus.ConsensusLoop+<PullerLoopAsync>d__38.MoveNext System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Stratis.Bitcoin.BlockPulling.LookaheadBlockPuller.NextBlockCore(CancellationToken cancellationToken) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\BlockPulling\LookaheadBlockPuller.cs:line 540
   at Stratis.Bitcoin.BlockPulling.LookaheadBlockPuller.NextBlock(CancellationToken cancellationToken) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\BlockPulling\LookaheadBlockPuller.cs:line 297
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<PullerLoopAsync>d__38.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 281
```

So I think we should handle OperationCanceledException here and ignore it instead of showing an error.

**Comment by dangershony** [comment]
Just confirming you got this when shutdown right?

**Comment by noescape00** [comment]
Yes.

**Comment by noescape00** [comment]
Fixed with activation merge.
