### ISSUE TITLE
Staking exception because collection was modified

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1205]
```
[2018-03-13 20:02:50.8818 39] ERROR: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake threw an unhandled exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Stratis.Bitcoin.Features.Miner.PosMinting.<StakeAndSignBlockAsync>d__46.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 668
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Stratis.Bitcoin.Features.Miner.PosMinting.<GenerateBlocksAsync>d__44.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 556
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Miner.PosMinting.<>c__DisplayClass42_0.<<Stake>b__0>d.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 426
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 136
```

So we have a collection modification inside a foreach:

PosMinting.cs: 666
```
// We have to make sure that we have no future timestamps in
// our transactions set.
foreach (Transaction transaction in block.Transactions)
{
    if (transaction.Time > block.Header.Time)
    {
        this.logger.LogTrace("Removing transaction with timestamp {0} as it is greater than coinstake transaction timestamp {1}.", transaction.Time, block.Header.Time);
        block.Transactions.Remove(transaction);
    }
}
```

**Comment by dangershony** [comment]
Hu? this is odd that method should be single threaded.

**Comment by noescape00** [comment]
>that method should be single threaded.
What do you mean? 
It will make no difference, it's just in general not possible to modify a collection inside a foreach on the same collection.

**Comment by dangershony** [comment]
Ah crap hahah ofcourse I got confused there for a second.
The fix is quite simple.
