### ISSUE TITLE
MemPoolErrorException in MempoolValidationContext

### ISSUE THREAD

**Issue by majikandy** [stratisproject/StratisBitcoinFullNode#1207]
(The following didn't hang the node but happened 3 times before clearing itself and continuing - I had to hit continue on the debugger)

Ran the node for 20 mins in debug mode and got the following exception:-

Exception of type 'Stratis.Bitcoin.Features.MemoryPool.MempoolErrorException' was thrown.   at Stratis.Bitcoin.Features.MemoryPool.MempoolValidationState.Throw() in C:\Projects\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.MemoryPool\MempoolValidationContext.cs:line 124
  at Stratis.Bitcoin.Features.MemoryPool.MempoolValidator.CheckMempoolCoinView(MempoolValidationContext context) in C:\Projects\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.MemoryPool\MempoolValidator.cs:line 671
  at Stratis.Bitcoin.Features.MemoryPool.MempoolValidator.<>c__DisplayClass32_0.<AcceptToMemoryPoolWorkerAsync>b__0() in C:\Projects\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.MemoryPool\MempoolValidator.cs:line 437
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state

**Comment by mikedennis** [comment]
Are you talking about just when running in the debugger? Yes the mempool validator does throw exceptions that are eaten (basically invalid transactions that are filtered out). So you will want to turn off breaking on that exception in the debugger in the mempool validator or you will go bonkers hitting F5 😁 - especially on Bitcoin testnet.

Looks like that specific one is a transaction in which not all inputs exist. Can confirm with Dan but I think this is a legit case where you've gotten a transaction before you've received all it's inputs so it has to reject it.

**Comment by dangershony** [comment]
Yes this is legit (perhaps we should have designed it differently) but its not a bug.

**Comment by einewton** [comment]
I am also having this same issue.. Quite annoying.
