### ISSUE TITLE
StakeValidator.CheckProofOfStake prevUtxo could be null

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1220]
Here `prevUtxo` could be null during a reorg:

```
ChainedBlock prevBlock = this.chain.GetBlock(coins.BlockHash);
UnspentOutputs prevUtxo = coins.UnspentOutputs[0];
if (prevBlock == null)
{
    this.logger.LogTrace("(-)[REORG]");
    ConsensusErrors.ReadTxPrevFailed.Throw();
}
```

This bug stops the consensus loop.

So probably (as @Aprogiena suggested) we should add a null check for a UTXO after the block check.

Log:

```
[2018-03-17 11:10:19.6410 8] INFO: Stratis.Bitcoin.Features.Consensus.ConsensusLoop+<RewindCoinViewLockedAsync>d__39.MoveNext Reorg detected, rewinding from '337605-7fd01a034545026eef1894bf86c855ec7d4f56b45f7e4dfda389dfc5f0135a9f' to '336596-8dcc216106715238c1f6ab5a4493820047b47e56656b159802db78e42d1732b0'.
[2018-03-17 11:10:19.7013 8] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext Consensus Loop stopping
[2018-03-17 11:10:19.7013 8] FATAL: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext Consensus Loop threw an unhandled exception
[2018-03-17 11:10:19.7013 8] ERROR: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext Consensus Loop threw an unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Consensus.StakeValidator.VerifySignature(UnspentOutputs coin, Transaction txTo, Int32 txToInN, ScriptVerify flagScriptVerify) in C:\Stratis\StratisBitcoinFullNode-second-node\src\Stratis.Bitcoin.Features.Consensus\StakeValidator.cs:line 307
   at Stratis.Bitcoin.Features.Consensus.StakeValidator.CheckProofOfStake(ContextStakeInformation context, ChainedBlock prevChainedBlock, BlockStake prevBlockStake, Transaction transaction, UInt32 headerBits) in C:\Stratis\StratisBitcoinFullNode-second-node\src\Stratis.Bitcoin.Features.Consensus\StakeValidator.cs:line 174
   at Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.CheckAndComputeStake(RuleContext context) in C:\Stratis\StratisBitcoinFullNode-second-node\src\Stratis.Bitcoin.Features.Consensus\PosConsensusValidator.cs:line 192
   at Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.ExecuteBlock(RuleContext context, TaskScheduler taskScheduler) in C:\Stratis\StratisBitcoinFullNode-second-node\src\Stratis.Bitcoin.Features.Consensus\PosConsensusValidator.cs:line 121
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<ValidateAndExecuteBlockAsync>d__42.MoveNext() in C:\Stratis\StratisBitcoinFullNode-second-node\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 489
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<AcceptBlockAsync>d__40.MoveNext() in C:\Stratis\StratisBitcoinFullNode-second-node\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 360
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<PullerLoopAsync>d__38.MoveNext() in C:\Stratis\StratisBitcoinFullNode-second-node\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 306
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<<StartAsync>b__36_0>d.MoveNext() in C:\Stratis\StratisBitcoinFullNode-second-node\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 238
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Stratis\StratisBitcoinFullNode-second-node\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 129
```

The bug happens during a reorg. StakeValidator tries to fetch a coin from the CachedCoinview (but the block with this coin was reorged away). CachedCoinview don't find the coin the cache and ask inner (DBreezeCoinview) for it but it also doesn't have it so the returned UTXO is null.

**Comment by dangershony** [comment]
I see you got this error today, but I believe it was fixed here #1208 (3 days ago) are you running the latest code?

**Comment by dangershony** [comment]
Ah sorry I see this refers to the prevUtxo yeah thats a bug we need to check and throw reorg exception

**Comment by dangershony** [comment]
Though this is odd as I see the error is during the consensus loop so the rewind code and the CheckProofOfStake code should happen sequentially (meaning if the consensus loop is reorging it can't go down the path of accepting a block so it can't call simultaneously `RewindCoinViewLockedAsync` and `AcceptBlockAsync` that leads to calling `coinView.FetchCoinsAsync()` )

If a rewind happens we go back to the puller to ask for the next block after consensus tip (meaning the trx to fetch must be in store) this is very odd, I think combining this bug with #1176 we should suspect consensus is not sequential.

**Comment by noescape00** [comment]
> I think combining this bug with #1176 we should suspect consensus is not sequential.

In some rare cases it's not. 
Not sure if I can explain this since I understand it poorly myself. 

But in general the thing is that the rewind in CachedCoinView creates an inner rewind task. If this task is synchronously awaited (task.Wait()) before the task scheduler schedules that it will be executed outside of the State Machine and the code inside it will be converted to inline. 
And that's pretty much what can happen when we call WaitOngoingTasks inside the lock- instead of pausing until the task finishes execution we will run the task synchronously from that very thread.

So I think we have a good solution for this problem which would be replacing R/W lock with async lock and moving the inner awaits inside that lock which will allow us to get rid of WaitOngoingTasks (right now we have to await outside of that lock).

**Comment by dangershony** [comment]
I think that is not necessarily the problem though as we will still wait for WaitOngoingTasks before fetching coins and the state should be correct.

> replacing R/W lock with async lock

Hmm I am not sure I like this solution we are just adding complexity to an already very complex code, this code will be refactored so no need to make it async right now.

**Comment by noescape00** [comment]
>this code will be refactored so no need to make it async right now.

But it's all async already (except for `Evict`). So not many changes will be required. 

>I would more prefer to remove the waiting for tasks inside a lock insanity.

Agreed, that's a good change but I guess it's more like a performance fix so it will be reasonable to apply it during the refactoring.
