### ISSUE TITLE
Exception while stopping the node while the wallet is being restored

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#1233]
The wallet restore can currently take several hours for a very large wallets (~500Mb)
When the node is busy restoring the wallet and user decides to stop the node by pressing Ctrl+C in the console an exception is thrown: [ExceptionWhileShuttingDownNode.txt](https://github.com/stratisproject/StratisBitcoinFullNode/files/1834657/ExceptionWhileShuttingDownNode.txt)

The same error have been observed with much smaller wallet (under 100 transactions)

``info: Stratis.Bitcoin.Connection.ConnectionManagerBehavior[0]
      Peer '[::ffff:10.0.0.1]:54831' offline, reason: 'Node shutdown'.
info: Stratis.Bitcoin.FullNode[0]
      Waiting for PeriodicLog to finish.
info: Stratis.Bitcoin.Features.Api.ApiFeature[0]
      API stopping on URL 'http://localhost:37241/'.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLCJ74O86QV5", Request id "0HLCJ74O86QV5:0000056D": An unhandled exception was thrown by the application.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Stratis.Bitcoin.Features.Api.LoggingActionFilter..ctor(ILoggerFactory loggerFactory) in C:\Code\Testing\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Api\LoggingActionFilter.cs:line 22
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.TypeFilterAttribute.CreateInstance(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultFilterProvider.ProvideFilter(FilterProviderContext context, FilterItem filterItem)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultFilterProvider.OnProvidersExecuting(FilterProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.FilterFactory.CreateUncachedFiltersCore(IFilterProvider[] filterProviders, ActionContext actionContext, List`1 filterItems)
   at Microsoft.AspNetCore.Mvc.Internal.FilterFactory.CreateUncachedFilters(IFilterProvider[] filterProviders, ActionContext actionContext, FilterItem[] cachedFilterItems)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvokerCache.GetCachedResult(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler.<>c__DisplayClass12_0.<RouteAsync>b__0(HttpContext c)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
info: Stratis.Bitcoin.FullNode[0]
      Waiting for PosMining.Stake to finish.
info: Stratis.Bitcoin.Features.Miner.MiningFeature[0]``

**Comment by bokobza** [comment]
I think these are the important bits:
`An unhandled exception was thrown by the application. System.ObjectDisposedException: Cannot access a disposed object. Object name: 'LoggerFactory'. at 
Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName) at Stratis.Bitcoin.Features.Api.LoggingActionFilter..ctor(ILoggerFactory loggerFactory) in 
C:\Code\Testing\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Api\LoggingActionFilter.cs:line 22`
and 
`Waiting for PosMining.Stake to finish. info: Stratis.Bitcoin.Features.Miner.MiningFeature[0]`

**Comment by bokobza** [comment]
@maciejzaleski were you also mining while restoring?

**Comment by maciejzaleski** [comment]
That is very possible. I kick off mining every time I start the wallet.

**Comment by dangershony** [comment]
The `LoggingActionFilter` creates a new logger on every request.
This can be improved I believe.
