### ISSUE TITLE
Exception on full node while staking

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#1237]
```
======Connection======
Peer:[::ffff:13.91.95.87]:26178,         connected:outbound,        height:336987,        agent:fullnode4-StratisBitcoin:1.0.10
Peer:[::ffff:84.192.155.226]:26178,      connected:outbound,        height:336978,        agent:/Stratis:2.0.0.3/
Peer:[::ffff:13.64.76.48]:26178,         connected:outbound,        height:336984,        agent:/Stratis:2.0.0.3/
Peer:[::ffff:94.102.63.207]:26178,       connected:outbound,        height:336987,        agent:StratisBitcoin:1.0.8
Peer:[::ffff:51.141.45.80]:26178,        connected:outbound,        height:336981,        agent:/Stratis:2.0.0.3/
Peer:[::ffff:51.140.231.125]:26178,      connected:outbound,        height:336987,        agent:StratisBitcoin:1.0.10
Peer:[::ffff:54.37.46.84]:26178,         connected:outbound,        height:336981,        agent:/Stratis:2.0.0.3/
Peer:[::ffff:40.113.118.138]:26178,      connected:outbound,        height:336966,        agent:/Stratis:2.0.0.3/


[2018-03-16 23:34:00.8744 52] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake stopping
[2018-03-16 23:34:00.8744 52] FATAL: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake threw an unhandled exception
[2018-03-16 23:34:00.8744 52] ERROR: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake threw an unhandled exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Stratis.Bitcoin.Features.Miner.PosMinting.<StakeAndSignBlockAsync>d__46.MoveNext() in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 670
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Stratis.Bitcoin.Features.Miner.PosMinting.<GenerateBlocksAsync>d__44.MoveNext() in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 558
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Miner.PosMinting.<>c__DisplayClass42_0.<<Stake>b__0>d.MoveNext() in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 427
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\fullnodemike\source\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 136
[2018-03-16 23:34:02.4070 64] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__74_0 ======Node stats====== 03/16/2018 23:34:02 agent StratisBitcoin:1.0.10
Headers.Height:      336987   Headers.Hash:     0d31c770ecc99fd74419ae490a8e9730a1879c24fd9ebbccb985b16269a696b4
Consensus.Height:    336987   Consensus.Hash:   0d31c770ecc99fd74419ae490a8e9730a1879c24fd9ebbccb985b16269a696b4
BlockStore.Height:   336987   BlockStore.Hash:  0d31c770ecc99fd74419ae490a8e9730a1879c24fd9ebbccb985b16269a696b4
Wallet.Height:       336987   Wallet.Hash:      0d31c770ecc99fd74419ae490a8e9730a1879c24fd9ebbccb985b16269a696b4
```

Looks like some sort of async problem. My code is about a week old, will update it and try again.

**Comment by Aprogiena** [comment]
The already know about this issue, I just cannot remember who reported it under which number

**Comment by Aprogiena** [comment]
But it is quite trivial, it is just about removing item from a collection that is being iterated

**Comment by dangershony** [comment]
Hi @mikedennis what version of the node do you have? 
Something similar was fixed already here https://github.com/stratisproject/StratisBitcoinFullNode/commit/7bedd0440d457bb77c83fbff03382b2cc6c0f5b1

**Comment by mikedennis** [comment]
I think I would have had that change. My source was about a week old I think. At any rate I updated my source and restarted so will let you know if it happens again.

**Comment by dangershony** [comment]
Ok its very likely we fixed this already as the error you got is exactly at the same line we fixed.
I will therefor close this issue and if the error comes back just create another.
