### ISSUE TITLE
Integration Test failing at shutdown

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1240]
Occasionally one of the integration tests fails with this error.
This is aodd as it indicates a singleton service was initialized a second time on dispose which should not happen.

```

System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Stratis.Bitcoin.Features.BlockStore.BlockRepository..ctor(Network network, String folder, IDateTimeProvider dateTimeProvider, ILoggerFactory loggerFactory) in C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.BlockStore\BlockRepository.cs:line 122
   at Stratis.Bitcoin.Features.BlockStore.BlockRepository..ctor(Network network, DataFolder dataFolder, IDateTimeProvider dateTimeProvider, ILoggerFactory loggerFactory) in C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.BlockStore\BlockRepository.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Stratis.Bitcoin.Builder.FullNodeServiceProvider.<get_Features>d__2.MoveNext() in C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Builder\FullNodeServiceProvider.cs:line 36
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ReverseIterator`1.MoveNext()
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 99
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Dispose() in C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 77
   at Stratis.Bitcoin.FullNode.Dispose() in C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\FullNode.cs:line 277
   at Stratis.Bitcoin.IntegrationTests.EnvironmentMockUpHelpers.StratisBitcoinPowRunner.Kill() in C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.IntegrationTests\EnvironmentMockUpHelpers\NodeRunners.cs:line 154
   at Stratis.Bitcoin.IntegrationTests.EnvironmentMockUpHelpers.CoreNode.Kill() in C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.IntegrationTests\EnvironmentMockUpHelpers\CoreNode.cs:line 299
   at Stratis.Bitcoin.IntegrationTests.EnvironmentMockUpHelpers.NodeBuilder.Dispose() in C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.IntegrationTests\EnvironmentMockUpHelpers\NodeBuilder.cs:line 281
   at Stratis.Bitcoin.IntegrationTests.WalletTests.Given__TheNodeHadAReorg_And_ConensusTipIsdifferentFromWalletTip__When__ANewBlockArrives__Then__WalletCanRecover() in C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.IntegrationTests\WalletTests.cs:line 396

```

**Comment by Aprogiena** [comment]
These kinds of errors happen before on full node when the shutdown sequence was not correct. So you just have to make sure that order of disposals is correct

**Comment by dangershony** [comment]
Hmm I suspect its different this time as we see that the constructor of `BlockRepository` is invoked on dispose which I find very odd, that class should be a singleton and there is no place in the code (to my knowledge) where we dispose of DI so why would a singleton be instantiated again?

**Comment by Aprogiena** [comment]
I think it is the same situation as before, it looked like this. When an object is destroyed in dependency injection, then if someone wants to use it again, the new instance is created.

**Comment by dangershony** [comment]
But how did the object get destroyed this is what I can't find.
Even if the Dispose was called on the service itself the DI would not know that (or would it?)

**Comment by Aprogiena** [comment]
Can't tell at this moment comment I don't know the details of the integration tests shutdown. So all I'm saying that it really reminded me what we had before in full node. It is quite likely it will be the same thing, but it is not hundred percent guaranteed.

**Comment by dangershony** [comment]
Why do we not dispose the logger at the end?
```
        public void Dispose()
        {
            if (this.State == FullNodeState.Disposing || this.State == FullNodeState.Disposed)
                return;

            this.State = FullNodeState.Disposing;

            this.logger.LogInformation("Closing node pending...");

            // Fire INodeLifetime.Stopping.
            this.nodeLifetime.StopApplication();

            this.ConnectionManager.Dispose();
            this.loggerFactory.Dispose();

            foreach (IDisposable disposable in this.Resources)
                disposable.Dispose();

            // Fire the NodeFeatureExecutor.Stop.
            this.fullNodeFeatureExecutor.Dispose();

            // Fire INodeLifetime.Stopped.
            this.nodeLifetime.NotifyStopped();

            this.State = FullNodeState.Disposed;
        }
```

**Comment by Aprogiena** [comment]
The logger is not disposable, right?

**Comment by dangershony** [comment]
Hmm good point so this is ok, that means if the DI is creating instances at dispose then they will throw `Cannot access a disposed object. Object name: 'LoggerFactory'.`

This is ok what we need to understand is why is the DI creating new instances at dispose time.
