### ISSUE TITLE
BlockPuller: Collection Modified bug

### ISSUE THREAD

**Issue by Derrick-** [stratisproject/StratisBitcoinFullNode#126]
Happened right after startup. Will investigate further.

```
info: Stratis.Bitcoin.FullNode[0]
      PeriodicLog starting
info: Stratis.Bitcoin.Connection[0]
      Node [::ffff:217.119.149.253]:8333 connected (outbound), agent /Satoshi:0.13.2/, height 463506
crit: Stratis.Bitcoin.Consensus[0]
      Consensus loop unhandled exception (Tip:463504)
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Stratis.Bitcoin.BlockPulling.BlockPuller.AssignPendingVectors() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\BlockPulling\BlockPuller.cs:line 268
   at Stratis.Bitcoin.BlockPulling.BlockPuller.OnStalling(ChainedBlock chainedBlock) in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\BlockPulling\BlockPuller.cs:line 306
   at Stratis.Bitcoin.BlockPulling.LookaheadBlockPuller.NextBlockCore(CancellationToken cancellationToken) in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\BlockPulling\LookaheadBlockPuller.cs:line 299
   at Stratis.Bitcoin.BlockPulling.LookaheadBlockPuller.NextBlock(CancellationToken cancellationToken) in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\BlockPulling\LookaheadBlockPuller.cs:line 125
   at Stratis.Bitcoin.Consensus.ConsensusLoop.ExecuteNextBlock(CancellationToken cancellationToken) in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\ConsensusLoop.cs:line 145
   at Stratis.Bitcoin.Consensus.ConsensusLoop.<Execute>d__21.MoveNext() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\ConsensusLoop.cs:line 121
   at Stratis.Bitcoin.Consensus.ConsensusFeature.RunLoop() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\ConsensusFeature.cs:line 106

Unhandled Exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Stratis.Bitcoin.BlockPulling.BlockPuller.AssignPendingVectors() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\BlockPulling\BlockPuller.cs:line 268
   at Stratis.Bitcoin.BlockPulling.BlockPuller.OnStalling(ChainedBlock chainedBlock) in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\BlockPulling\BlockPuller.cs:line 306
   at Stratis.Bitcoin.BlockPulling.LookaheadBlockPuller.NextBlockCore(CancellationToken cancellationToken) in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\BlockPulling\LookaheadBlockPuller.cs:line 299
   at Stratis.Bitcoin.BlockPulling.LookaheadBlockPuller.NextBlock(CancellationToken cancellationToken) in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\BlockPulling\LookaheadBlockPuller.cs:line 125
   at Stratis.Bitcoin.Consensus.ConsensusLoop.ExecuteNextBlock(CancellationToken cancellationToken) in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\ConsensusLoop.cs:line 145
   at Stratis.Bitcoin.Consensus.ConsensusLoop.<Execute>d__21.MoveNext() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\ConsensusLoop.cs:line 121
   at Stratis.Bitcoin.Consensus.ConsensusFeature.RunLoop() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\ConsensusFeature.cs:line 165
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by dangershony** [comment]
Ahhhh I know what the issue is, ops my bad.
vectors.Remove(vector); is called inside the enumerator.

**Comment by dangershony** [comment]
To solve it either add this code 
```
	foreach (var vector in vectors.ToList())
```
or add to a second list and remove from the vector list after the enumeration

**Comment by Derrick-** [comment]
I'm on it
