### ISSUE TITLE
[Stratis.BreezeD] System.InvalidOperationException 

### ISSUE THREAD

**Issue by D3m0nKingx** [stratisproject/StratisBitcoinFullNode#1291]
```
      Starting node...
fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred starting the application: System.InvalidOperationException: Unable to resolve service for type 'Stratis.Bitcoin.Features.Wallet.WalletSettings' while attempting to activate 'Stratis.Bitcoin.Features.Wallet.WalletManager'.
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
         at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
         at Stratis.Bitcoin.Builder.FullNodeServiceProvider.get_Features()+MoveNext() in /home/ader/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Builder/FullNodeServiceProvider.cs:line 36
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in /home/ader/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 99
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Initialize() in /home/ader/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 56
There was a problem initializing the node. Details: 'Unable to resolve service for type 'Stratis.Bitcoin.Features.Wallet.WalletSettings' while attempting to activate 'Stratis.Bitcoin.Features.Wallet.WalletManager'.'
Application is shutting down...
The CancellationTokenSource has been disposed.
```

**Comment by bokobza** [comment]
Hi @D3m0nKingx , what did you run?

**Comment by D3m0nKingx** [comment]
Stratis.BreezeD. Same exception occurs on mainnet for bitcoin and stratis

**Comment by D3m0nKingx** [comment]
It works fine on commit [dc9c40](https://github.com/stratisproject/StratisBitcoinFullNode/pull/1193)

**Comment by bokobza** [comment]
I'll have a look, thanks mate.

**Comment by bokobza** [comment]
Fixed in https://github.com/stratisproject/StratisBitcoinFullNode/pull/1303
