### ISSUE TITLE
Exception in Periodic peer flush

### ISSUE THREAD

**Issue by bokobza** [stratisproject/StratisBitcoinFullNode#1420]
While syncing bitcoin Mainnet IBD, I encountered this:

```

[2018-05-17 21:32:41.5325 13] INFO: Stratis.Bitcoin.Features.Wallet.WalletManager.<Start>b__28_0 Wallets saved to file at 05/17/2018 21:32:41.
[2018-05-17 21:32:41.5325 15] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__75_0 ======Node stats====== 05/17/2018 21:32:41 agent StratisBitcoin:1.1.2
Headers.Height:      523156   Headers.Hash:     000000000000000000282956c72c31f8245af7a3ddc00c001ff7e590d2f66d49
Consensus.Height:    220659   Consensus.Hash:   00000000000000d5f9a2c3297c8e0ced836569f928d5e0c592f86e7a87683b87
BlockStore.Height:   220633   BlockStore.Hash:  00000000000002bda08f9acd807812b84441d0e7ea139ef74cad69e9024b4240
Wallet.Height:       No Wallet

======Mempool======
MempoolSize: 0    DynamicSize: 0 kb   OrphanSize: 0   

======Connection======
Peer:[::ffff:62.109.20.99]:8333,         connected:outbound,        height:523156,        agent:/Satoshi:0.15.1/
Peer:[::ffff:199.182.129.26]:8333,       connected:outbound,        height:523156,        agent:/Satoshi:0.16.0/
Peer:[::ffff:113.252.193.10]:8333,       connected:outbound,        height:523156,        agent:/Satoshi:0.15.1/
Peer:[::ffff:91.106.194.97]:8333,        connected:outbound,        height:523156,        agent:/Satoshi:0.16.0/
Peer:[::ffff:176.9.109.123]:8333,        connected:outbound,        height:523156,        agent:/Satoshi:0.16.0/
Peer:[::ffff:204.9.50.25]:8333,          connected:outbound,        height:523156,        agent:/Satoshi:0.15.1/
Peer:[::ffff:67.205.142.50]:8333,        connected:outbound,        height:523156,        agent:/Satoshi:0.16.0/
Peer:[::ffff:67.149.65.252]:8333,        connected:outbound,        height:523156,        agent:/Satoshi:0.15.1/


[2018-05-17 21:32:41.5388 36] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext Periodic peer flush... stopping
[2018-05-17 21:32:41.5694 36] FATAL: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext Periodic peer flush... threw an unhandled exception
[2018-05-17 21:32:41.5694 36] ERROR: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext Periodic peer flush... threw an unhandled exception: System.ArgumentException: The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair`2[] array, Int32 index)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__3.MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stratis.Bitcoin.P2P.PeerAddressManager.SavePeers() in D:\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\PeerAddressManager.cs:line 162
   at Stratis.Bitcoin.Base.BaseFeature.<StartAddressManager>b__26_0(CancellationToken token) in D:\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Base\BaseFeature.cs:line 267
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in D:\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 136
[2018-05-17 21:32:41.5956 32] INFO: Stratis.Bitcoin.Features.Consensus.ConsensusStats+<LogAsync>d__14.MoveNext ======Block Puller======
Lookahead:          947 blocks
Downloaded:         878 blocks
==========================
Persistent Tip:     219775
Cache Tip           220660
Cache entries       177585
====Blk Fetching Speed====
Transactions:       0.0000 ms/tx
```

**Comment by dangershony** [comment]
Hmmm its probably a race condition, we should

```
Change this:
            fileStorage.SaveToFile(this.peers.OrderByDescending(p => p.Value.LastConnectionSuccess).Select(p => p.Value).ToList(), PeerFileName);

To this:
            fileStorage.SaveToFile(this.peers.ToList().OrderByDescending(p => p.Value.LastConnectionSuccess).Select(p => p.Value).ToList(), PeerFileName);

```

**Comment by monsieurleberre** [comment]
I am not sure ToList() will fix it, but it looks like ToArray should:

https://stackoverflow.com/questions/43924965/how-to-get-moment-in-time-snapshot-of-concurrentdictionary-in-c

The source code in .Net core does take a lock on the dictionary before enumerating it
I can try that...

**Comment by bokobza** [comment]
Closed with https://github.com/stratisproject/StratisBitcoinFullNode/pull/1664
