### ISSUE TITLE
v1.1.0-beta Release: critical error when I try to start staking on testnet

### ISSUE THREAD

**Issue by mwherman2000** [stratisproject/StratisBitcoinFullNode#1430]
Using release: https://github.com/stratisproject/StratisBitcoinFullNode/releases/tag/v1.1.0-beta

When I use `http://localhost:38221/swagger/#!/Miner/ApiMinerStartstakingPost` to stop and then start staking, I get the following error.  This full node has been running continuously for about one day.

```
info: Stratis.Bitcoin.Features.Miner.MiningFeature[0]
      Staking enabled on wallet 'GatewayTest2'.
info: Stratis.Bitcoin.FullNode[0]
      PosMining.Stake starting
info: Stratis.Bitcoin.FullNode[0]
      PosMining.Stake stopping
crit: Stratis.Bitcoin.FullNode[0]
      PosMining.Stake threw an unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Miner.PosMinting.<GenerateBlocksAsync>d__44.MoveNext() in D:\STRATIS\repos\StratisBitcoinFullNode-1.1.0-beta\StratisBitcoinFullNode-1.1.0-beta\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 523
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Miner.PosMinting.<>c__DisplayClass42_0.<<Stake>b__0>d.MoveNext() in D:\STRATIS\repos\StratisBitcoinFullNode-1.1.0-beta\StratisBitcoinFullNode-1.1.0-beta\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 426
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in D:\STRATIS\repos\StratisBitcoinFullNode-1.1.0-beta\StratisBitcoinFullNode-1.1.0-beta\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 136
fail: Stratis.Bitcoin.FullNode[0]
      PosMining.Stake threw an unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
         at Stratis.Bitcoin.Features.Miner.PosMinting.<GenerateBlocksAsync>d__44.MoveNext() in D:\STRATIS\repos\StratisBitcoinFullNode-1.1.0-beta\StratisBitcoinFullNode-1.1.0-beta\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 523
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.Miner.PosMinting.<>c__DisplayClass42_0.<<Stake>b__0>d.MoveNext() in D:\STRATIS\repos\StratisBitcoinFullNode-1.1.0-beta\StratisBitcoinFullNode-1.1.0-beta\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 426
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in D:\STRATIS\repos\StratisBitcoinFullNode-1.1.0-beta\StratisBitcoinFullNode-1.1.0-beta\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 136
info: Stratis.Bitcoin.FullNode[0]
      ======Node stats====== 05/20/2018 17:08:42 agent StratisBitcoin:1.1.0
      Headers.Height:      413877   Headers.Hash:     b436963dd33017c4ba2d059a3a76a0cbffff1cad5b0aeb7f552fb01792fde012
      Consensus.Height:    413877   Consensus.Hash:   b436963dd33017c4ba2d059a3a76a0cbffff1cad5b0aeb7f552fb01792fde012
      BlockStore.Height:   413877   BlockStore.Hash:  b436963dd33017c4ba2d059a3a76a0cbffff1cad5b0aeb7f552fb01792fde012
      Wallet.Height:       413877   Wallet.Hash:      b436963dd33017c4ba2d059a3a76a0cbffff1cad5b0aeb7f552fb01792fde012

      ======Mempool======
      MempoolSize: 0    DynamicSize: 0 kb   OrphanSize: 0

      ======Wallets======
      Wallet: GatewayTest2,        Confirmed balance: 16732.32117344
      Wallet: GatewayTest1,        Confirmed balance: 100.00000000
```

**Comment by Aprogiena** [comment]
most likely just duplicate of already closed issue https://github.com/stratisproject/StratisBitcoinFullNode/issues/1338

**Comment by mwherman2000** [comment]
@Aprogiena It was closed as not reproducible.  Mine is reproducible ...staking cannot be restarted on this node.  CC: @dangershony

**Comment by Aprogiena** [comment]
It was also closed because there was pull request that fixed the probable cause. Issue should be reopened only if you can reproduce it on the latest master. So, can you reproduce it on the latest master?

**Comment by mwherman2000** [comment]
@Aprogiena I can fork and clone the current master.  I don't know what the trigger is to cause the failure but I'm on a freshly built,clean Windows 10 Pro machine (not a VM) with only Stratis and dotnet core on it.

I ran the full node for about 24 hours and then it stopped staking and wasn't restartable.   I'll try to get this going today.
