### ISSUE TITLE
SmartContractGasInjector creates an invalid program in methods with nested loops.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1698]
When there are nested loops of non-constant iterations, the GasInjector injects the SpendGas code in such a way that the resulting CIL is invalid. When we try to execute the method via reflection we get the following exception: `System.InvalidProgramException: Common Language Runtime detected an invalid program.`

Playing with it myself, I was able to find the following code that will produce this bug:
```
using Stratis.SmartContracts;

public sealed class ThrowExceptionContract : SmartContract
{
    public ThrowExceptionContract(ISmartContractState state)
        : base(state)
    {
    }

    string SampleString { get; set;}

    public void ThrowException()
    {
        SampleString = "test";
        for(int i = 0; i < SampleString.Length; i++)
        {
            SampleString += "1";
            for(int j=0; j < SampleString.Length; j++)
            {
                SampleString = "example";
                SampleString += "2";
            }
        }
    }
}
```

Yes, the code is nonsensical  but it should still execute (possibly just until it runs out of gas).

We should have a test for code similar to the above (ideally a more realistic use case) in SmartContractExecutorTests, and fix the issue.

Current Bounty: 50 STRAT.

**Comment by damien-r** [comment]
Hi,
I got the same problem with consecutive if when they are at least 4 case. Example:

 ```
public string Value
{
    get { return PersistentState.GetString(nameof(Value)); }
    set { PersistentState.SetString(nameof(Value), value); }
}

public void IfNesting(string value)
{
    if(value == "a")
    {
        Value = "A";
    }
    else if(value.Contains("b"))
    {
        Value = "B";
    }
    else if(value.StartsWith("c"))
    {
        Value = "C";
    }
    else
    {
         Value = "D";
    }
}
```

Generates the following error:

```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at SCToDebug.IfNesting(String value)
   at IFT.CosmoHelvetia.FD.FDNodeServer.Managers.Implementations.SmartContractManager.CallMethod(String walletName, String walletPassword, String methodName, Object[] parameters) in C:\Workspaces\CosmoHeveltia.FairyDust\src\FairyDust\FDNodeServer\Managers\Implementations\SmartContractManager.cs:line 65
   at IFT.CosmoHelvetia.FD.FDNodeServer.Managers.Implementations.SmartContractManager.CallMethod(String walletName, String walletPassword, String methodName, Object[] parameters) in C:\Workspaces\CosmoHeveltia.FairyDust\src\FairyDust\FDNodeServer\Managers\Implementations\SmartContractManager.cs:line 81
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at IFT.CosmoHelvetia.FD.SmartContractsTest.SmartContractDebugger.CallSCAsync(String scAddress) in C:\Workspaces\CosmoHeveltia.FairyDust\src\FairyDust.Tests\SmartContractsTest\SmartContractsTest\SmartContractDebugger.cs:line 77
   at IFT.CosmoHelvetia.FD.SmartContractsTest.SmartContractDebugger.Run() in C:\Workspaces\CosmoHeveltia.FairyDust\src\FairyDust.Tests\SmartContractsTest\SmartContractsTest\SmartContractDebugger.cs:line 153
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at IFT.CosmoHelvetia.FD.SmartContractsTest.SmartContractDebugger.Main(String[] args) in C:\Workspaces\CosmoHeveltia.FairyDust\src\FairyDust.Tests\SmartContractsTest\SmartContractsTest\SmartContractDebugger.cs:line 27
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (An error occurred while trying to call smart contract IfNesting: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at SCToDebug.IfNesting(String value)) ---> System.Exception: An error occurred while trying to call smart contract IfNesting: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at SCToDebug.IfNesting(String value)
   at IFT.CosmoHelvetia.FD.FDNodeServer.Managers.Implementations.SmartContractManager.CallMethod(String walletName, String walletPassword, String methodName, Object[] parameters) in C:\Workspaces\CosmoHeveltia.FairyDust\src\FairyDust\FDNodeServer\Managers\Implementations\SmartContractManager.cs:line 65
   at IFT.CosmoHelvetia.FD.FDNodeServer.Managers.Implementations.SmartContractManager.CallMethod(String walletName, String walletPassword, String methodName, Object[] parameters) in C:\Workspaces\CosmoHeveltia.FairyDust\src\FairyDust\FDNodeServer\Managers\Implementations\SmartContractManager.cs:line 81
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at IFT.CosmoHelvetia.FD.SmartContractsTest.SmartContractDebugger.CallSCAsync(String scAddress) in C:\Workspaces\CosmoHeveltia.FairyDust\src\FairyDust.Tests\SmartContractsTest\SmartContractsTest\SmartContractDebugger.cs:line 77
   at IFT.CosmoHelvetia.FD.SmartContractsTest.SmartContractDebugger.Run() in C:\Workspaces\CosmoHeveltia.FairyDust\src\FairyDust.Tests\SmartContractsTest\SmartContractsTest\SmartContractDebugger.cs:line 153
---> (Inner Exception #0) System.Exception: An error occurred while trying to call smart contract IfNesting: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at SCToDebug.IfNesting(String value)
   at IFT.CosmoHelvetia.FD.FDNodeServer.Managers.Implementations.SmartContractManager.CallMethod(String walletName, String walletPassword, String methodName, Object[] parameters) in C:\Workspaces\CosmoHeveltia.FairyDust\src\FairyDust\FDNodeServer\Managers\Implementations\SmartContractManager.cs:line 65
   at IFT.CosmoHelvetia.FD.FDNodeServer.Managers.Implementations.SmartContractManager.CallMethod(String walletName, String walletPassword, String methodName, Object[] parameters) in C:\Workspaces\CosmoHeveltia.FairyDust\src\FairyDust\FDNodeServer\Managers\Implementations\SmartContractManager.cs:line 81
```

**Comment by nathanielcook** [comment]
Got a PR up for this one [here](https://github.com/stratisproject/StratisBitcoinFullNode/pull/2362). Looks like you're using the master branch now for smart contract work. Is that correct?

**Comment by rowandh** [comment]
@nathanielcook that's correct.
