### ISSUE TITLE
Fix shutdown sequence

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#2166]
Currently it seems that shutdown sequence is broken, we need to fix it. We always need to think in very simple terms – which component must be disposed before another component. For example if we have a component that delivers new blocks and those blocks then are validated by another component, first we need to make sure that we terminate the first component in order to prevent new blocks to arrive, only then we want to terminate the second component. Same must be done for every pair of components

**Comment by D3m0nKingx** [comment]
I agree here something isn't kosher.  I started from a fresh sync (no .stratisnode folder). Waited for some peers to connect (4) then shutdown the node (Ctrl+C) after about 3,800 blocks. 

Noticed two things:

1) dotnet process doesn't terminate even so in the console it says the "Application is shutting down" (even after waiting 5 mins):
![image](https://user-images.githubusercontent.com/18432686/46662228-dbe4dd00-cb88-11e8-9ad3-0cd04856c75c.png)


2) restarting the node (whether killing the prior dotnet process or not), the node only reaches the state of:
![image](https://user-images.githubusercontent.com/18432686/46662267-f323ca80-cb88-11e8-8441-e4df91b9c7af.png)

No further activity seems to occur from this point. However when I force kill the process `killall -9 dotnet` it shows: 
```bash
info: Stratis.Bitcoin.FullNode[0]
      Periodic peer flush starting.
```

The log file:
```bash
[2018-10-09 09:57:10.0873 1] INFO: Stratis.Bitcoin.FullNode.Initialize Full node initialized on StratisMain.
[2018-10-09 09:57:10.1333 1] INFO: Stratis.Bitcoin.FullNode.Start Starting node.
[2018-10-09 09:57:10.7122 1] INFO: Stratis.Bitcoin.Base.BaseFeature+<StartChainAsync>d__27.MoveNext Loading finalized block height.
[2018-10-09 09:57:10.8180 7] INFO: Stratis.Bitcoin.Base.BaseFeature+<StartChainAsync>d__27.MoveNext Loading chain.
[2018-10-09 09:57:11.1529 5] INFO: Stratis.Bitcoin.Base.BaseFeature+<StartChainAsync>d__27.MoveNext Chain loaded at height 3839.
[2018-10-09 09:57:11.1671 6] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext FlushChain starting in 60 seconds.
[2018-10-09 09:57:11.1752 5] INFO: Stratis.Bitcoin.Base.BaseFeature.StartAddressManager Loading peers from : /home/demon/.stratisnode/stratis/StratisMain.
[2018-10-09 09:57:11.5335 6] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext Periodic peer flush starting in 300 seconds.
[2018-10-09 09:58:11.1730 6] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext FlushChain starting.
[2018-10-09 10:02:11.5357 9] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext Periodic peer flush starting
```

**Comment by D3m0nKingx** [comment]
From this I'm assuming there's something going on with the DB maybe... so through a process of elimination... I deleted **ONLY** the contents of **/home/demon/.stratisnode/stratis/StratisMain/chain**

And this produced the following error:

```C#
fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred starting the application.
There was a problem initializing the node. Details: 'System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Value cannot be null.
Parameter name: block) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Consensus.StakeChainStore.LoadAsync() in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin.Features.Consensus/StakeChainStore.cs:line 58
   at Stratis.Bitcoin.Features.Consensus.Rules.PosConsensusRuleEngine.Initialize() in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin.Features.Consensus/Rules/PosConsensusRuleEngine.cs:line 52
   at Stratis.Bitcoin.Base.BaseFeature.InitializeAsync() in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Base/BaseFeature.cs:line 201
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 52
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 102
   --- End of inner exception stack trace ---
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 120
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Initialize() in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 52
   at Stratis.Bitcoin.FullNode.Start() in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/FullNode.cs:line 211
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.RunAsync(IFullNode node, CancellationToken cancellationToken, String shutdownMessage, String shutdownCompleteMessage) in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Utilities/FullNodeExtensions.cs:line 71
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.RunAsync(IFullNode node) in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Utilities/FullNodeExtensions.cs:line 53
   at Stratis.StratisD.Program.Main(String[] args) in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.StratisD/Program.cs:line 40
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Consensus.StakeChainStore.LoadAsync() in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin.Features.Consensus/StakeChainStore.cs:line 58
   at Stratis.Bitcoin.Features.Consensus.Rules.PosConsensusRuleEngine.Initialize() in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin.Features.Consensus/Rules/PosConsensusRuleEngine.cs:line 52
   at Stratis.Bitcoin.Base.BaseFeature.InitializeAsync() in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Base/BaseFeature.cs:line 201
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 52
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 102<---

---> (Inner Exception #1) System.ArgumentNullException: Value cannot be null.
Parameter name: block
   at Stratis.Bitcoin.Utilities.Guard.NotNull[T](T value, String parameterName) in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Utilities/Guard.cs:line 49
   at Stratis.Bitcoin.Base.Deployments.NodeDeployments.GetFlags(ChainedHeader block) in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Base/Deployments/NodeDeployments.cs:line 28
   at Stratis.Bitcoin.Features.Consensus.ConsensusFeature.InitializeAsync() in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs:line 59
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 52
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in /home/demon/coins/StratisBitcoinFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 102<---

Application is shutting down.
The CancellationTokenSource has been disposed.
```
@Aprogiena @bokobza This seems to be what @sondreb experienced in #2428.

**Comment by dangershony** [comment]
Yes I am investigating this now thanks.
