### ISSUE TITLE
Bug during node shutdown

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2174]
Node stopped advancing. Shutted it down, resulted in following error: 

```
fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred stopping the application
There was a problem initializing the node. Details: 'System.AggregateException: One or more errors occurred. (One or more errors occurred. (Assertion failed)) ---> System.AggregateException: One or more errors occurred. (Assertion failed) ---> System.Exception: Assertion failed
   at Stratis.Bitcoin.Utilities.Guard.Assert(Boolean condition) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\Guard.cs:line 22
   at Stratis.Bitcoin.Features.Consensus.StakeChainStore.GetAsync(uint256 blockid) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\StakeChainStore.cs:line 91
   at Stratis.Bitcoin.Features.Consensus.StakeChainStore.Get(uint256 blockid) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\StakeChainStore.cs:line 112
   at Stratis.Bitcoin.Features.Consensus.StakeValidator.GetLastPowPosChainedBlock(IStakeChain stakeChain, ChainedHeader startChainedHeader, Boolean proofOfStake) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\StakeValidator.cs:line 95
   at Stratis.Bitcoin.Features.Consensus.StakeValidator.GetNextTargetRequired(IStakeChain stakeChain, ChainedHeader chainedHeader, IConsensus consensus, Boolean proofOfStake) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\StakeValidator.cs:line 159
   at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.CheckDifficultyHybridRule.RunAsync(RuleContext context) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\CheckDifficultyHybridRule.cs:line 45
   at Stratis.Bitcoin.Consensus.ConsensusRuleEngine.ExecuteRulesAsync(IEnumerable`1 asyncRules, RuleContext ruleContext) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\ConsensusRuleEngine.cs:line 230
   at Stratis.Bitcoin.Consensus.ConsensusRuleEngine.PartialValidationAsync(ChainedHeader header, Block block) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\ConsensusRuleEngine.cs:line 213
   at Stratis.Bitcoin.Consensus.Validators.PartialValidator.OnEnqueueAsync(PartialValidationItem item, CancellationToken cancellationtoken) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\Validators\BlockValidator.cs:line 154
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.ConsumerAsync() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 135
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.DisposeInternal(Boolean calledFromConsumerTask) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 248
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.Dispose() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 234
   at Stratis.Bitcoin.Consensus.Validators.PartialValidator.Dispose() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\Validators\BlockValidator.cs:line 147
   at Stratis.Bitcoin.Consensus.ConsensusManager.Dispose() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 1228
   at Stratis.Bitcoin.Base.BaseFeature.Dispose() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Base\BaseFeature.cs:line 301
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Dispose>b__4_0(IFullNodeFeature feature) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 71
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 102
   --- End of inner exception stack trace ---
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 120
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Dispose() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 71
   at Stratis.Bitcoin.FullNode.Dispose() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\FullNode.cs:line 278
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.RunAsync(IFullNode node, CancellationToken cancellationToken, String shutdownMessage, String shutdownCompleteMessage) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\FullNodeExtensions.cs:line 95
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.RunAsync(IFullNode node) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\FullNodeExtensions.cs:line 53
   at Stratis.StratisD.Program.Main(String[] args) in C:\Users\user\Desktop\StratisRepository\src\Stratis.StratisD\Program.cs:line 40
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Assertion failed) ---> System.Exception: Assertion failed
   at Stratis.Bitcoin.Utilities.Guard.Assert(Boolean condition) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\Guard.cs:line 22
   at Stratis.Bitcoin.Features.Consensus.StakeChainStore.GetAsync(uint256 blockid) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\StakeChainStore.cs:line 91
   at Stratis.Bitcoin.Features.Consensus.StakeChainStore.Get(uint256 blockid) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\StakeChainStore.cs:line 112
   at Stratis.Bitcoin.Features.Consensus.StakeValidator.GetLastPowPosChainedBlock(IStakeChain stakeChain, ChainedHeader startChainedHeader, Boolean proofOfStake) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\StakeValidator.cs:line 95
   at Stratis.Bitcoin.Features.Consensus.StakeValidator.GetNextTargetRequired(IStakeChain stakeChain, ChainedHeader chainedHeader, IConsensus consensus, Boolean proofOfStake) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\StakeValidator.cs:line 159
   at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.CheckDifficultyHybridRule.RunAsync(RuleContext context) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\CheckDifficultyHybridRule.cs:line 45
   at Stratis.Bitcoin.Consensus.ConsensusRuleEngine.ExecuteRulesAsync(IEnumerable`1 asyncRules, RuleContext ruleContext) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\ConsensusRuleEngine.cs:line 230
   at Stratis.Bitcoin.Consensus.ConsensusRuleEngine.PartialValidationAsync(ChainedHeader header, Block block) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\ConsensusRuleEngine.cs:line 213
   at Stratis.Bitcoin.Consensus.Validators.PartialValidator.OnEnqueueAsync(PartialValidationItem item, CancellationToken cancellationtoken) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\Validators\BlockValidator.cs:line 154
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.ConsumerAsync() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 135
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.DisposeInternal(Boolean calledFromConsumerTask) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 248
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.Dispose() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 234
   at Stratis.Bitcoin.Consensus.Validators.PartialValidator.Dispose() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\Validators\BlockValidator.cs:line 147
   at Stratis.Bitcoin.Consensus.ConsensusManager.Dispose() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 1228
   at Stratis.Bitcoin.Base.BaseFeature.Dispose() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Base\BaseFeature.cs:line 301
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Dispose>b__4_0(IFullNodeFeature feature) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 71
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 102
---> (Inner Exception #0) System.Exception: Assertion failed
   at Stratis.Bitcoin.Utilities.Guard.Assert(Boolean condition) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\Guard.cs:line 22
   at Stratis.Bitcoin.Features.Consensus.StakeChainStore.GetAsync(uint256 blockid) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\StakeChainStore.cs:line 91
   at Stratis.Bitcoin.Features.Consensus.StakeChainStore.Get(uint256 blockid) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\StakeChainStore.cs:line 112
   at Stratis.Bitcoin.Features.Consensus.StakeValidator.GetLastPowPosChainedBlock(IStakeChain stakeChain, ChainedHeader startChainedHeader, Boolean proofOfStake) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\StakeValidator.cs:line 95
   at Stratis.Bitcoin.Features.Consensus.StakeValidator.GetNextTargetRequired(IStakeChain stakeChain, ChainedHeader chainedHeader, IConsensus consensus, Boolean proofOfStake) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\StakeValidator.cs:line 159
   at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.CheckDifficultyHybridRule.RunAsync(RuleContext context) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\CheckDifficultyHybridRule.cs:line 45
   at Stratis.Bitcoin.Consensus.ConsensusRuleEngine.ExecuteRulesAsync(IEnumerable`1 asyncRules, RuleContext ruleContext) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\ConsensusRuleEngine.cs:line 230
   at Stratis.Bitcoin.Consensus.ConsensusRuleEngine.PartialValidationAsync(ChainedHeader header, Block block) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\ConsensusRuleEngine.cs:line 213
   at Stratis.Bitcoin.Consensus.Validators.PartialValidator.OnEnqueueAsync(PartialValidationItem item, CancellationToken cancellationtoken) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Consensus\Validators\BlockValidator.cs:line 154
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.ConsumerAsync() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 135<---
<---
'```

**Comment by noescape00** [comment]
@dangershony I saw on slack that you found cause of this StakeChain bug. 
Are you working on it?

**Comment by noescape00** [comment]
@dangershony do you know the state of the issue? I didn't see the bug this week.

**Comment by dangershony** [comment]
Ah yes this can be closed
