### ISSUE TITLE
Missing stake information, delete the data folder and re-download the chain

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#2428]
Seeing this too often to be a rare problem, it stops the startup of the daemon. It does not repair itself on second startup either.

```
[2018-10-08 23:31:36.8139 11] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext Periodic peer flush starting in 300 seconds.
[2018-10-08 23:31:37.0342 1] ERROR: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute An error occurred: 'Stratis.Bitcoin.Configuration.ConfigurationException: Missing stake information, delete the data folder and re-download the chain
   at Stratis.Bitcoin.Features.Consensus.StakeChainStore.LoadAsync()
   at Stratis.Bitcoin.Features.Consensus.Rules.PosConsensusRuleEngine.Initialize() in D:\a\1\s\src\Stratis.Bitcoin.Features.Consensus\Rules\PosConsensusRuleEngine.cs:line 52
   at Stratis.Bitcoin.Base.BaseFeature.InitializeAsync() in D:\a\1\s\src\Stratis.Bitcoin\Base\BaseFeature.cs:line 203
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in D:\a\1\s\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 52
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in D:\a\1\s\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 102'
[2018-10-08 23:31:37.0533 1] ERROR: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute An error occurred: 'System.ArgumentNullException: Value cannot be null.
Parameter name: block
   at Stratis.Bitcoin.Utilities.Guard.NotNull[T](T value, String parameterName) in D:\a\1\s\src\Stratis.Bitcoin\Utilities\Guard.cs:line 46
   at Stratis.Bitcoin.Base.Deployments.NodeDeployments.GetFlags(ChainedHeader block) in D:\a\1\s\src\Stratis.Bitcoin\Base\Deployments\NodeDeployments.cs:line 28
   at Stratis.Bitcoin.Features.Consensus.ConsensusFeature.InitializeAsync() in D:\a\1\s\src\Stratis.Bitcoin.Features.Consensus\ConsensusFeature.cs:line 59
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in D:\a\1\s\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 52
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in D:\a\1\s\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 102'
[2018-10-08 23:31:37.0533 1] INFO: Stratis.Bitcoin.Features.MemoryPool.MempoolManager+<LoadPoolAsync>d__25.MoveNext Loading Memory Pool.
```

Not sure if this is related to #426 in any way?

**Comment by bokobza** [comment]
I assume you have the latest version of the code.
There was a big change about a month ago that included changes in the db so that requires a delete of the data folder.
Have you tried to delete the folder and this error keeps appearing?

**Comment by D3m0nKingx** [comment]
Re-posting my findings here: https://github.com/stratisproject/StratisBitcoinFullNode/issues/2166#issuecomment-428139829

**Comment by dangershony** [comment]
I believe this bug means the stake store and the coin view db are out of sync, mainly because stake store is behind and does not have the blocks it needs to come to the height of coinview.

The solution is to rewind coinview (or find the blocks in block store), the odd thing is this should not happen as we always flush stake store before we flush coin view.

@sondreb if you have any usefull way to reproduce this it will help.
I believe @majikandy also gets this often.

**Comment by majikandy** [comment]
I have code from 7 days ago and have experienced this 4 times.

this can reasonably reliably br recreated by staking (possibly staking on another node) and then killing the Daemon in TaskManager

**Comment by dangershony** [comment]
Ok I know what the bug is, or at least one of the bugs.

This component relays on the tip hash of coinview be present in chain (ConcurrentChain) If a node crashes and chain is not persisted correctly (chain height is lower then coinview tip) we get this bug.

I will try to submit a fix today where we do the same as in ConsensusManager (and rewind coinview so the node can also recover)
