### ISSUE TITLE
Whitebind is not working as expected

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2499]
When adding a whitebind host the node will try to bind to that address and fails with exception.

```crit: Stratis.Bitcoin.Connection.ConnectionManager[0]
      Unable to listen on port 16178 (you can change the port using '-port=[number]'). Error message: Cannot assign requested address
info: Stratis.Bitcoin.FullNode[0]
      PeerConnectorDiscovery.ConnectAsync starting.
There was a problem initializing the node. Details: 'System.Net.Sockets.SocketException (99): Cannot assign requested address
   at Stratis.Bitcoin.Connection.ConnectionManager.StartNodeServer() in C:\Code\InternalTestnet\tmp\StratisBitcoinFullNode\src\Stratis.Bitcoin\Connection\ConnectionManager.cs:line 197
   at Stratis.Bitcoin.Connection.ConnectionManager.Initialize(IConsensusManager consensusManager) in C:\Code\InternalTestnet\tmp\StratisBitcoinFullNode\src\Stratis.Bitcoin\Connection\ConnectionManager.cs:line 141
   at Stratis.Bitcoin.FullNode.Start() in C:\Code\InternalTestnet\tmp\StratisBitcoinFullNode\src\Stratis.Bitcoin\FullNode.cs:line 215
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.RunAsync(IFullNode node, CancellationToken cancellationToken, String shutdownMessage, String shutdownCompleteMessage) in C:\Code\InternalTestnet\tmp\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\FullNodeExtensions.cs:line 71
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.RunAsync(IFullNode node) in C:\Code\InternalTestnet\tmp\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\FullNodeExtensions.cs:line 53
   at Stratis.StratisD.Program.Main(String[] args) in C:\Code\InternalTestnet\tmp\StratisBitcoinFullNode\src\Stratis.StratisD\Program.cs:line 45
```

**This is caused by adding a remote IP address to the list of local interfaces the node should be listening on:**
```
this.Listen.AddRange(config.GetAll("whitebind", this.logger)
                        .Select(c => new NodeServerEndpoint(c.ToIPEndPoint(this.Port), true)));
```

**Comment by maciejzaleski** [comment]
PRs: #2715 and #2752

**Comment by dangershony** [comment]
@maciejzaleski is this not resolved?

**Comment by maciejzaleski** [comment]
Resolved
