### ISSUE TITLE
[RPC] sendtoaddress compatibility with stratisX

### ISSUE THREAD

**Issue by zeptin** [stratisproject/StratisBitcoinFullNode#2616]
When using the following two versions of `sendtoaddress` only the latter works for a stratisX node, whereas the former works for SBFN:

```
                stratisXRpc.SendToAddress(aliceAddress, Money.Coins(1.0m));
                stratisXRpc.SendCommand(RPCOperations.sendtoaddress, aliceAddress.ToString(), 1);
```

When trying to use the Money version against stratisX the following gets thrown:

```
Stratis.Bitcoin.Features.RPC.RPCException : value is type str, expected real
   at Stratis.Bitcoin.Features.RPC.RPCResponse.ThrowIfError() in C:\Projects\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.RPC\RPCResponse.cs:line 75
   at Stratis.Bitcoin.Features.RPC.RPCClient.SendCommandAsyncCoreAsync(RPCRequest request, Boolean throwIfRPCError) in C:\Projects\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.RPC\RPCClient.cs:line 707
   at Stratis.Bitcoin.Features.RPC.RPCClient.SendCommandAsync(RPCRequest request, Boolean throwIfRPCError) in C:\Projects\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.RPC\RPCClient.cs:line 613
   at Stratis.Bitcoin.Features.RPC.RPCClient.SendToAddressAsync(BitcoinAddress address, Money amount, String commentTx, String commentDest) in C:\Projects\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.RPC\RPCClient.cs:line 1340
   at Stratis.Bitcoin.Features.RPC.RPCClient.SendToAddress(BitcoinAddress address, Money amount, String commentTx, String commentDest) in C:\Projects\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.RPC\RPCClient.cs:line 1316
```

**Comment by dangershony** [comment]
This is probably a  none issue.
