### ISSUE TITLE
[RPC] Support RPC batching

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#2619]
Bitcoin core supports sending batch of requests, and receiving batch of responses. Currently Stratis RPC server throws internal error if it receives a request like this.

Related to PR https://github.com/MetacoSA/NBitcoin/pull/413

**Comment by mikedennis** [comment]
This test will reproduce the error:
```
 [Fact]
        public async void TestRpcBatch()
        {
            var rpcBatch = this.rpcTestFixture.RpcClient.PrepareBatch();
            Task command = rpcBatch.SendCommandAsync("getpeerinfo");
            await rpcBatch.SendBatchAsync();
        }
```
You can see this in the logging:
```
Stratis.Bitcoin.Features.RPC.RPCMiddleware:Error: Internal error while calling RPC Method

Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Stratis.Bitcoin.Features.RPC.RPCRouteHandler.RouteAsync(RouteContext context) in C:\source\stratis-fork\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.RPC\RPCRouteHandler.cs:line 47
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Stratis.Bitcoin.Features.RPC.RPCMiddleware.InvokeAsync(HttpContext httpContext) in C:\source\stratis-fork\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.RPC\RPCMiddleware.cs:line 45
```

**Comment by mikedennis** [comment]
Did some investigation into this. Might be a bit tricky. 

We can definitely identify whether it's a batch request in ``RPCRouteHandler`` using some JSon logic handling - question is then what to do next. Possibly redirect to a controller that handles the batch request. Or could put logic directly in ```RPCRouteHandler``` to iterate over each of the requests?

I'm thinking perhaps one approach for actually executing the batch is instantiating an ```RPCClient``` and then iterating through the batch and aggregating the responses. Along the lines of what is done in ```RPCController.CallByName()``` but in a batch type mode.

Thoughts? Maybe there is a better way? @zeptin @dangershony @bokobza

**Comment by maciejzaleski** [comment]
Closed
