### ISSUE TITLE
Peers disconnected due to network issues will not reconnect

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2665]
This error was not intentional, it has occurred during normal execution. I suspect that there could be a network issue between two nodes which caused exception to be thrown and peer to get disconnected.

I would expect the connection to be reopened after period of time.

**Node folder with logs**: https://stratisplatform-my.sharepoint.com/:u:/p/maciej_zaleski/ER9M1-0qK-RGoE4BcIbZSZYB7T6i34eiG6G-PKBp0W74CQ?e=5WmqDx

```[2018-11-03 03:14:17.8203 81] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection+<ReadBytesAsync>d__35.MoveNext (-)$exception:System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadBytesAsync(Byte[] buffer, Int32 offset, Int32 bytesToRead, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 404
[2018-11-03 03:14:17.8203 81] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection+<ReadMagicAsync>d__34.MoveNext (-)$exception:System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadBytesAsync(Byte[] buffer, Int32 offset, Int32 bytesToRead, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 404
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadMagicAsync(Byte[] magic, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 374
[2018-11-03 03:14:17.8203 81] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection+<ReadMessageAsync>d__33.MoveNext (-)$exception:System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadBytesAsync(Byte[] buffer, Int32 offset, Int32 bytesToRead, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 404
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadMagicAsync(Byte[] magic, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 374
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadMessageAsync(ProtocolVersion protocolVersion, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 325
[2018-11-03 03:14:17.8203 81] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection+<ReadAndParseMessageAsync>d__36.MoveNext (-)$exception:System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadBytesAsync(Byte[] buffer, Int32 offset, Int32 bytesToRead, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 404
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadMagicAsync(Byte[] magic, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 374
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadMessageAsync(ProtocolVersion protocolVersion, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 325
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadAndParseMessageAsync(ProtocolVersion protocolVersion, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 433
[2018-11-03 03:14:17.8203 81] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection+<ReceiveMessagesAsync>d__29.MoveNext [7-[::ffff:192.168.98.131]:16178] Exception occurred: 'System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadBytesAsync(Byte[] buffer, Int32 offset, Int32 bytesToRead, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 404
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadMagicAsync(Byte[] magic, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 374
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadMessageAsync(ProtocolVersion protocolVersion, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 325
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadAndParseMessageAsync(ProtocolVersion protocolVersion, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 433
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReceiveMessagesAsync() in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 132'
[2018-11-03 03:14:17.8203 81] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeer.Disconnect (reason:'Unexpected exception while waiting for a message',exception:System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadBytesAsync(Byte[] buffer, Int32 offset, Int32 bytesToRead, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 404
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadMagicAsync(Byte[] magic, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 374
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadMessageAsync(ProtocolVersion protocolVersion, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 325
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadAndParseMessageAsync(ProtocolVersion protocolVersion, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 433
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReceiveMessagesAsync() in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 132)
[2018-11-03 03:14:17.8203 81] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeer.Disconnect [7-[::ffff:192.168.98.131]:16178] (-)[DISCONNECTED]```

**Comment by fassadlr** [comment]
@maciejzaleski those exceptions are pretty standard when a peer disconnects from another. Unless the peer got banned OR the selection algorhythm in PeerSelector filters the peer I cant see a reason why it wont connect again.

Can you see in the peers.json file for this peer if it has been banned? Maybe post its json content here.

**Comment by zeptin** [comment]
This seems to be normal behaviour, the peer discovery on node DA is unable to find anything to connect to because it has banned DB for 24 hours:

```
[2018-11-03 03:14:17.8015 149] TRACE: Stratis.Bitcoin.Connection.PeerBanning.BanAndDisconnectPeer (endpoint:[::ffff:192.168.98.131]:16178,reason:'Peer violates max reorg rule.')
[2018-11-03 03:14:17.8015 149] TRACE: Stratis.Bitcoin.Connection.PeerBanning.BanAndDisconnectPeer (endpoint:[::ffff:192.168.98.131]:16178,banTimeSeconds:86400,reason:'Peer violates max reorg rule.')
```
