### ISSUE TITLE
Nodes are banned as a result of failed reorg

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2667]
**Sequence of events**
- [00:53:27] Last common consensus block 2482
- [03:06:39] NodeAB changes peer NodeDB height from 2866 to 1241
- [03:06:31] At the same time NodeDB is at height (Header:2981/Consensus:2875/Blockstore:2874) and stakes block 2875
- [03:38:13] Last common header height 3100
- [03:38:21] Node DB banned node AB

**Comment by zeptin** [comment]
This was impressively difficult to find the root cause for. But eventually:

```
[2018-11-03 00:54:26.4002 111] TRACE: Stratis.Bitcoin.Consensus.Validators.PartialValidator.OnEnqueueAsync (item:ChainedHeader=2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated,Block=NBitcoin.PosBlock,)
[2018-11-03 00:54:26.4002 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusRuleEngine.PartialValidationAsync (header:2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated,)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusRuleEngine.ExecuteRulesAsync (asyncRules.Count:11,)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.PosTimeMaskRule.RunAsync Height of block is 2483, block timestamp is 1541206400, previous block timestamp is 1541206384, block version is 0x20000000.
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusRuleEngine+<ExecuteRulesAsync>d__42.MoveNext (-)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusError.op_Inequality (a:<NULL>,b:<NULL>)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusError.op_Equality (a:<NULL>,b:<NULL>)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusError.op_Equality (-):True
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusError.op_Inequality (-):False
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusRuleEngine+<PartialValidationAsync>d__41.MoveNext (-)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager.OnPartialValidationCompletedCallbackAsync ()
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusError.op_Equality (a:<NULL>,b:<NULL>)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusError.op_Equality (-):True
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager.OnPartialValidationSucceededAsync (chainedHeader:2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.PerformanceCounters.ConsensusManager.ConsensusManagerPerformanceCounter.MeasureTotalConnectionTime ()
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.PerformanceCounters.ConsensusManager.ConsensusManagerPerformanceCounter.MeasureTotalConnectionTime (-)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.PartialValidationSucceeded (chainedHeader:2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.GetConsensusTip ()
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.GetConsensusTip (-):2482-66f6cde883ea696bad7de45b8839fa90dfcb374a36c783723a26338b68ef371c-FullyValidated
[2018-11-03 00:54:26.4714 111] DEBUG: Stratis.Bitcoin.Consensus.ChainedHeaderTree.PartialValidationSucceeded Partially validated chained header '2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-PartiallyValidated' has more work than the current consensus tip.
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.ClaimPeerTip (networkPeerId:-1,tipHash:a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.ClaimPeerTip (-)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.PartialValidationSucceeded (-).Count:0, fullValidationRequired:True
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager+<OnPartialValidationSucceededAsync>d__47.MoveNext Full validation is required.
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager.FullyValidateLockedAsync (newTip:2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-PartiallyValidated,blockMined:False)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager.TryGetBlocksToConnectAsync (proposedNewTip:2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-PartiallyValidated,heightOfFirstBlock:2483)
[2018-11-03 00:54:26.4714 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager.GetBlockDataAsync (blockHash:a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae)
[2018-11-03 00:54:26.5004 111] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.GetChainedHeaderBlock (blockHash:a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae)
[2018-11-03 00:54:26.5004 111] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.GetChainedHeaderBlock (-):2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated
[2018-11-03 00:54:26.5004 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager+<GetBlockDataAsync>d__61.MoveNext Block pair '2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated' was found in memory.
[2018-11-03 00:54:26.5004 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager+<GetBlockDataAsync>d__61.MoveNext (-)[FOUND_IN_CHT]:'2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated'
[2018-11-03 00:54:26.5004 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager+<GetBlockDataAsync>d__61.MoveNext (-):2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated
[2018-11-03 00:54:26.5004 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager+<TryGetBlocksToConnectAsync>d__55.MoveNext (-).Count:1
[2018-11-03 00:54:26.5004 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager.ConnectChainAsync (blocksToConnect.Count:1,blockMined:False)
[2018-11-03 00:54:26.5004 111] TRACE: Stratis.Bitcoin.Consensus.PerformanceCounters.ConsensusManager.ConsensusManagerPerformanceCounter.MeasureBlockConnectionFV ()
[2018-11-03 00:54:26.5004 111] TRACE: Stratis.Bitcoin.Consensus.PerformanceCounters.ConsensusManager.ConsensusManagerPerformanceCounter.MeasureBlockConnectionFV (-)
[2018-11-03 00:54:26.5004 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager.ConnectBlockAsync (blockToConnect:2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated)
[2018-11-03 00:54:26.5333 111] ERROR: Stratis.Bitcoin.Consensus.ConsensusManager+<ConnectBlockAsync>d__54.MoveNext Block '2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated' must be partially or fully validated but it is HeaderValidated.
[2018-11-03 00:54:26.5333 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager+<ConnectBlockAsync>d__54.MoveNext (-)[BLOCK_INVALID_STATE]
[2018-11-03 00:54:26.5333 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager+<ConnectBlockAsync>d__54.MoveNext (-)$exception:Stratis.Bitcoin.Consensus.ConsensusException: Block must be partially or fully validated.
   at Stratis.Bitcoin.Consensus.ConsensusManager.ConnectBlockAsync(ChainedHeaderBlock blockToConnect) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 782
```

I draw your attention in particular to the following, which I believe to be the cause:

```
[2018-11-03 00:54:26.5004 111] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.GetChainedHeaderBlock (-):2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated
[2018-11-03 00:54:26.5004 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager+<GetBlockDataAsync>d__61.MoveNext Block pair '2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated' was found in memory.
```

Which then puts everything into an inconsistent state, causing the exception to be thrown:

```
[2018-11-03 00:54:26.5333 111] ERROR: Stratis.Bitcoin.Consensus.ConsensusManager+<ConnectBlockAsync>d__54.MoveNext Block '2483-a58b9ce68b89329c73fcb4ac395aa4d533d6a64dc434c2b4dc0cad57f66ce2ae-HeaderValidated' must be partially or fully validated but it is HeaderValidated.
[2018-11-03 00:54:26.5333 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager+<ConnectBlockAsync>d__54.MoveNext (-)[BLOCK_INVALID_STATE]
[2018-11-03 00:54:26.5333 111] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager+<ConnectBlockAsync>d__54.MoveNext (-)$exception:Stratis.Bitcoin.Consensus.ConsensusException: Block must be partially or fully validated.
   at Stratis.Bitcoin.Consensus.ConsensusManager.ConnectBlockAsync(ChainedHeaderBlock blockToConnect) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 782
```

How this actually results in the symptoms Maciej reports is a complex and thrilling tale, but to simplify it, DB rejects the chains that AB has been reorging back and forth between, and starts staking its own chain until eventually it surpasses the max reorg depth and bans AB.

**Comment by zeptin** [comment]
This then appears to disrupt the chain of validation so that partial validation never gets done for subsequent incoming blocks from AB's chain (this is because `chainedHeader.Previous.BlockValidationState` evaluates to `HeaderValidated` only).

Therefore full validation never gets done either, so only DB's own staked blocks can advance its tip.

```
[2018-11-03 00:55:27.0326 45] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager.BlockDownloaded Calling 1 callbacks for block '2490-792c602d5c5b0920fab81d4c95962435b5c73465ffe84f3d1944953ff9961fb5-HeaderValidated'.
[2018-11-03 00:55:27.0326 45] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager.ProcessDownloadedBlock (chainedHeaderBlock:2490-792c602d5c5b0920fab81d4c95962435b5c73465ffe84f3d1944953ff9961fb5-HeaderValidated)
[2018-11-03 00:55:27.0326 45] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.BlockDataDownloaded (chainedHeader:2490-792c602d5c5b0920fab81d4c95962435b5c73465ffe84f3d1944953ff9961fb5-HeaderValidated,)
[2018-11-03 00:55:27.0326 45] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.BlockDataDownloaded Size of unconsumed block data is increased by 744, new value is -537071.
[2018-11-03 00:55:27.0326 45] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.BlockDataDownloaded [BLOCK_DOWNLOAD_PREVIOUS_STATE]Previous:2489-98645ef91eeea58a6c8c18e0bbd70ef4987c38af32b9dbcfcea0f22b5b0c9e14-HeaderValidated:HeaderValidated
[2018-11-03 00:55:27.0326 45] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.BlockDataDownloaded (-):False
[2018-11-03 00:55:27.0326 45] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager.ProcessDownloadedBlock Partial validation is NOT required.
[2018-11-03 00:55:27.0326 45] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager.ProcessDownloadedBlock (-)
[2018-11-03 00:55:27.0326 45] TRACE: Stratis.Bitcoin.Consensus.ConsensusManager.BlockDownloaded (-)
```

**Comment by fassadlr** [comment]
@zeptin your investigation is spot on! @dangershony and I also got to this point and that is why we put extra logging on ChainedHeader to also include the BlockValidationState in the logs, So basically from your logs it now shows that we incorrectly pull a HeaderValidated block from the cache which is not correct as THAT block was already previously full validated.

If we fix this, we will fix this bug.

**Comment by bokobza** [comment]
Nice work @zeptin !

**Comment by maciejzaleski** [comment]
We have not seen this problem reoccur
