### ISSUE TITLE
SBFN PH: Two PH SBFN nodes fail to sync from each other

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2787]
**Setup**
 - Mined 1241 blocks on StratisX using POW
 - Synced blocks NodeJFX (StratisX) -> NodeJE (SBFN) -> NodeJDX (StratisX) -> NodeAD (SBFN)
 - NodeJA (SBFN) fails to connect to NodeAD (SBFN) with below exception

Full logs: [NodeJA-Logs.zip](https://github.com/stratisproject/StratisBitcoinFullNode/files/2604435/NodeJA-Logs.zip)

**Stack Trace from Node**
```[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Protocol.Message.ReadNext (network:StratisMain,version:PROTOCOL_VERSION,)
[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Protocol.Message.SkipMagicScope (value:True)
[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Protocol.Message.SkipMagicScope (-)
[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Protocol.Message.VerifyChecksum (checksum:00000000000000000000000000000000000000000000000000000000eea48aa7,payload.Count:20541,length:20541)
[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Protocol.Message.VerifyChecksum (-):True
[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Protocol.Payloads.PayloadProvider.GetCommandType (commandName:'provhdr')
[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Protocol.Payloads.PayloadProvider.GetCommandType (-):Stratis.Bitcoin.P2P.Protocol.Payloads.ProvenHeadersPayload
[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Protocol.Payloads.ProvenHeadersPayload.ReadWriteCore ()
[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Protocol.Payloads.ProvenHeadersPayload.ReadWriteCore (-)$exception:System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Array size not big
   at NBitcoin.Protocol.VarString.ReadWrite(BitcoinStream stream) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\Protocol\VarString.cs:line 44
   at NBitcoin.BitcoinStream.ReadWrite(Script data) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 124
   at NBitcoin.BitcoinStream.ReadWrite(Script& script) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 134
   at NBitcoin.TxIn.ReadWrite(BitcoinStream stream) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\Transaction.cs:line 261
   at NBitcoin.BitcoinStream.ReadWrite[T](T& data) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 210
   at NBitcoin.BitcoinStream.ReadWriteArray[T](T[]& data) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.Partial.cs:line 28
   at NBitcoin.BitcoinStream.ReadWriteList[TList,TItem](TList& data) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 238
   at NBitcoin.BitcoinStream.ReadWrite[TList,TItem](TList& list) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 224
   at NBitcoin.Transaction.ReadWrite(BitcoinStream stream) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\Transaction.cs:line 1237
   at NBitcoin.BitcoinStream.ReadWrite[T](T& data) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 210
   at NBitcoin.ProvenBlockHeader.ReadWrite(BitcoinStream stream) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\ProvenBlockHeader.cs:line 122
   at NBitcoin.BitcoinStream.ReadWrite[T](T& data) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 210
   at NBitcoin.BitcoinStream.ReadWriteArray[T](T[]& data) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.Partial.cs:line 28
   at NBitcoin.BitcoinStream.ReadWriteList[TList,TItem](TList& data) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 238
   at NBitcoin.BitcoinStream.ReadWrite[T](List`1& list) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 217
   at Stratis.Bitcoin.P2P.Protocol.Payloads.ProvenHeadersPayload.ReadWriteCore(BitcoinStream stream) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\Payloads\ProvenHeadersPayload.cs:line 36
[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Protocol.Message.ReadNext (-)$exception:System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Array size not big
   at NBitcoin.BitcoinStream.ReadWrite(Type type, Object& obj) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 168
   at Stratis.Bitcoin.P2P.Protocol.Message.ReadWrite(BitcoinStream stream) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\Message.cs:line 145
   at Stratis.Bitcoin.P2P.Protocol.Message.ReadNext(Stream stream, Network network, ProtocolVersion version, CancellationToken cancellationToken, PayloadProvider payloadProvider, PerformanceCounter& counter) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\Message.cs:line 198
[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection+<ReadAndParseMessageAsync>d__36.MoveNext (-)$exception:System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Array size not big
   at NBitcoin.BitcoinStream.ReadWrite(Type type, Object& obj) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 168
   at Stratis.Bitcoin.P2P.Protocol.Message.ReadWrite(BitcoinStream stream) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\Message.cs:line 145
   at Stratis.Bitcoin.P2P.Protocol.Message.ReadNext(Stream stream, Network network, ProtocolVersion version, CancellationToken cancellationToken, PayloadProvider payloadProvider, PerformanceCounter& counter) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\Message.cs:line 198
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadAndParseMessageAsync(ProtocolVersion protocolVersion, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 436
[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection+<ReceiveMessagesAsync>d__29.MoveNext [20-[::ffff:192.168.98.103]:16178] Exception occurred: 'System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Array size not big
   at NBitcoin.BitcoinStream.ReadWrite(Type type, Object& obj) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 168
   at Stratis.Bitcoin.P2P.Protocol.Message.ReadWrite(BitcoinStream stream) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\Message.cs:line 145
   at Stratis.Bitcoin.P2P.Protocol.Message.ReadNext(Stream stream, Network network, ProtocolVersion version, CancellationToken cancellationToken, PayloadProvider payloadProvider, PerformanceCounter& counter) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\Message.cs:line 198
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadAndParseMessageAsync(ProtocolVersion protocolVersion, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 436
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReceiveMessagesAsync() in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 132'
[2018-11-21 13:39:21.0981 19] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeer.Disconnect (reason:'Unexpected exception while waiting for a message',exception:System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Array size not big
   at NBitcoin.BitcoinStream.ReadWrite(Type type, Object& obj) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\BitcoinStream.cs:line 168
   at Stratis.Bitcoin.P2P.Protocol.Message.ReadWrite(BitcoinStream stream) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\Message.cs:line 145
   at Stratis.Bitcoin.P2P.Protocol.Message.ReadNext(Stream stream, Network network, ProtocolVersion version, CancellationToken cancellationToken, PayloadProvider payloadProvider, PerformanceCounter& counter) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\Message.cs:line 198
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReadAndParseMessageAsync(ProtocolVersion protocolVersion, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 436
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ReceiveMessagesAsync() in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 132)```

**Comment by zeptin** [comment]
From node AD:

```[2018-11-21 17:53:04.1779 25] FATAL: Stratis.Bitcoin.P2P.Peer.NetworkPeer+<ProcessMessageAsync>d__95.MoveNext [15-[::ffff:192.168.98.121]:44023] Exception occurred while calling message received callbacks: Stratis.Bitcoin.Consensus.ConsensusException: Proven header could not be found.
   at Stratis.Bitcoin.Features.Consensus.Behaviors.ProvenHeadersConsensusManagerBehavior.ConstructHeadersPayload(GetHeadersPayload getHeadersPayload, ChainedHeader& lastHeader) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\Behaviors\ProvenHeadersConsensusManagerBehavior.cs:line 124
   at Stratis.Bitcoin.Consensus.ConsensusManagerBehavior.ProcessGetHeadersAsync(INetworkPeer peer, GetHeadersPayload getHeadersPayload) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManagerBehavior.cs:line 185
   at Stratis.Bitcoin.Features.Consensus.Behaviors.ProvenHeadersConsensusManagerBehavior.OnMessageReceivedAsync(INetworkPeer peer, IncomingMessage message) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\Behaviors\ProvenHeadersConsensusManagerBehavior.cs:line 80
   at Stratis.Bitcoin.Utilities.AsyncExecutionEvent`2.ExecuteCallbacksAsync(TSender sender, TArg arg) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncExecutionEvent.cs:line 156
   at Stratis.Bitcoin.P2P.Peer.NetworkPeer.ProcessMessageAsync(IncomingMessage message, CancellationToken cancellation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeer.cs:line 502
```

**Comment by zeptin** [comment]
Preliminary analysis:

```
[2018-11-21 17:53:01.9812 24] TRACE: Stratis.Bitcoin.Features.BlockStore.ProvenHeadersBlockStoreSignaled.CreateAndStoreProvenHeader (blockHeight:117,chainedHeaderBlock:117-77ce8238899128b3e74b5a296492cad5498180b33ad91d8d7c73ac7eb8408af3-FullyValidated,isIBD:False)
[2018-11-21 17:53:01.9812 24] TRACE: Stratis.Bitcoin.Features.BlockStore.ProvenHeadersBlockStoreSignaled.CreateAndStoreProvenHeader Created Proven Header at height 117 with hash 77ce8238899128b3e74b5a296492cad5498180b33ad91d8d7c73ac7eb8408af3 and adding to the pending batch to be stored.

[2018-11-21 17:53:01.8977 18] TRACE: Stratis.Bitcoin.Features.Consensus.ProvenBlockHeaders.ProvenBlockHeaderRepository+<>c__DisplayClass14_0.<GetAsync>b__0 Loading ProvenBlockHeaders from block height 117 to 117 from the database.
[2018-11-21 17:53:01.9812 18] DEBUG: Stratis.Bitcoin.Features.Consensus.ProvenBlockHeaders.ProvenBlockHeaderRepository+<>c__DisplayClass14_0.<GetAsync>b__0 ProvenBlockHeader height 117 does not exist in the database.
```

Appears to be a race condition between creation of the proven header and the PH being needed by the header payload construction. Possibly connecting a header to CHT creates an expectation that we will have a proven header available even though it only gets created later when the block completes validation.
