### ISSUE TITLE
SBFN PH: Cannot generate POW blocks

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2789]
Exception returned in Swagger

**Exception**
```
{
  "errors": [
    {
      "status": 400,
      "message": "Exception of type 'Stratis.Bitcoin.Consensus.ConsensusRuleException' was thrown.",
      "description": "Stratis.Bitcoin.Consensus.ConsensusRuleException: Exception of type 'Stratis.Bitcoin.Consensus.ConsensusRuleException' was thrown.\n   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateAndValidateNewChainedHeader(BlockHeader currentBlockHeader, ChainedHeader previousChainedHeader) in C:\\Code\\InternalTestnet_Data\\Sources\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin\\Consensus\\ChainedHeaderTree.cs:line 1053\n   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateNewHeaders(List`1 headers) in C:\\Code\\InternalTestnet_Data\\Sources\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin\\Consensus\\ChainedHeaderTree.cs:line 982\n   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateChainedHeaderOfMinedBlock(Block block) in C:\\Code\\InternalTestnet_Data\\Sources\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin\\Consensus\\ChainedHeaderTree.cs:line 940\n   at Stratis.Bitcoin.Consensus.ConsensusManager.BlockMinedAsync(Block block) in C:\\Code\\InternalTestnet_Data\\Sources\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin\\Consensus\\ConsensusManager.cs:line 252\n   at Stratis.Bitcoin.Features.Miner.PowMining.ValidateAndConnectBlock(MineBlockContext context) in C:\\Code\\InternalTestnet_Data\\Sources\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin.Features.Miner\\PowMining.cs:line 273\n   at Stratis.Bitcoin.Features.Miner.PowMining.GenerateBlocks(ReserveScript reserveScript, UInt64 amountOfBlocksToMine, UInt64 maxTries) in C:\\Code\\InternalTestnet_Data\\Sources\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin.Features.Miner\\PowMining.cs:line 182\n   at Stratis.Bitcoin.Features.Miner.Controllers.MiningController.Generate(MiningRequest request) in C:\\Code\\InternalTestnet_Data\\Sources\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin.Features.Miner\\Controllers\\MiningController.cs:line 87"
    }
  ]
}
```

**Stack Trace**
```
[2018-11-21 13:59:53.0985 19] ERROR: Stratis.Bitcoin.Features.Miner.Controllers.MiningController.Generate Exception occurred: Stratis.Bitcoin.Consensus.ConsensusRuleException: Exception of type 'Stratis.Bitcoin.Consensus.ConsensusRuleException' was thrown.
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateAndValidateNewChainedHeader(BlockHeader currentBlockHeader, ChainedHeader previousChainedHeader) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 1053
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateNewHeaders(List`1 headers) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 982
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateChainedHeaderOfMinedBlock(Block block) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 940
   at Stratis.Bitcoin.Consensus.ConsensusManager.BlockMinedAsync(Block block) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 252
   at Stratis.Bitcoin.Features.Miner.PowMining.ValidateAndConnectBlock(MineBlockContext context) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PowMining.cs:line 273
   at Stratis.Bitcoin.Features.Miner.PowMining.GenerateBlocks(ReserveScript reserveScript, UInt64 amountOfBlocksToMine, UInt64 maxTries) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PowMining.cs:line 182
   at Stratis.Bitcoin.Features.Miner.Controllers.MiningController.Generate(MiningRequest request) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\Controllers\MiningController.cs:line 87
[2018-11-21 14:00:36.5824 17] TRACE: Stratis.Bitcoin.Features.Miner.Controllers.MiningController.Generate (BlockCount:1)
[2018-11-21 14:00:36.5877 17] DEBUG: Stratis.Bitcoin.Features.Miner.BlockDefinition.OnBuild Serialized size is 185 bytes, block weight is 185, number of txs is 0, tx fees are 0.00000000, number of sigops is 400.
[2018-11-21 14:00:36.5877 17] ERROR: Stratis.Bitcoin.Features.Miner.Controllers.MiningController.Generate Exception occurred: Stratis.Bitcoin.Consensus.ConsensusRuleException: Exception of type 'Stratis.Bitcoin.Consensus.ConsensusRuleException' was thrown.
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateAndValidateNewChainedHeader(BlockHeader currentBlockHeader, ChainedHeader previousChainedHeader) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 1053
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateNewHeaders(List`1 headers) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 982
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateChainedHeaderOfMinedBlock(Block block) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 940
   at Stratis.Bitcoin.Consensus.ConsensusManager.BlockMinedAsync(Block block) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 252
   at Stratis.Bitcoin.Features.Miner.PowMining.ValidateAndConnectBlock(MineBlockContext context) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PowMining.cs:line 273
   at Stratis.Bitcoin.Features.Miner.PowMining.GenerateBlocks(ReserveScript reserveScript, UInt64 amountOfBlocksToMine, UInt64 maxTries) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PowMining.cs:line 182
   at Stratis.Bitcoin.Features.Miner.Controllers.MiningController.Generate(MiningRequest request) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\Controllers\MiningController.cs:line 87
[2018-11-21 14:14:10.0787 19] TRACE: Stratis.Bitcoin.Features.Miner.Controllers.MiningController.Generate (BlockCount:1)
[2018-11-21 14:14:10.0787 19] DEBUG: Stratis.Bitcoin.Features.Miner.BlockDefinition.OnBuild Serialized size is 185 bytes, block weight is 185, number of txs is 0, tx fees are 0.00000000, number of sigops is 400.
[2018-11-21 14:14:10.0878 19] ERROR: Stratis.Bitcoin.Features.Miner.Controllers.MiningController.Generate Exception occurred: Stratis.Bitcoin.Consensus.ConsensusRuleException: Exception of type 'Stratis.Bitcoin.Consensus.ConsensusRuleException' was thrown.
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateAndValidateNewChainedHeader(BlockHeader currentBlockHeader, ChainedHeader previousChainedHeader) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 1053
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateNewHeaders(List`1 headers) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 982
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateChainedHeaderOfMinedBlock(Block block) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 940
   at Stratis.Bitcoin.Consensus.ConsensusManager.BlockMinedAsync(Block block) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 252
   at Stratis.Bitcoin.Features.Miner.PowMining.ValidateAndConnectBlock(MineBlockContext context) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PowMining.cs:line 273
   at Stratis.Bitcoin.Features.Miner.PowMining.GenerateBlocks(ReserveScript reserveScript, UInt64 amountOfBlocksToMine, UInt64 maxTries) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\PowMining.cs:line 182
   at Stratis.Bitcoin.Features.Miner.Controllers.MiningController.Generate(MiningRequest request) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\Controllers\MiningController.cs:line 87```

**Comment by zeptin** [comment]
See related issue #2792, although that issue occurs specifically at genesis and is due to a different reason.

**Comment by ArcSin2000X** [comment]
retested can confirm this is fixed now
