### ISSUE TITLE
Staking with same wallets on 2 nodes causes them to stop advancing

### ISSUE THREAD

**Issue by ArcSin2000X** [stratisproject/StratisBitcoinFullNode#2867]
**Scenario description:**
Nodes `NodeFB` and `NodeFD` have been configured with the same wallet each with 5444444 Strat. Nodes have been synced to block 3500 with staking set to off on both nodes. After enabling staking on both nodes stopped advancing. `FB` stopped on block 3500, where `FD` stopped on block 3501 I have found following error messages in the logs for

**NodeFD:**
```properties
[2018-11-28 23:38:08.5091 8] TRACE: Stratis.Bitcoin.Consensus.ConsensusError.Throw (-)$exception:Stratis.Bitcoin.Consensus.ConsensusErrorException: proof-of-stake hash did not meet target protocol
   at Stratis.Bitcoin.Consensus.ConsensusError.Throw() in C:\Dev\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusErrorException.cs:line 45
```

**NodeFB:**
```properties
[2018-11-28 23:38:04.2599 40] TRACE: Stratis.Bitcoin.Consensus.ChainedHeaderTree.ConnectNewHeaders (-)$exception:Stratis.Bitcoin.Consensus.ConnectHeaderException: Exception of type 'Stratis.Bitcoin.Consensus.ConnectHeaderException' was thrown.
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.ConnectNewHeaders(Int32 networkPeerId, List`1 headers) in C:\Dev\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 630
```

Birds eye view of the network, see the fork on 2 nodes `FB` `FD`
![image](https://user-images.githubusercontent.com/37782512/49233756-95746780-f3ee-11e8-8f2e-3be5e73c1a5b.png)

Network topology:
https://stratisplatform-my.sharepoint.com/:u:/p/lukasz_krol/EVJ8reSfdBZFj1etmAb2Q7MBl3VAfjOBCXRzZL8dPBtcrw?e=2r9uqg

28/11/2018 at 23:38 is when nodes stopped advancing their consensus tips. 

Node data folders for  `FB` `FD` can be found here:
https://stratisplatform-my.sharepoint.com/:u:/p/lukasz_krol/EbF7msw8krJOt3YYkkRxhaYBmPmsXXgTdrZAfom6kZwI-w?e=AxmXrX

**Comment by ArcSin2000X** [comment]
Test was run against code level below:

```properties
Revision: c89d8e267dc45801d51b319599ac1e2dba74a11e
Author: Francois de la Rouviere <fassadlr@gmail.com>
Date: 27/11/2018 17:31:18
Message:
[BlockStore] Dequeue all items from the async queue on dispose (#2837)

* Add items from async queue to batch before saving



* Fixes as per review



* Changes as per review
----
Modified: src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs
Modified: src/Stratis.Bitcoin/Utilities/AsyncQueue.cs
```

**Comment by fassadlr** [comment]
@ArcSin2000X Also, this one, can we close?

**Comment by maciejzaleski** [comment]
Issue has been resolved
