### ISSUE TITLE
Inconsistent connection state reported by nodes

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2918]
Inconsistent connection state:
- `NodeCA` (100.64.2.1) "thinks" it is connected to `NodeAA`
- `NodeAA` (100.123.254.1) is not showing connection to `NodeCA`

**Logs**
[NodeAA-CA Logs.zip](https://github.com/stratisproject/StratisBitcoinFullNode/files/2653414/NodeAA-CA.Logs.zip)

**Node connections**
![image 1](https://user-images.githubusercontent.com/6422181/49590218-35883e80-f963-11e8-90f5-7d60403a3381.png)

**Code version**
```
9535e61e (06 Dec @ 15:32); Patches: Kevin 
   
*** Build date: 06/12/2018 12:34:06.68 
*** Specific commit:  
   
*** Recent commits 
*    9535e61e - (HEAD -> master, origin/master, origin/HEAD) syncing speedup (#2901) (Thu, 6 Dec 2018 15:32:25 +0300) <noescape0>
*    63b750a3 - Fix DoS vector (#2904) (Thu, 6 Dec 2018 12:53:36 +0300) <noescape0>
*    3719dab9 - Set the transaction fee to the network defined minimum fee (#2907) (Thu, 6 Dec 2018 08:05:27 +0000) <Jeremy Bokobza>
*    e2af0c02 - (origin/sc/v0.13.0-beta) Add version to network folder name (#2915) (Thu, 6 Dec 2018 15:11:18 +1100) <Rowan de Haas>
*    f4a8ec92 - Increment magic and nonce (#2914) (Thu, 6 Dec 2018 15:05:31 +1100) <Rowan de Haas>
*    0c313825 - Increment SC version (#2911) (Thu, 6 Dec 2018 12:20:01 +1100) <Rowan de Haas>
*    0f93ca37 - RuntimeObserver -> Stratis.SmartContracts.RuntimeObserver (#2912) (Thu, 6 Dec 2018 12:13:24 +1100) <Jordan Andrews>
*    5c8c08f9 - Powershell NuGet fix + version updates (#2900) (Thu, 6 Dec 2018 10:41:10 +1100) <Jordan Andrews>
*    a6a8d2b7 - Added custom path for KeyTool (#2902) (Wed, 5 Dec 2018 17:05:43 +0000) <Jeremy Bokobza>
*    528337cc - Missing inputs error was not reporting correctly the error (#2906) (Wed, 5 Dec 2018 16:53:23 +0000) <Dan Gershony>  
****************** 
 
*** Repackaged: 06/12/2018 12:51:28.90
```

**Comment by fassadlr** [comment]
I've observed this issue now as well.

I had a C# node running, connected to a my GW which was connected to X.

I shutdown the GW node but my C# is still reporting a connection:

```=======Mempool=======
MempoolSize: 7    DynamicSize: 830 kb OrphanSize: 0   

[2018-12-09 10:29:00.3299 39] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0 ======Node stats====== 12/09/2018 10:29:00
Headers.Height:      673764   Headers.Hash:     bfac1009cd99d2dc76aab13b4b21787893896e43865e7e5a4e8b6d89915b148a
Consensus.Height:    673764   Consensus.Hash:   bfac1009cd99d2dc76aab13b4b21787893896e43865e7e5a4e8b6d89915b148a
BlockStore.Height:   673764   BlockStore.Hash:  bfac1009cd99d2dc76aab13b4b21787893896e43865e7e5a4e8b6d89915b148a
Wallet.Height:       No Wallet

======Connection====== agent fassa-StratisNode:1.2.6 (70012) [in:0 out:15]
...
Peer:[::ffff:191.235.85.131]:26178,      connected:outbound,       (r/s):673600/673764         agent:/Stratis:2.0.0.5/
...
```

GW node:

```
[2018-12-09 10:29:45.2110 12] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0 ======Node stats====== 12/09/2018 10:29:45
Headers.Height:      673766   Headers.Hash:     59f2ccb962ec37d81e29c8e0052085c9b7ba3661f214967ce734101cef53376e
Consensus.Height:    673766   Consensus.Hash:   59f2ccb962ec37d81e29c8e0052085c9b7ba3661f214967ce734101cef53376e
BlockStore.Height:   673766   BlockStore.Hash:  59f2ccb962ec37d81e29c8e0052085c9b7ba3661f214967ce734101cef53376e
Wallet.Height:       No Wallet

======Connection====== agent fassadlr-StratisNode:1.2.6 (70012) [in:0 out:1]
Peer:[::ffff:127.0.0.1]:26178,           connected:outbound,       (r/s):673766/673766         agent:/Stratis:2.0.0.5/
```

**Comment by fassadlr** [comment]
I will investigate this one a bit.

**Comment by MithrilMan** [comment]
Did you have anything to report @fassadlr about this?

**Comment by MithrilMan** [comment]
watching at NodeAA.tcpdump I see 3 connections from 100.64.2.1 to 100.123.254.1:
- at 14:58:35 (from port 40971)
- at 14:58:45 (from port 40485)
- at 15:18:37 (from port 43239)

I see 2 FIN (connection end):
- at 14:58:50 (from port 40485)
- at 15:18:36 (from port 40971)

This mean that:
first connection starts at 14:58:35 and end at 15:18:36
-duration ~ 20 minutes

second connection starts at 14:58:45 and end at 15:18:50
-duration 5 seconds

third connection starts at 15:18:36 and doesn't close (may be because of end of tracing)
So it seems actually these peers are connected. Invastigating other logs.

**Comment by MithrilMan** [comment]
in NodeCA log (100.64.2.1) I see it went offline
>[2018-12-06 14:18:36.5264 39] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior+<OnStateChangedAsync>d__15.MoveNext Peer '[::ffff:100.123.254.1]:16178' offline, reason: 'Pong timeout for 15811463201652718343'.
and get reconnected later

**Comment by MithrilMan** [comment]
Object reference not set to an instance of an object. ??

```
[2018-12-06 13:58:35.1674 8] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.ConnectAsync (endPoint:[::ffff:100.123.254.1]:16178,)
[2018-12-06 13:58:35.3101 7] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeerConnectionParameters.CreateVersion (-)$exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at NBitcoin.Protocol.NetworkAddress.set_Endpoint(IPEndPoint value) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\Protocol\NetworkAddress.cs:line 37
   at Stratis.Bitcoin.P2P.Protocol.Payloads.VersionPayload.set_AddressFrom(IPEndPoint value) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\Payloads\VersionPayload.cs:line 126
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnectionParameters.CreateVersion(IPEndPoint externalAddressEndPoint, IPEndPoint peerAddress, Network network, DateTimeOffset timeStamp) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnectionParameters.cs:line 95
[2018-12-06 13:58:35.3101 7] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeerFactory+<CreateConnectedNetworkPeerAsync>d__13.MoveNext (-)$exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at NBitcoin.Protocol.NetworkAddress.set_Endpoint(IPEndPoint value) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\NBitcoin\Protocol\NetworkAddress.cs:line 37
   at Stratis.Bitcoin.P2P.Protocol.Payloads.VersionPayload.set_AddressFrom(IPEndPoint value) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\Payloads\VersionPayload.cs:line 126
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnectionParameters.CreateVersion(IPEndPoint externalAddressEndPoint, IPEndPoint peerAddress, Network network, DateTimeOffset timeStamp) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnectionParameters.cs:line 95
   at Stratis.Bitcoin.P2P.Peer.NetworkPeer..ctor(Boolean inbound, IPEndPoint peerEndPoint, Network network, NetworkPeerConnectionParameters parameters, IDateTimeProvider dateTimeProvider, ILoggerFactory loggerFactory, ISelfEndpointTracker selfEndpointTracker, Action`1 onDisconnected, Action`2 onSendingMessage) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeer.cs:line 292
   at Stratis.Bitcoin.P2P.Peer.NetworkPeer..ctor(IPEndPoint peerEndPoint, Network network, NetworkPeerConnectionParameters parameters, INetworkPeerFactory networkPeerFactory, IDateTimeProvider dateTimeProvider, ILoggerFactory loggerFactory, ISelfEndpointTracker selfEndpointTracker, Action`1 onDisconnected, Action`2 onSendingMessage) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeer.cs:line 320
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerFactory.CreateConnectedNetworkPeerAsync(IPEndPoint peerEndPoint, NetworkPeerConnectionParameters parameters, NetworkPeerDisposer networkPeerDisposer) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerFactory.cs:line 196
[2018-12-06 13:58:35.3101 7] TRACE: Stratis.Bitcoin.P2P.PeerDiscovery+<<DiscoverPeersAsync>b__15_2>d.MoveNext Discovery from '[::ffff:100.123.254.1]:16178' finished
```

**Comment by MithrilMan** [comment]
>[2018-12-06 13:58:45.3088 15] TRACE: Stratis.Bitcoin.P2P.PeerDiscovery+<<DiscoverPeersAsync>b__15_2>d.MoveNext Attempting to discover from : '[::ffff:100.123.254.1]:16178'

this explain the connection from port 40485 was a PeerDiscovery connection, this is why got disconnected fast

**Comment by MithrilMan** [comment]
@maciejzaleski
I see that NodeCA has connection to  100.64.2.1, so same range?. Range filter was off?

beside this, NodeCA received a ping from NodeAA
>[2018-12-06 13:58:45.3354 15] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection+<ReceiveMessagesAsync>d__29.MoveNext [2-[::ffff:100.123.254.1]:16178] Received message: 'ping: PingPayload : 12184742314287925274'

but it seems it didn't replied back because after 20 minutes, NodeAA disconnected to it because of pong timeout
>[2018-12-06 14:18:45.3657 38] TRACE: Stratis.Bitcoin.P2P.Protocol.Payloads.PingPayload.ToString (-):'PingPayload : 12184742314287925274'
[2018-12-06 14:18:45.3657 38] TRACE: Stratis.Bitcoin.P2P.Protocol.Behaviors.PingPongBehavior.PingTimeout (ping:PingPayload : 12184742314287925274)
[2018-12-06 14:18:45.3657 38] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeer.Disconnect (reason:'Pong timeout for 12184742314287925274',exception:<NULL>)
[2018-12-06 14:18:45.2756 42] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeerCollection.Match (ip:::ffff:100.65.6.1,port:16178,)
[2018-12-06 14:18:45.3657 38] TRACE: Stratis.Bitcoin.P2P.Peer.NetworkPeer.Disconnect [28-[::ffff:100.64.2.1]:40485] (-)[DISCONNECTED]

**Comment by MithrilMan** [comment]
@maciejzaleski 
Understanding what happened, without having contextual thread information in logs is a pain (asyn code may mix log output) but what I can say is taht NodeCA seems to be disconnected from NodeAA because another peer with IP 100.64.6.1 was already connected and so NodeAC(100.64.2.1) is RANGE_FILTERED

this is the output of NodeAA and you can see that before NodeAC connection it has already a connected peer with same group

```
[2018-12-06 13:58:14.3954 19] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior+<OnStateChangedAsync>d__15.MoveNext Peer '[::ffff:100.65.6.1]:33763' connected (inbound), agent 'StratisNode:1.2.6 (70012)', height 0
[2018-12-06 13:58:14.9182 13] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext WalletManager.DownloadChain starting.
[2018-12-06 13:58:14.9182 19] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0 ======Node stats====== 12/06/2018 13:58:14
Headers.Height:      0        Headers.Hash:     0000066e91e46e5a264d42c89e1204963b2ee6be230b443e9159020539d972af
Consensus.Height:    0        Consensus.Hash:   0000066e91e46e5a264d42c89e1204963b2ee6be230b443e9159020539d972af
BlockStore.Height:   0        BlockStore.Hash:  0000066e91e46e5a264d42c89e1204963b2ee6be230b443e9159020539d972af
Wallet.Height:       0        Wallet.Hash:      0000066e91e46e5a264d42c89e1204963b2ee6be230b443e9159020539d972af

======Connection====== agent StratisNode:1.2.6 (70012) [in:2 out:1]
Peer:[::ffff:100.65.6.1]:33763,          connected:inbound,        (r/s):0/0                   agent:StratisNode:1.2.6 (70012)
Peer:[::ffff:100.64.6.1]:34671,          connected:inbound,        (r/s):0/0                   agent:StratisNode:1.2.6 (70012)
```

It seems to me a race condition, we need better logging (#2969) and maybe some more statistical data on connections (#2968)

**Comment by noescape00** [comment]
>without having contextual thread information in logs is a pain (asyn code may mix log output)

logs produced by nlog config in documentation folder should contain thread number in them for each line.

>I can say is taht NodeCA seems to be disconnected from NodeAA because another peer with IP 100.64.6.1 was already connected and so NodeAC(100.64.2.1) is RANGE_FILTERED

That seems like that case. Though I thought that @maciejzaleski recently updated the network so all of the peers are in the different IP groups.

**Comment by maciejzaleski** [comment]
Closed
