### ISSUE TITLE
Transaction is not included in the block

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2927]
I have been sending 5 transactions every 5-10 seconds on the InternalMainnet which stakes blocks faster than real mainnet. There were two stakers on the network NodeGE and NodeIE both of witch are SBFN implementation.

After few attempts I got a network to the state where there is one transaction in the mempool (on some of the nodes) which cannot be mined. Several blocks but the transaction is still not mined.

**Logs**: https://stratisplatform-my.sharepoint.com/:u:/p/maciej_zaleski/EVK1wGUJArVNrkA6hdy0bsoBp5wyxFEW4KX_B4_pYFvjAw?e=awCMnZ

**Network state**
![image](https://user-images.githubusercontent.com/6422181/49695499-e5dc8980-fb93-11e8-86b5-b55b02d05877.png)

**Comment by dangershony** [comment]
If the trx is resubmitted again and gets mined then the issue is propagation indeed.
It might be the trx never ended in a miners mempool because of reorgs and then it's stuck in limbo.
Trying to resubmit the trx in a miner node will confirm this is the issue.

**Comment by maciejzaleski** [comment]
The transaction is present in the mempool on NodeGE and NodeGE is one of the two miners on the network (along the NodeIE)
There are logs attached for both miners.

**Comment by dangershony** [comment]
Right thanks this is an issue for sure then, I will investigate

**Comment by dangershony** [comment]
After further investigation we discovered the reason is that miner thread was shut down after an error.
This is the logs that where observed:

```[2018-12-09 09:06:26.0256 93] ERROR: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<>c__DisplayClass38_0+<<Stake>b__0>d.MoveNext Exception: Stratis.Bitcoin.Consensus.ConsensusException: tried to overwrite transaction
   at Stratis.Bitcoin.Consensus.ConsensusManager.BlockMinedAsync(Block block) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 281
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.CheckStakeAsync(Block block, ChainedHeader chainTip) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 490
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.GenerateBlocksAsync(WalletSecret walletSecret, CancellationToken cancellationToken) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 408
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.<>c__DisplayClass38_0.<<Stake>b__0>d.MoveNext() in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 288
[2018-12-09 09:06:26.0256 93] TRACE: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<>c__DisplayClass38_0+<<Stake>b__0>d.MoveNext (-)[UNHANDLED_EXCEPTION]
```

**Comment by maciejzaleski** [comment]
Closed
