### ISSUE TITLE
If staking is attempted on a PH node before PH activation it could fail

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2942]
**Exception**
```
[2018-12-11 18:38:57.6804 27] ERROR: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<>c__DisplayClass38_0+<<Stake>b__0>d.MoveNext Exception: Stratis.Bitcoin.Consensus.ConsensusRuleException: proven-header-invalid-previous-header-stack-modifier : previous proven header's StackModifier is null
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateAndValidateNewChainedHeader(BlockHeader currentBlockHeader, ChainedHeader previousChainedHeader, Boolean& insufficientHeaderInformation) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 1065
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateNewHeaders(List`1 headers, Boolean& insufficientInfo) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 991
   at Stratis.Bitcoin.Consensus.ChainedHeaderTree.CreateChainedHeaderOfMinedBlock(Block block) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ChainedHeaderTree.cs:line 946
   at Stratis.Bitcoin.Consensus.ConsensusManager.BlockMinedAsync(Block block) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 258
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.CheckStakeAsync(Block block, ChainedHeader chainTip) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 490
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.GenerateBlocksAsync(WalletSecret walletSecret, CancellationToken cancellationToken) in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 408
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.<>c__DisplayClass38_0.<<Stake>b__0>d.MoveNext() in C:\Code\InternalTestnet_Data\Sources\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 288
[2018-12-11 18:38:57.6804 27] TRACE: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<>c__DisplayClass38_0+<<Stake>b__0>d.MoveNext (-)[UNHANDLED_EXCEPTION]
```

**Code Version**
```
4879e7e2 (11 Dec @ 13:09); Patches: AllowClientConnection_in_IBD,DecreaseDifficultyAndLastPOWBlockHeight,DecreaseCoinstakeMinConfirmation,AddPropagationFeature,Kevin 
   
*** Build date: 11/12/2018 13:48:45.75 
   
*** Recent commits 
*    4879e7e2 - (HEAD -> master, origin/master, origin/HEAD) Make all setting keys lowercase (#2938) (Tue, 11 Dec 2018 13:09:59 +0000) <Dan Gershony>
*    6ca6055c - [SC] Address json resolver (#2937) (Tue, 11 Dec 2018 21:51:14 +1100) <Jordan Andrews>
*    c827ae23 - Adding BlockStoreCacheTip property and more debug logs (#2930) (Mon, 10 Dec 2018 16:32:46 +0000) <Dan Gershony>
*    727c439b - added logs for test package method (#2934) (Mon, 10 Dec 2018 19:22:20 +0300) <noescape0>
*    1ee625a9 - Changed Default log lovel to Information (#2931) (Mon, 10 Dec 2018 11:44:01 +0000) <Jeremy Bokobza>
*    dc69a4db - Important Comment (#2932) (Mon, 10 Dec 2018 13:27:14 +1100) <Jordan Andrews>
*    c2e55d6c - [SC] Remove wallet requirement for local execution (#2923) (Sat, 8 Dec 2018 21:25:43 +1100) <Rowan de Haas>
*    b8291b4e - fixed FeeRate rounding issue  (#2924) (Fri, 7 Dec 2018 19:31:50 +0100) <MithrilMan>
*    e2371d24 - Fix P2P unit tests (#2917) (Fri, 7 Dec 2018 13:35:42 +0000) <Francois de la Rouviere>
*    40c89126 - Gateway node should be able to sync normal headers before last checkpoint (#2922) (Fri, 7 Dec 2018 13:23:12 +0300) <noescape0>  
****************** 
```

**Comment by dangershony** [comment]
Staking is not broken I just mined a block on testnet with latest master
I will need more information to be able to reproduce this bug

**Comment by maciejzaleski** [comment]
I will rerun the test in case I have used old data folder

**Comment by maciejzaleski** [comment]
Resolved
