### ISSUE TITLE
Reorg (1 single height) stopped staking

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#2990]
Received an exception during reorg that stopped the staking. Been running without any problems for days, then stopped:

```

[2018-12-16 19:38:09.0902 5] INFO: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<CreateCoinstakeAsync>d__44.MoveNext Node staking with 1230551.56552840 (39.03 % of the network weight 3153183.80370056), est. time to find new block is 00:02:43.
[2018-12-16 19:38:11.2692 5] INFO: Stratis.Bitcoin.Consensus.ConsensusManager+<RewindToForkPointAsync>d__50.MoveNext Reorg from block '54835-5583edbecdcb0be7211914fff08c47f95a72f6021b13b65734236788c8307108-FullyValidated' to '54834-c17a4cca321f5bb8680c54b7bdeb9efab8b475e7ae3d675eef925cb6a21d313f-FullyValidated'
[2018-12-16 19:38:12.3259 25] INFO: Stratis.Bitcoin.Features.Wallet.WalletSyncManager+<OnProcessBlockAsync>d__16.MoveNext Reorg detected, going back from '54835-5583edbecdcb0be7211914fff08c47f95a72f6021b13b65734236788c8307108-FullyValidated' to '54834-c17a4cca321f5bb8680c54b7bdeb9efab8b475e7ae3d675eef925cb6a21d313f-FullyValidated'.
[2018-12-16 19:38:13.3698 19] ERROR: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<>c__DisplayClass38_0+<<Stake>b__0>d.MoveNext Exception: System.Exception: Assertion failed
   at Stratis.Bitcoin.Utilities.Guard.Assert(Boolean condition) in D:\a\1\s\src\Stratis.Bitcoin\Utilities\Guard.cs:line 23
   at Stratis.Bitcoin.Features.MemoryPool.TxMempool.GetMemPoolChildren(TxMempoolEntry entry) in D:\a\1\s\src\Stratis.Bitcoin.Features.MemoryPool\TxMemPool.cs:line 449
   at Stratis.Bitcoin.Features.MemoryPool.TxMempool.CalculateDescendants(TxMempoolEntry entry, SetEntries setDescendants) in D:\a\1\s\src\Stratis.Bitcoin.Features.MemoryPool\TxMemPool.cs:line 729
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.Bitcoin.Features.Miner.BlockDefinition.UpdatePackagesForAdded(SetEntries alreadyAdded, Dictionary`2 mapModifiedTx) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\BlockDefinition.cs:line 540
   at Stratis.Bitcoin.Features.Miner.BlockDefinition.AddTransactions(Int32& nPackagesSelected, Int32& nDescendantsUpdated) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\BlockDefinition.cs:line 453
   at Stratis.Bitcoin.Features.Miner.BlockDefinition.OnBuild(ChainedHeader chainTip, Script scriptPubKey) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\BlockDefinition.cs:line 222
   at Stratis.Bitcoin.Features.Miner.PosBlockDefinition.Build(ChainedHeader chainTip, Script scriptPubKey) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\PosBlockDefinition.cs:line 60
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.GenerateBlocksAsync(WalletSecret walletSecret, CancellationToken cancellationToken) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 402
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.<>c__DisplayClass38_0.<<Stake>b__0>d.MoveNext() in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 288
[2018-12-16 19:38:13.3782 19] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake stopping.
[2018-12-16 19:38:13.3782 19] FATAL: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake threw an unhandled exception
[2018-12-16 19:38:13.3782 19] ERROR: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake threw an unhandled exception: System.Exception: Assertion failed
   at Stratis.Bitcoin.Utilities.Guard.Assert(Boolean condition) in D:\a\1\s\src\Stratis.Bitcoin\Utilities\Guard.cs:line 23
   at Stratis.Bitcoin.Features.MemoryPool.TxMempool.GetMemPoolChildren(TxMempoolEntry entry) in D:\a\1\s\src\Stratis.Bitcoin.Features.MemoryPool\TxMemPool.cs:line 449
   at Stratis.Bitcoin.Features.MemoryPool.TxMempool.CalculateDescendants(TxMempoolEntry entry, SetEntries setDescendants) in D:\a\1\s\src\Stratis.Bitcoin.Features.MemoryPool\TxMemPool.cs:line 729
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.Bitcoin.Features.Miner.BlockDefinition.UpdatePackagesForAdded(SetEntries alreadyAdded, Dictionary`2 mapModifiedTx) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\BlockDefinition.cs:line 540
   at Stratis.Bitcoin.Features.Miner.BlockDefinition.AddTransactions(Int32& nPackagesSelected, Int32& nDescendantsUpdated) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\BlockDefinition.cs:line 453
   at Stratis.Bitcoin.Features.Miner.BlockDefinition.OnBuild(ChainedHeader chainTip, Script scriptPubKey) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\BlockDefinition.cs:line 222
   at Stratis.Bitcoin.Features.Miner.PosBlockDefinition.Build(ChainedHeader chainTip, Script scriptPubKey) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\PosBlockDefinition.cs:line 60
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.GenerateBlocksAsync(WalletSecret walletSecret, CancellationToken cancellationToken) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 402
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.<>c__DisplayClass38_0.<<Stake>b__0>d.MoveNext() in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 288
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in D:\a\1\s\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 141
```

**Comment by sondreb** [comment]
Happened again:

```
[2018-12-28 11:20:34.0292 20] INFO: Stratis.Bitcoin.Consensus.ConsensusManager+<RewindToForkPointAsync>d__50.MoveNext Reorg from block '69788-d1b44f996426b187d977fcfa9ce34a42b8d6d2dc7bdc7a5b5408fb0aa87f7d41-FullyValidated' to '69787-b176cce3975a4a468b72861a251b335e96588d30b558d3a067c58993948f2e30-FullyValidated'
[2018-12-28 11:20:34.0467 30] INFO: Stratis.Bitcoin.Features.Wallet.WalletSyncManager+<OnProcessBlockAsync>d__16.MoveNext Reorg detected, going back from '69788-d1b44f996426b187d977fcfa9ce34a42b8d6d2dc7bdc7a5b5408fb0aa87f7d41-FullyValidated' to '69787-b176cce3975a4a468b72861a251b335e96588d30b558d3a067c58993948f2e30-FullyValidated'.
[2018-12-28 11:20:34.2595 13] ERROR: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<>c__DisplayClass38_0+<<Stake>b__0>d.MoveNext Exception: System.Exception: Assertion failed
   at Stratis.Bitcoin.Utilities.Guard.Assert(Boolean condition) in D:\a\1\s\src\Stratis.Bitcoin\Utilities\Guard.cs:line 23
   at Stratis.Bitcoin.Features.MemoryPool.TxMempool.GetMemPoolChildren(TxMempoolEntry entry) in D:\a\1\s\src\Stratis.Bitcoin.Features.MemoryPool\TxMemPool.cs:line 449
   at Stratis.Bitcoin.Features.MemoryPool.TxMempool.CalculateDescendants(TxMempoolEntry entry, SetEntries setDescendants) in D:\a\1\s\src\Stratis.Bitcoin.Features.MemoryPool\TxMemPool.cs:line 729
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.Bitcoin.Features.Miner.BlockDefinition.UpdatePackagesForAdded(SetEntries alreadyAdded, Dictionary`2 mapModifiedTx) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\BlockDefinition.cs:line 540
   at Stratis.Bitcoin.Features.Miner.BlockDefinition.AddTransactions(Int32& nPackagesSelected, Int32& nDescendantsUpdated) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\BlockDefinition.cs:line 453
   at Stratis.Bitcoin.Features.Miner.BlockDefinition.OnBuild(ChainedHeader chainTip, Script scriptPubKey) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\BlockDefinition.cs:line 222
   at Stratis.Bitcoin.Features.Miner.PosBlockDefinition.Build(ChainedHeader chainTip, Script scriptPubKey) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\PosBlockDefinition.cs:line 60
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.GenerateBlocksAsync(WalletSecret walletSecret, CancellationToken cancellationToken) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 402
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.<>c__DisplayClass38_0.<<Stake>b__0>d.MoveNext() in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 288
[2018-12-28 11:20:34.2595 13] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake stopping.
[2018-12-28 11:20:34.2595 13] FATAL: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake threw an unhandled exception
[2018-12-28 11:20:34.2595 13] ERROR: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake threw an unhandled exception: System.Exception: Assertion failed
   at Stratis.Bitcoin.Utilities.Guard.Assert(Boolean condition) in D:\a\1\s\src\Stratis.Bitcoin\Utilities\Guard.cs:line 23
   at Stratis.Bitcoin.Features.MemoryPool.TxMempool.GetMemPoolChildren(TxMempoolEntry entry) in D:\a\1\s\src\Stratis.Bitcoin.Features.MemoryPool\TxMemPool.cs:line 449
   at Stratis.Bitcoin.Features.MemoryPool.TxMempool.CalculateDescendants(TxMempoolEntry entry, SetEntries setDescendants) in D:\a\1\s\src\Stratis.Bitcoin.Features.MemoryPool\TxMemPool.cs:line 729
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.Bitcoin.Features.Miner.BlockDefinition.UpdatePackagesForAdded(SetEntries alreadyAdded, Dictionary`2 mapModifiedTx) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\BlockDefinition.cs:line 540
   at Stratis.Bitcoin.Features.Miner.BlockDefinition.AddTransactions(Int32& nPackagesSelected, Int32& nDescendantsUpdated) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\BlockDefinition.cs:line 453
   at Stratis.Bitcoin.Features.Miner.BlockDefinition.OnBuild(ChainedHeader chainTip, Script scriptPubKey) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\BlockDefinition.cs:line 222
   at Stratis.Bitcoin.Features.Miner.PosBlockDefinition.Build(ChainedHeader chainTip, Script scriptPubKey) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\PosBlockDefinition.cs:line 60
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.GenerateBlocksAsync(WalletSecret walletSecret, CancellationToken cancellationToken) in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 402
   at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.<>c__DisplayClass38_0.<<Stake>b__0>d.MoveNext() in D:\a\1\s\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 288
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in D:\a\1\s\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 141
```

**Comment by dangershony** [comment]
This is likely fixed here
https://github.com/stratisproject/StratisBitcoinFullNode/commit/e70945af47f5d4b3fc1e7b69c7f5b6aaac567013
