### ISSUE TITLE
Exception while shutting down the node

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#3009]
```
info: Stratis.Bitcoin.P2P.Peer.NetworkPeerServer[0]
      [0.0.0.0:26178] Waiting for 105 connected clients to finish.
There was a problem initializing the node. Details: 'System.AggregateException: One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)) ---> System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Consensus.Behaviors.ProvenHeadersConsensusManagerBehavior.ConstructHeadersPayload(GetHeadersPayload getHeadersPayload, ChainedHeader& lastHeader) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\Behaviors\ProvenHeadersConsensusManagerBehavior.cs:line 138
   at Stratis.Bitcoin.Consensus.ConsensusManagerBehavior.ProcessGetHeadersAsync(INetworkPeer peer, GetHeadersPayload getHeadersPayload) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManagerBehavior.cs:line 194
   at Stratis.Bitcoin.Consensus.ConsensusManagerBehavior.OnMessageReceivedAsync(INetworkPeer peer, IncomingMessage message) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManagerBehavior.cs:line 145
   at Stratis.Bitcoin.Features.Consensus.Behaviors.ProvenHeadersConsensusManagerBehavior.OnMessageReceivedAsync(INetworkPeer peer, IncomingMessage message) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\Behaviors\ProvenHeadersConsensusManagerBehavior.cs:line 102
   at Stratis.Bitcoin.Utilities.AsyncExecutionEvent`2.ExecuteCallbacksAsync(TSender sender, TArg arg) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncExecutionEvent.cs:line 156
   at Stratis.Bitcoin.P2P.Peer.NetworkPeer.ProcessMessageAsync(IncomingMessage message, CancellationToken cancellation) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeer.cs:line 507
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.ConsumerAsync() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 135
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.DisposeInternal(Boolean calledFromConsumerTask) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 248
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 234
   at Stratis.Bitcoin.P2P.Protocol.CallbackMessageListener`1.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\CallbackMessageListener.cs:line 47
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 460
   at Stratis.Bitcoin.P2P.Peer.NetworkPeer.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeer.cs:line 874
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerDisposer.OnEnqueueAsync(INetworkPeer peer, CancellationToken cancellationToken) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerDisposer.cs:line 78
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.ConsumerAsync() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 135
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.DisposeInternal(Boolean calledFromConsumerTask) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 248
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 234
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerDisposer.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerDisposer.cs:line 104
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerServer.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerServer.cs:line 194
   at Stratis.Bitcoin.Connection.ConnectionManager.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Connection\ConnectionManager.cs:line 269
   at Stratis.Bitcoin.FullNode.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\FullNode.cs:line 274
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.RunAsync(IFullNode node, CancellationToken cancellationToken, String shutdownMessage, String shutdownCompleteMessage) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\FullNodeExtensions.cs:line 95
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.RunAsync(IFullNode node) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\FullNodeExtensions.cs:line 53
   at Stratis.StratisD.Program.Main(String[] args) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.StratisD\Program.cs:line 44
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Consensus.Behaviors.ProvenHeadersConsensusManagerBehavior.ConstructHeadersPayload(GetHeadersPayload getHeadersPayload, ChainedHeader& lastHeader) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\Behaviors\ProvenHeadersConsensusManagerBehavior.cs:line 138
   at Stratis.Bitcoin.Consensus.ConsensusManagerBehavior.ProcessGetHeadersAsync(INetworkPeer peer, GetHeadersPayload getHeadersPayload) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManagerBehavior.cs:line 194
   at Stratis.Bitcoin.Consensus.ConsensusManagerBehavior.OnMessageReceivedAsync(INetworkPeer peer, IncomingMessage message) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManagerBehavior.cs:line 145
   at Stratis.Bitcoin.Features.Consensus.Behaviors.ProvenHeadersConsensusManagerBehavior.OnMessageReceivedAsync(INetworkPeer peer, IncomingMessage message) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\Behaviors\ProvenHeadersConsensusManagerBehavior.cs:line 102
   at Stratis.Bitcoin.Utilities.AsyncExecutionEvent`2.ExecuteCallbacksAsync(TSender sender, TArg arg) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncExecutionEvent.cs:line 156
   at Stratis.Bitcoin.P2P.Peer.NetworkPeer.ProcessMessageAsync(IncomingMessage message, CancellationToken cancellation) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeer.cs:line 507
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.ConsumerAsync() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 135
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.DisposeInternal(Boolean calledFromConsumerTask) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 248
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 234
   at Stratis.Bitcoin.P2P.Protocol.CallbackMessageListener`1.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Protocol\CallbackMessageListener.cs:line 47
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerConnection.cs:line 460
   at Stratis.Bitcoin.P2P.Peer.NetworkPeer.Dispose() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeer.cs:line 874
   at Stratis.Bitcoin.P2P.Peer.NetworkPeerDisposer.OnEnqueueAsync(INetworkPeer peer, CancellationToken cancellationToken) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeerDisposer.cs:line 78
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.ConsumerAsync() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 135
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Consensus.Behaviors.ProvenHeadersConsensusManagerBehavior.ConstructHeadersPayload(GetHeadersPayload getHeadersPayload, ChainedHeader& lastHeader) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\Behaviors\ProvenHeadersConsensusManagerBehavior.cs:line 138
   at Stratis.Bitcoin.Consensus.ConsensusManagerBehavior.ProcessGetHeadersAsync(INetworkPeer peer, GetHeadersPayload getHeadersPayload) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManagerBehavior.cs:line 194
   at Stratis.Bitcoin.Consensus.ConsensusManagerBehavior.OnMessageReceivedAsync(INetworkPeer peer, IncomingMessage message) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManagerBehavior.cs:line 145
   at Stratis.Bitcoin.Features.Consensus.Behaviors.ProvenHeadersConsensusManagerBehavior.OnMessageReceivedAsync(INetworkPeer peer, IncomingMessage message) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\Behaviors\ProvenHeadersConsensusManagerBehavior.cs:line 102
   at Stratis.Bitcoin.Utilities.AsyncExecutionEvent`2.ExecuteCallbacksAsync(TSender sender, TArg arg) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncExecutionEvent.cs:line 156
   at Stratis.Bitcoin.P2P.Peer.NetworkPeer.ProcessMessageAsync(IncomingMessage message, CancellationToken cancellation) in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\P2P\Peer\NetworkPeer.cs:line 507
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.ConsumerAsync() in C:\Users\user\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 135<---
<---
```

**Comment by maciejzaleski** [comment]
Retested and confirmed to be fixed
