### ISSUE TITLE
Error when reconnecting the chain after a reorg

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#3011]
```
[2018-12-25 02:33:12.4541 13] INFO: Stratis.Bitcoin.Consensus.ConsensusManager+<RewindToForkPointAsync>d__50.MoveNext Reorg from block '1125080-a2ed4b7fe759fa5bbed1a6937fbf9733ad4ae28f1fa8de445de6fe365667b196-FullyValidated' to '1125078-7af235052794ea3a48532044b1316c7b818002edb6c9652946ceaa4ab471014b-FullyValidated'
[2018-12-25 02:33:12.4840 37] INFO: Stratis.Bitcoin.Consensus.ConsensusManager+<RewindToForkPointAsync>d__50.MoveNext Reorg from block '1125079-f3f2a8ea679b65d6e23d05408c429b1fe85d488936c62a8077db162988cc0683-FullyValidated' to '1125078-7af235052794ea3a48532044b1316c7b818002edb6c9652946ceaa4ab471014b-FullyValidated'
[2018-12-25 02:33:12.8785 37] ERROR: Stratis.Bitcoin.Consensus.ConsensusManager+<ReconnectOldChainAsync>d__52.MoveNext A critical error has prevented reconnecting blocks, error = bad-txns-BIP30 : tried to overwrite transaction
[2018-12-25 02:33:12.8785 37] FATAL: Stratis.Bitcoin.Consensus.Validators.PartialValidator+<OnEnqueueAsync>d__5.MoveNext Partial validation callback threw an exception: Stratis.Bitcoin.Consensus.ConsensusException: A critical error has prevented reconnecting blocks.
   at Stratis.Bitcoin.Consensus.ConsensusManager.ReconnectOldChainAsync(List`1 blocksToReconnect) in C:\Users\fullnodedan\Documents\Github\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 744
   at Stratis.Bitcoin.Consensus.ConsensusManager.FullyValidateLockedAsync(ChainedHeader newTip, Boolean blockMined) in C:\Users\fullnodedan\Documents\Github\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 596
   at Stratis.Bitcoin.Consensus.ConsensusManager.OnPartialValidationSucceededAsync(ChainedHeader chainedHeader) in C:\Users\fullnodedan\Documents\Github\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 429
   at Stratis.Bitcoin.Consensus.ConsensusManager.OnPartialValidationCompletedCallbackAsync(ValidationContext validationContext) in C:\Users\fullnodedan\Documents\Github\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 371
   at Stratis.Bitcoin.Consensus.Validators.PartialValidator.OnEnqueueAsync(PartialValidationItem item, CancellationToken cancellationtoken) in C:\Users\fullnodedan\Documents\Github\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\Validators\BlockValidator.cs:line 150.
```

**Comment by dangershony** [comment]
https://github.com/stratisproject/StratisBitcoinFullNode/issues/2927

**Comment by maciejzaleski** [comment]
The issue has been resolved
