### ISSUE TITLE
Error when storing a proven header

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#3012]
```
[2018-12-25 02:35:34.7851 78] FATAL: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext FlushChain threw an unhandled exception
[2018-12-25 02:35:34.7851 78] ERROR: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext FlushChain threw an unhandled exception: Stratis.Bitcoin.Features.Consensus.ProvenBlockHeaders.ProvenBlockHeaderException: Invalid new tip hash, tip hash has not changed.
   at Stratis.Bitcoin.Features.Consensus.ProvenBlockHeaders.ProvenBlockHeaderRepository.PutAsync(SortedDictionary`2 headers, HashHeightPair newTip) in C:\Users\mainnet\Desktop\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\ProvenBlockHeaders\ProvenBlockHeaderRepository.cs:line 155
   at Stratis.Bitcoin.Features.Consensus.ProvenBlockHeaders.ProvenBlockHeaderStore.SaveAsync() in C:\Users\mainnet\Desktop\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\ProvenBlockHeaders\ProvenBlockHeaderStore.cs:line 238
   at Stratis.Bitcoin.Base.BaseFeature.<StartChainAsync>b__27_0(CancellationToken token) in C:\Users\mainnet\Desktop\StratisBitcoinFullNode\src\Stratis.Bitcoin\Base\BaseFeature.cs:line 246
```

**Comment by dangershony** [comment]
[node-2018-12-26.14.zip](https://github.com/stratisproject/StratisBitcoinFullNode/files/2712006/node-2018-12-26.14.zip)

**Comment by maciejzaleski** [comment]
Resolved
