### ISSUE TITLE
Failing Integration Tests

### ISSUE THREAD

**Issue by quantumagi** [stratisproject/StratisBitcoinFullNode#3126]
Failing on MacOS:

```
2019-01-21T12:51:01.6245880Z Failed   CanOverrideAllPorts
2019-01-21T12:51:01.6246310Z Error Message:
2019-01-21T12:51:01.6246740Z  System.AggregateException : One or more errors occurred. (Permission denied)
2019-01-21T12:51:01.6248180Z ---- System.Net.Sockets.SocketException : Permission denied
2019-01-21T12:51:01.6248390Z Stack Trace:
2019-01-21T12:51:01.6249190Z    at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 126
2019-01-21T12:51:01.6258340Z    at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Initialize() in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 52
2019-01-21T12:51:01.6258610Z    at Stratis.Bitcoin.FullNode.Start() in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin/FullNode.cs:line 208
2019-01-21T12:51:01.6258770Z    at Stratis.Bitcoin.IntegrationTests.Common.Runners.NodeRunner.Start() in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin.IntegrationTests.Common/Runners/NodeRunner.cs:line 45
2019-01-21T12:51:01.6258940Z    at Stratis.Bitcoin.IntegrationTests.Common.EnvironmentMockUpHelpers.CoreNode.Start() in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs:line 261
2019-01-21T12:51:01.6259080Z    at Stratis.Bitcoin.IntegrationTests.CustomNodeBuilderTests.CanOverrideAllPorts() in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin.IntegrationTests/CustomNodeBuilderTests.cs:line 88
2019-01-21T12:51:01.6260130Z ----- Inner Stack Trace -----
2019-01-21T12:51:01.6260270Z    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
2019-01-21T12:51:01.6260380Z    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
2019-01-21T12:51:01.6260500Z    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
2019-01-21T12:51:01.6260900Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
2019-01-21T12:51:01.6261020Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
2019-01-21T12:51:01.6262120Z --- End of stack trace from previous location where exception was thrown ---
2019-01-21T12:51:01.6262260Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
2019-01-21T12:51:01.6262400Z    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
2019-01-21T12:51:01.6262550Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
2019-01-21T12:51:01.6262670Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
2019-01-21T12:51:01.6262840Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
2019-01-21T12:51:01.6262960Z    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
2019-01-21T12:51:01.6263060Z    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
2019-01-21T12:51:01.6263190Z    at Stratis.Bitcoin.Features.RPC.RPCFeature.InitializeAsync() in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin.Features.RPC/RPCFeature.cs:line 100
2019-01-21T12:51:01.6263340Z    at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 52
2019-01-21T12:51:01.6263490Z    at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 102

2019-01-21T12:48:59.8303570Z Failed   ReorgChain_FailsFullValidation_Reconnect_OldChain_FromSecondMiner_Disconnected
2019-01-21T12:48:59.8303990Z Error Message:
2019-01-21T12:48:59.8304290Z  Unknown Reason
2019-01-21T12:48:59.8304450Z The operation was canceled.
2019-01-21T12:48:59.8304780Z Expected: False
2019-01-21T12:48:59.8305030Z Actual:   True
2019-01-21T12:48:59.8305130Z Stack Trace:
2019-01-21T12:48:59.8305490Z    at Stratis.Bitcoin.IntegrationTests.Common.TestHelper.WaitLoop(Func`1 act, String failureReason, Int32 waitTimeSeconds, Int32 retryDelayInMiliseconds, CancellationToken cancellationToken) in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs:line 40
2019-01-21T12:48:59.8305950Z    at Stratis.Bitcoin.IntegrationTests.Common.TestHelper.Connect(CoreNode thisNode, CoreNode connectToNode) in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs:line 371
2019-01-21T12:48:59.8306150Z    at Stratis.Bitcoin.IntegrationTests.Common.TestHelper.ConnectAndSync(CoreNode thisNode, Boolean ignoreMempool, CoreNode[] to) in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs:line 405
2019-01-21T12:48:59.8306240Z    at Stratis.Bitcoin.IntegrationTests.Common.TestHelper.ConnectAndSync(CoreNode thisNode, CoreNode[] to) in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs:line 393
2019-01-21T12:48:59.8306330Z    at Stratis.Bitcoin.IntegrationTests.ConsensusManagerFailedReorgTests.ReorgChain_FailsFullValidation_Reconnect_OldChain_FromSecondMiner_Disconnected() in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerFailedReorgTests.cs:line 116

2019-01-21T12:30:03.5204650Z Failed   CanCall_AddNode
2019-01-21T12:30:03.5205330Z Error Message:
2019-01-21T12:30:03.5205570Z  Assert.Throws() Failure
2019-01-21T12:30:03.5205970Z Expected: typeof(System.Net.Sockets.SocketException)
2019-01-21T12:30:03.5206380Z Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
2019-01-21T12:30:03.5208170Z ---- System.Threading.Tasks.TaskCanceledException : A task was canceled.
2019-01-21T12:30:03.5208410Z Stack Trace:
2019-01-21T12:30:03.5208570Z    at Stratis.Bitcoin.Connection.ConnectionManager.ConnectAsync(IPEndPoint ipEndpoint) in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin/Connection/ConnectionManager.cs:line 447
2019-01-21T12:30:03.5208760Z    at Stratis.Bitcoin.Connection.ConnectionManagerController.AddNodeRPC(String endpointStr, String command) in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin/Connection/ConnectionManagerController.cs:line 54
2019-01-21T12:30:03.5208940Z    at Stratis.Bitcoin.IntegrationTests.RPC.AddNodeActionTest.<>c__DisplayClass0_0.<CanCall_AddNode>b__0() in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin.IntegrationTests/RPC/AddNodeActionTest.cs:line 21
2019-01-21T12:30:03.5209850Z ----- Inner Stack Trace -----
2019-01-21T12:30:03.5210030Z    at Stratis.Bitcoin.Connection.ConnectionManager.ConnectAsync(IPEndPoint ipEndpoint) in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin/Connection/ConnectionManager.cs:line 447
2019-01-21T12:30:03.5210200Z    at Stratis.Bitcoin.Connection.ConnectionManagerController.AddNodeRPC(String endpointStr, String command) in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin/Connection/ConnectionManagerController.cs:line 54
2019-01-21T12:30:03.5210390Z    at Stratis.Bitcoin.IntegrationTests.RPC.AddNodeActionTest.<>c__DisplayClass0_0.<CanCall_AddNode>b__0() in /Users/vsts/agent/2.144.0/work/1/s/src/Stratis.Bitcoin.IntegrationTests/RPC/AddNodeActionTest.cs:line 21
```

**Comment by quantumagi** [comment]
On MacOS ports below 1024 are privileged, and cannot be bound to by anyone other than root.

**Comment by fassadlr** [comment]
Tests are stable.
