### ISSUE TITLE
Bug while running FN: A critical error has prevented reconnecting blocks

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#3137]
Happened on testnet. Node version: d7d1523 (master from 16/01/2019 )

```
[2019-01-23 11:58:31.2885 54] ERROR: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute An error occurred: 'System.AggregateException: One or more errors occurred. (A critical error has prevented reconnecting blocks.) ---> Stratis.Bitcoin.Consensus.ConsensusException: A critical error has prevented reconnecting blocks.
   at Stratis.Bitcoin.Consensus.ConsensusManager.ReconnectOldChainAsync(List`1 blocksToReconnect) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 786
   at Stratis.Bitcoin.Consensus.ConsensusManager.FullyValidateLockedAsync(ChainedHeader newTip, Boolean blockMined) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 638
   at Stratis.Bitcoin.Consensus.ConsensusManager.OnPartialValidationSucceededAsync(ChainedHeader chainedHeader) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 471
   at Stratis.Bitcoin.Consensus.ConsensusManager.OnPartialValidationCompletedCallbackAsync(ValidationContext validationContext) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 413
   at Stratis.Bitcoin.Consensus.Validators.PartialValidator.OnEnqueueAsync(PartialValidationItem item, CancellationToken cancellationtoken) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\Validators\BlockValidator.cs:line 150
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.ConsumerAsync() in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 135
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.DisposeInternal(Boolean calledFromConsumerTask) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 248
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.Dispose() in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 234
   at Stratis.Bitcoin.Consensus.Validators.PartialValidator.Dispose() in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\Validators\BlockValidator.cs:line 141
   at Stratis.Bitcoin.Base.BaseFeature.Dispose() in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Base\BaseFeature.cs:line 311
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Dispose>b__4_0(IFullNodeFeature feature) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 67
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 102
---> (Inner Exception #0) Stratis.Bitcoin.Consensus.ConsensusException: A critical error has prevented reconnecting blocks.
   at Stratis.Bitcoin.Consensus.ConsensusManager.ReconnectOldChainAsync(List`1 blocksToReconnect) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 786
   at Stratis.Bitcoin.Consensus.ConsensusManager.FullyValidateLockedAsync(ChainedHeader newTip, Boolean blockMined) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 638
   at Stratis.Bitcoin.Consensus.ConsensusManager.OnPartialValidationSucceededAsync(ChainedHeader chainedHeader) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 471
   at Stratis.Bitcoin.Consensus.ConsensusManager.OnPartialValidationCompletedCallbackAsync(ValidationContext validationContext) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 413
   at Stratis.Bitcoin.Consensus.Validators.PartialValidator.OnEnqueueAsync(PartialValidationItem item, CancellationToken cancellationtoken) in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\Validators\BlockValidator.cs:line 150
   at Stratis.Bitcoin.Utilities.AsyncQueue`1.ConsumerAsync() in C:\Users\fullnodeivan\AppData\Roaming\WatchTool_StratisFNRepo\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncQueue.cs:line 135<---
'
```

**Comment by maciejzaleski** [comment]
Issue has been resolved
