### ISSUE TITLE
Stratis.StratisSmartContractsD - Error 'System.NotSupportedException: Specified method is not supported.

### ISSUE THREAD

**Issue by damien-r** [stratisproject/StratisBitcoinFullNode#3226]
Hi,

When I start the project Stratis.StratisSmartContractsD, I let it run for a little time to mine a couple of blocks. After that, I stop the process and then I restart it and got the following error :

```
info: Stratis.Bitcoin.FullNode[0]


           .d8888b. 88888888888 8888888b.         d8888 88888888888 8888888  .d8888b.
          d88P  Y88b    888     888   Y88b       d88888     888       888   d88P  Y88b
          Y88b.         888     888    888      d88P888     888       888   Y88b.
           "Y888b.      888     888   d88P     d88P 888     888       888    "Y888b.
              "Y88b.    888     8888888P"     d88P  888     888       888       "Y88b.
                "888    888     888 T88b     d88P   888     888       888         "888
          Y88b  d88P    888     888  T88b   d8888888888     888       888   Y88b  d88P
           "Y8888P"     888     888   T88b d88P     888     888     8888888  "Y8888P"

      ················································································
      ················································································
      ······································STRAT·····································
      ···································STRATISSTRAT·································
      ·······························STRATISS····STRATIS······························
      ····························STRATIS···········STRATISS··························
      ·························STRATIS··················STRATIS·······················
      ·····················STRATISS························STRATISS···················
      ··················STRATIS································STRATIS················
      ···············STRATIS······································STRATIS·············
      ···········STRATIS··············································STRATIS·········
      ········STRATIS····················································STRATISS·····
      ····STRATISS···························································STRATIS··
      ··STRATIS································································STRAT··
      ··STRATISST··························································STRATISS···
      ··STRA··STRATIS···················································STRATIS·······
      ··STRA·····STRATISS············································STRATIS··········
      ··STRA·········STRATIS·····································STRATIS··············
      ··STRATI··········STRATISS······························STRATIS··········STRAT··
      ····STRATIS···········STRATIS·······················STRATIS··········STRATISST··
      ·······STRATISS··········STRATISS················STRATIS·········STRATISS··STR··
      ···········STRATIS···········STRATIS·········STRATIST·········STRATIST·····STR··
      ·····S········STRATIS···········STRATIS··STRATISS··········STRATIS········STRA··
      ····STRATIS·······STRATIS···········STRATISST··········STRATISS·········STRATI··
      ······STRATIS········STRATIS···········STR··········STRATIS·········STRATIS·····
      ·········STRATISS········STRATIS················STRATISS·········STRATIS········
      ·············STRATIS········STRATIS··········STRATIS·········STRATIS············
      ················STRATIS·········STRATIS··STRATISS·········STRATIS···············
      ···················STRATISS········STRATISSTR·········STRATISS··················
      ·······················STRATIS········STRA·········STRATIS······················
      ··························STRATISS·············STRATISS·························
      ······························STRATIS·······STRATIS·····························
      ·································STRATISSTRATISS································
      ·····································STRATIS····································
      ················································································



info: Stratis.Bitcoin.FullNode[0]
      Full node initialized on SmartContractsPoATest-0.13.0-beta.
info: Stratis.Bitcoin.FullNode[0]
      Starting node.
info: Stratis.Bitcoin.Base.BaseFeature[0]
      Loading finalized block height.
info: Stratis.Bitcoin.Base.BaseFeature[0]
      Loading chain.
info: Stratis.Bitcoin.Base.BaseFeature[0]
      Chain loaded at height 2.
info: Stratis.Bitcoin.FullNode[0]
      FlushChain starting in 60 seconds.
info: Stratis.Bitcoin.FullNode[0]
      Periodic peer flush starting in 300 seconds.
info: Stratis.Bitcoin.Features.RPC.RPCFeature[0]
      RPC Server is off based on configuration.
info: Stratis.Bitcoin.Features.SmartContracts.SmartContractFeature[0]
      Smart Contract Feature Injected.
info: Stratis.Bitcoin.Features.PoA.FederationManager[0]
      Federation contains 2 members. Their public keys are:
      02d082f2f0d7b90561960fba2de65510b3a8bdbaa7c0285edc1fadde484b3fdae6
      03cb103016ec4e999af5a6aeffec6fe79b719a472e60b9ce7575a605d8a6c2c36c
info: Stratis.Bitcoin.Features.PoA.FederationManager[0]
      Federation key pair was successfully loaded. Your public key is: '02d082f2f0d7b90561960fba2de65510b3a8bdbaa7c0285edc1fadde484b3fdae6'.
info: Stratis.Bitcoin.Features.PoA.PoAMiner[0]
      Waiting 26 seconds until block can be mined.
fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred: 'System.NotSupportedException: Specified method is not supported.
         at Stratis.Bitcoin.Utilities.DBreezeSerializer.Deserialize(Byte[] bytes, Type type) in C:\Workspaces\CosmoHeveltia.FairyDust\src\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\DBreezeSerializer.cs:line 136
         at Stratis.Bitcoin.Utilities.DBreezeSerializer.Deserialize[T](Byte[] bytes) in C:\Workspaces\CosmoHeveltia.FairyDust\src\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\DBreezeSerializer.cs:line 82
         at Stratis.Bitcoin.Utilities.KeyValueRepository.LoadValue[T](String key) in C:\Workspaces\CosmoHeveltia.FairyDust\src\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\KeyValueRepository.cs:line 107
         at Stratis.Bitcoin.Features.PoA.Voting.VotingManager.LoadPolls(String key) in C:\Workspaces\CosmoHeveltia.FairyDust\src\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.PoA\Voting\VotingManager.cs:line 130
         at Stratis.Bitcoin.Features.PoA.Voting.VotingManager.Initialize() in C:\Workspaces\CosmoHeveltia.FairyDust\src\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.PoA\Voting\VotingManager.cs:line 61
         at Stratis.Bitcoin.Features.PoA.PoAFeature.InitializeAsync() in C:\Workspaces\CosmoHeveltia.FairyDust\src\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.PoA\PoAFeature.cs:line 95
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in C:\Workspaces\CosmoHeveltia.FairyDust\src\StratisBitcoinFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 52
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in C:\Workspaces\CosmoHeveltia.FairyDust\src\StratisBitcoinFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 102'
fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred starting the application.
Running interactively, press enter to stop.
```

**Comment by codingupastorm** [comment]
hey @damien-r cheers for this.

Some work that was happening on another feature made it into master when it shouldn't have. We'll sort this out - if you want to connect you can use the following branch:
https://github.com/stratisproject/StratisBitcoinFullNode/tree/sc/v0.13.0-beta

**Comment by codingupastorm** [comment]
Going to close but feel free to reopen if you have further issues along the same lines.

Should be fixed in master regardless in the next couple days I believe.
