### ISSUE TITLE
[BUG] DBreezeCoinView.Initialize crashes on unhandled exception

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#354]
```
fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred starting the application

Unhandled Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Consensus.CoinViews.DBreezeCoinView.<Initialize>b__10_0() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Features\Consensus\CoinViews\DBreezeCoinView.cs:line 51
   at Stratis.Bitcoin.Utilities.DBreezeSingleThreadSession.<>c__DisplayClass8_0.<Execute>b__0() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\DBreezeSingleThreadSession.cs:line 171
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Stratis.Bitcoin.Features.Consensus.ConsensusFeature.Start() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Features\Consensus\ConsensusFeature.cs:line 99
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Start>b__3_1(IFullNodeFeature service) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 56
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 95
   --- End of inner exception stack trace ---
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 113
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Start() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 61
   at Stratis.Bitcoin.FullNode.Start() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\FullNode.cs:line 179
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.Run(IFullNode node, CancellationToken cancellationToken, String shutdownMessage) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\FullNodeExtensions.cs:line 68
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.Run(IFullNode node) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\FullNodeExtensions.cs:line 53
   at Stratis.BitcoinD.Program.Main(String[] args) in C:\StratisBitcoinFullNode\Stratis.BitcoinD\Program.cs:line 40
```

**Comment by Aprogiena** [comment]
This happens to me from time to time and I don't know why or when exactly.

**Comment by Aprogiena** [comment]
Even if I remove APPDATA directory it still occurs, there is no `dotnet.exe` process.

**Comment by Aprogiena** [comment]
When loading to debugger:
```
DBreeze.Exceptions.DBreezeException occurred
  HResult=0x80131500
  Message=Creation of the database folder failed!
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at DBreeze.DBreezeEngine.InitDb()
   at DBreeze.DBreezeEngine..ctor(String DBreezeDataFolderName)
   at Stratis.Bitcoin.Utilities.DBreezeSingleThreadSession.<>c__DisplayClass5_0.<.ctor>b__0() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\DBreezeSingleThreadSession.cs:line 79
   at System.Threading.Tasks.Task.Execute()

Inner Exception 1:
ArgumentException: An item with the same key has already been added. Key: System.UInt64

```

**Comment by Aprogiena** [comment]
alternatively I also get

```
DBreeze.Exceptions.DBreezeException occurred
  HResult=0x80131500
  Message=Creation of the database folder failed!
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at DBreeze.DBreezeEngine.InitDb()
   at DBreeze.DBreezeEngine..ctor(String DBreezeDataFolderName)
   at Stratis.Bitcoin.Utilities.DBreezeSingleThreadSession.<>c__DisplayClass5_0.<.ctor>b__0() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\DBreezeSingleThreadSession.cs:line 79
   at System.Threading.Tasks.Task.Execute()

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by Aprogiena** [comment]
@darxtar (on slack) revealed that locking around 
```
this.engine = new DBreezeEngine(folder);
```
inside `DBreezeSingleThreadSession` with a static lock fixes the problem. 

The root of the problem is that 3 different components each create their own `DBreezeSingleThreadSession`. Thus there are 3 exclusive schedulers instead of just 1 and they can race on `DBreezeEngine` constructor.

**Comment by dangershony** [comment]
I think that is correct to have a single thread sceduler per db engine, they are separate instances of the engine and each dbreeze engine runs on its own thread.

**Comment by Aprogiena** [comment]
Possibly yes, I don't know the details, you have mentioned earlier some kind of this is necessary for DBreeze. Anyway, it seems that during the initialization there have to be an exclusive access.

**Comment by dangershony** [comment]
I might refer to the dbreeze documentation might be hints on initialize retirements

**Comment by Aprogiena** [comment]
So, any ideas how to fix it in an elegant way? 
I currently don't understand much the initialization process of the whole thing. All the DI is alien to me, I think it is quite hard to grasp it as well as to find out what are the real dependencies between the components. 

I'm not sure if it is possible to make the initialization process serial. If it can't be done easily, we need some kind of exclusive mechanism there.

**Comment by dangershony** [comment]
It seems this is a very precise race condition
From dbreeze DataTypesConvertor.InitDict() method
```
    internal static void InitDict()
    {
      if (DataTypesConvertor.dcb.Count > 0)
        return;
      DataTypesConvertor.dcb.Add(DataTypesConvertor.TYPE_BYTE_ARRAY, (Func<byte[], object>) (dt => (object) dt));
      DataTypesConvertor.dcb.Add(DataTypesConvertor.TYPE_ULONG, (Func<byte[], object>) (dt => (object) dt.To_UInt64_BigEndian()));

```

We have 3 db instances of dbreeze that are initiated sequentially but as the  initialize  constructor uses a task we get a race condition, of course a Task in the constructor is bad practice but thats a different issue.

This fixed it for me
```
            this.singleThread = new CustomThreadPoolTaskScheduler(1, 100, threadName);
            var task = new Task(() =>
            {
                DBreeze.Utils.CustomSerializator.ByteArraySerializator = NBitcoinSerialize;
                DBreeze.Utils.CustomSerializator.ByteArrayDeSerializator = NBitcoinDeserialize;
                this.engine = new DBreezeEngine(folder);
                this.transaction = this.engine.GetTransaction();
            });

	    task.Start(this.singleThread);
	    task.GetAwaiter().GetResult();

```

**Comment by Aprogiena** [comment]
There are at lest 2 different races here - as I got 2 different exceptions.
But let me confirm that this fixes the problem.

**Comment by Aprogiena** [comment]
Looks fine at this moment. Will see as the time goes if this is solved.

**Comment by Aprogiena** [comment]
If I understand what you did there - the features and services are actually loaded in serial fashion, but due to this task having its own thread, it happens that initialization of one component finishes and initialization of another starts before this thread is started, and that second component does the same - makes a task to be scheduled in separated thread. And then those tasks are run in 2 separated threads and can collide. But if we await for this task to be finished here, we restore the serial fashion of the initialization process. Is that right? If so, this definitely fixes the problem.

**Comment by dangershony** [comment]
Yes you got it right, feature load is sequential, probably something changed in the code that made the threads collide.

But the real problem here is that dbreeze init method is not thread safe.

**Comment by Aprogiena** [comment]
This should be fixed by https://github.com/stratisproject/StratisBitcoinFullNode/pull/357
