### ISSUE TITLE
[POS] Exception in GenerateBlocks

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#402]
```
[2017-09-02 14:32:50.0989 17] DEBUG: Stratis.Bitcoin.Features.Miner.PosMinting+<>c__DisplayClass32_0.<Mine>b__0 Exception occurred in miner loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Stratis.Bitcoin.Features.Miner.PosMinting.GenerateBlocks(WalletSecret walletSecret) in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 242
   at Stratis.Bitcoin.Features.Miner.PosMinting.<>c__DisplayClass32_0.<Mine>b__0(CancellationToken token) in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 146
```

**Comment by Aprogiena** [comment]
```
                    UnspentOutputs set = coinset.UnspentOutputs.FirstOrDefault(f => f?.TransactionId == infoTransaction.Transaction.Id);
                    TxOut utxo = set?._Outputs[infoTransaction.Transaction.Index];
```

it is the second line here
