### ISSUE TITLE
[Wallet] WalletSyncManager.ProcessBlock assertion failed

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#405]
StratisD crashes while mining:
```
info: Stratis.Bitcoin.Features.Consensus.ConsensusFeature[0]
      Reorg detected, rewinding from 97534 (62ff0bf4cb40b30ed69816a32cfeaa9b29dc482250a065a892fbca26e8529dce) to 97533 (283dc87de10ea19ffaf8fd2813581d3b43b7cff054bf440e8138105f4a12c86b)
crit: Stratis.Bitcoin.Features.Consensus.ConsensusFeature[0]
      Consensus loop unhandled exception (Tip:97533)
System.Exception: Assertion failed
   at Stratis.Bitcoin.Utilities.Guard.Assert(Boolean condition) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\Guard.cs:line 22
   at Stratis.Bitcoin.Features.Wallet.WalletSyncManager.ProcessBlock(Block block) in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\WalletSyncManager.cs:line 91
   at Stratis.Bitcoin.Features.Wallet.Notifications.BlockObserver.OnNextCore(Block block) in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\Notifications\BlockObserver.cs:line 24
   at System.Reactive.SafeObserver`1.OnNext(TSource value)
   at System.Reactive.Observer`1.OnNext(T value)
   at System.Reactive.SynchronizedObserver`1.OnNextCore(T value)
   at Stratis.Bitcoin.Signals.Signaler`1.Broadcast(T item) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Signals\Signaler.cs:line 70
   at Stratis.Bitcoin.Signals.Signals.SignalBlock(Block block) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Signals\Signals.cs:line 74
   at Stratis.Bitcoin.Features.Consensus.ConsensusFeature.RunLoop() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Features\Consensus\ConsensusFeature.cs:line 165

Unhandled Exception: System.Exception: Assertion failed
   at Stratis.Bitcoin.Utilities.Guard.Assert(Boolean condition) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\Guard.cs:line 22
   at Stratis.Bitcoin.Features.Wallet.WalletSyncManager.ProcessBlock(Block block) in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\WalletSyncManager.cs:line 91
   at Stratis.Bitcoin.Features.Wallet.Notifications.BlockObserver.OnNextCore(Block block) in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\Notifications\BlockObserver.cs:line 24
   at System.Reactive.SafeObserver`1.OnNext(TSource value)
   at System.Reactive.Observer`1.OnNext(T value)
   at System.Reactive.SynchronizedObserver`1.OnNextCore(T value)
   at Stratis.Bitcoin.Signals.Signaler`1.Broadcast(T item) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Signals\Signaler.cs:line 70
   at Stratis.Bitcoin.Signals.Signals.SignalBlock(Block block) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Signals\Signals.cs:line 74
   at Stratis.Bitcoin.Features.Consensus.ConsensusFeature.RunLoop() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Features\Consensus\ConsensusFeature.cs:line 186
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by Aprogiena** [comment]
This crash is rare (took me 48 hours to reproduce).

here are some more logs, can supply earlier logs as well if necessary


```
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.StakeChainStore.Get (-)[LOADED]:*.HashProof='0000c736ac9ded5f938c6cf16d89517cf2dc3e539f0e9246e9da13e064e1c0c2'
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.StakeChainStore.Get (blockid:'58cf01c83b564856f44e052bdc1de1bbfdc796022ce54553d4a9e97e62f4b6ec')
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.StakeChainStore.Get (-)[LOADED]:*.HashProof='0000933c60504e20351a09916fb2ff39a9b7003f80b7c42f5239a09fa88682a0'
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.StakeChainStore.Get (blockid:'fcb1323066cbf9e450dd1f5592255c516a80af7142735cd2c3c38c14218efb4a')
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.StakeChainStore.Get (-)[LOADED]:*.HashProof='0002f9bc9b4fde29f67a8cdebc64638760196c15fce31a6298833e733916f450'
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.StakeValidator.ComputeStakeModifier (-):StakeModifier=0,StakeModifierV2='1c6eb913645451b44274996ccd8d3d802cfd294c984ad5e3c51b2c52312acc9e'
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.CheckAndComputeStake (-)
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PowConsensusValidator.ExecuteBlock ()
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.UpdateCoinView ()
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PowConsensusValidator.UpdateCoinView ()
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PowConsensusValidator.UpdateCoinView (-)
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.UpdateCoinView (-)
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.UpdateCoinView ()
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PowConsensusValidator.UpdateCoinView ()
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PowConsensusValidator.UpdateCoinView (-)
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.UpdateCoinView (-)
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.CheckBlockReward (nFees:0.00000000,chainedBlock:'283dc87de10ea19ffaf8fd2813581d3b43b7cff054bf440e8138105f4a12c86b/97533')
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.CheckBlockReward Block stake reward is 1.00000000, calculated reward is 1.00000000.
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.CheckBlockReward (-)
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PowConsensusValidator.ExecuteBlock (-)
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.StakeChainStore.SetAsync (chainedBlock:'283dc87de10ea19ffaf8fd2813581d3b43b7cff054bf440e8138105f4a12c86b/97533',blockStake.HashProof:'00789ea1d4c4e70823362b4187d1527f783a99e56a621bab908965703ddd0862')
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.StakeChainStore.SetAsync (-)[ALREADY_EXISTS]
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.ExecuteBlock (-)
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.CoinViews.CachedCoinView.SaveChangesAsync (unspentOutputs.Count():3,originalOutputs.Count():(null),oldBlockHash:'f85915c3b4b3b0e5a0cb7853e33e1af648dca7dd91bc185ba41d9b3463b31f29',nextBlockHash:'283dc87de10ea19ffaf8fd2813581d3b43b7cff054bf440e8138105f4a12c86b')
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.CoinViews.CachedCoinView.SaveChangesAsync Outputs of transaction ID 'c3711c21d281d83e182b809d534245743768c6cd5f8d3a7c5acc26beb350db8b' are in cache already, updating them.
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.CoinViews.CachedCoinView.SaveChangesAsync Outputs of transaction ID '3a553072502bca9cc94ce76a75446e9429b88506708a3579ca99748c6c1154e2' are in cache already, updating them.
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.CoinViews.CachedCoinView.SaveChangesAsync Outputs of transaction ID '67a0a93c998e583c286353996a7a2ef3b4940c8227e9d51ce112e3aa4796e391' are in cache already, updating them.
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.Consensus.CoinViews.CachedCoinView.SaveChangesAsync (-)
[2017-09-03 15:34:08.1699 19] INFO: Stratis.Bitcoin.Features.Consensus.ConsensusFeature.RunLoop Reorg detected, rewinding from 97534 (62ff0bf4cb40b30ed69816a32cfeaa9b29dc482250a065a892fbca26e8529dce) to 97533 (283dc87de10ea19ffaf8fd2813581d3b43b7cff054bf440e8138105f4a12c86b)
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreSignaled.OnNextCore ()
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreLoop.AddToPending (block:'283dc87de10ea19ffaf8fd2813581d3b43b7cff054bf440e8138105f4a12c86b')
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreLoop.AddToPending (-)
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreSignaled.OnNextCore Block hash is '283dc87de10ea19ffaf8fd2813581d3b43b7cff054bf440e8138105f4a12c86b'.
[2017-09-03 15:34:08.1699 19] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreSignaled.OnNextCore (-)
[2017-09-03 15:34:08.1879 19] DEBUG: Stratis.Bitcoin.Features.Consensus.ConsensusFeature.RunLoop Exception occurred in consensus loop: System.Exception: Assertion failed
   at Stratis.Bitcoin.Utilities.Guard.Assert(Boolean condition) in X:\Dev\Stratis\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\Guard.cs:line 22
   at Stratis.Bitcoin.Features.Wallet.WalletSyncManager.ProcessBlock(Block block) in X:\Dev\Stratis\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\WalletSyncManager.cs:line 91
   at Stratis.Bitcoin.Features.Wallet.Notifications.BlockObserver.OnNextCore(Block block) in X:\Dev\Stratis\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\Notifications\BlockObserver.cs:line 24
   at System.Reactive.SafeObserver`1.OnNext(TSource value)
   at System.Reactive.Observer`1.OnNext(T value)
   at System.Reactive.SynchronizedObserver`1.OnNextCore(T value)
   at Stratis.Bitcoin.Signals.Signaler`1.Broadcast(T item) in X:\Dev\Stratis\StratisBitcoinFullNode\Stratis.Bitcoin\Signals\Signaler.cs:line 70
   at Stratis.Bitcoin.Signals.Signals.SignalBlock(Block block) in X:\Dev\Stratis\StratisBitcoinFullNode\Stratis.Bitcoin\Signals\Signals.cs:line 74
   at Stratis.Bitcoin.Features.Consensus.ConsensusFeature.RunLoop() in X:\Dev\Stratis\StratisBitcoinFullNode\Stratis.Bitcoin\Features\Consensus\ConsensusFeature.cs:line 165
[2017-09-03 15:34:08.1879 19] FATAL: Stratis.Bitcoin.Features.Consensus.ConsensusFeature.RunLoop Consensus loop unhandled exception (Tip:97533)
```

**Comment by dangershony** [comment]
I am aware of this bug, its the wallet that cant handle a specific case of a reorg, when i wrote this code i made the assumption the received block is the reorg block. This is not true.

**Comment by Aprogiena** [comment]
OK, I'll just add that this bug is the current source of node instability, i.e. quite a big issue.
