### ISSUE TITLE
[WalletManager] ProcessBlock assertion

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#432]
I had tons of `Wallet is behind the best chain and the next block is not found in store` on the console, so I ctrl+C and 
```
Application is shutting down...
info: Stratis.Bitcoin.Base.BaseFeature[0]
      FlushChain stopping
info: Stratis.Bitcoin.FullNode[0]
      MemoryPool.RelayWorker stopping
info: Stratis.Bitcoin.Base.BaseFeature[0]
      FlushAddressManager stopping
info: Stratis.Bitcoin.FullNode[0]
      wallet persist job stopping
info: Stratis.Bitcoin.FullNode[0]
      Closing node pending...
info: Stratis.Bitcoin.FullNode[0]
      BlockStore.DownloadAndStoreBlocks stopping
info: Stratis.Bitcoin.FullNode[0]
      PeriodicLog stopping
info: Stratis.Bitcoin.FullNode[0]
      BlockStore.RelayWorker stopping
crit: Stratis.Bitcoin.Features.Consensus.ConsensusFeature[0]
      Consensus loop unhandled exception (Tip:6135)
System.ArgumentNullException: Value cannot be null.
Parameter name: block
   at Stratis.Bitcoin.Utilities.Guard.NotNull[T](T value, String parameterName) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\Guard.cs:line 46
   at Stratis.Bitcoin.Features.Wallet.WalletManager.ProcessBlock(Block block, ChainedBlock chainedBlock) in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\WalletManager.cs:line 471
   at Stratis.Bitcoin.Features.Wallet.WalletSyncManager.ProcessBlock(Block block) in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\WalletSyncManager.cs:line 131
   at Stratis.Bitcoin.Features.Wallet.Notifications.BlockObserver.OnNextCore(Block block) in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\Notifications\BlockObserver.cs:line 24
   at System.Reactive.SafeObserver`1.OnNext(TSource value)
   at System.Reactive.Observer`1.OnNext(T value)
   at System.Reactive.SynchronizedObserver`1.OnNextCore(T value)
   at Stratis.Bitcoin.Signals.Signaler`1.Broadcast(T item) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Signals\Signaler.cs:line 70
   at Stratis.Bitcoin.Signals.Signals.SignalBlock(Block block) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Signals\Signals.cs:line 74
   at Stratis.Bitcoin.Features.Consensus.ConsensusFeature.RunLoop() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Features\Consensus\ConsensusFeature.cs:line 165

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: block
   at Stratis.Bitcoin.Utilities.Guard.NotNull[T](T value, String parameterName) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\Guard.cs:line 46
   at Stratis.Bitcoin.Features.Wallet.WalletManager.ProcessBlock(Block block, ChainedBlock chainedBlock) in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\WalletManager.cs:line 471
   at Stratis.Bitcoin.Features.Wallet.WalletSyncManager.ProcessBlock(Block block) in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\WalletSyncManager.cs:line 131
   at Stratis.Bitcoin.Features.Wallet.Notifications.BlockObserver.OnNextCore(Block block) in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\Notifications\BlockObserver.cs:line 24
   at System.Reactive.SafeObserver`1.OnNext(TSource value)
   at System.Reactive.Observer`1.OnNext(T value)
   at System.Reactive.SynchronizedObserver`1.OnNextCore(T value)
   at Stratis.Bitcoin.Signals.Signaler`1.Broadcast(T item) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Signals\Signaler.cs:line 70
   at Stratis.Bitcoin.Signals.Signals.SignalBlock(Block block) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Signals\Signals.cs:line 74
   at Stratis.Bitcoin.Features.Consensus.ConsensusFeature.RunLoop() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Features\Consensus\ConsensusFeature.cs:line 186
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by dangershony** [comment]
Ok yeah thanks, its currently an ugly hack.

When the wallet is behind consensus a loop tries to find the block in store (this will only work for not pruned nodes).

The problem is the loop is blocking consensus, and if the block is not in store (waiting for consensus to signal a block block to store) then the loop will never exit.

I have a hack on top of a hack.
Release the loop after x attempts, and don't push the block to the wallet assuming the next block will now release store to push the block and it will be available next round.

The proper fix:
Make wallet stand alone same as BlockStore.
If the wallet is behind and the block is not available in store (or if prune mode enabled) then wallet will download blocks (another puller is going to be introduced ;) )
