### ISSUE TITLE
[Wallet-Bug] When persisting wallet to disk.

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#446]
```
      ==================================================================
info: Stratis.Bitcoin.Features.Miner.PosMinting[0]
      Found new POS block hash '8ec0d92db70e951f31999a03cc236413324c7e978049c623b111e2d8aa9d3242' at height 107568.
info: Stratis.Bitcoin.Features.Miner.PosMinting[0]
      ==================================================================
crit: Stratis.Bitcoin.FullNode[0]
      wallet persist job threw an unhandled exception
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting)
   at Stratis.Bitcoin.Utilities.FileStorage.FileStorage`1.SaveToFile(T toSave, String fileName) in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\FileStorage.cs:line 42
   at Stratis.Bitcoin.Features.Wallet.WalletManager.SaveToFile(Wallet wallet) in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\WalletManager.cs:line 751
   at Stratis.Bitcoin.Features.Wallet.WalletManager.SaveToFile() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\WalletManager.cs:line 742
   at Stratis.Bitcoin.Features.Wallet.WalletManager.<Initialize>b__28_0(CancellationToken token) in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin.Features.Wallet\WalletManager.cs:line 115
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass12_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 129
info: Stratis.Bitcoin.Features.BlockStore.BlockStoreLoop[0]
```

**Comment by bokobza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-Bug] When persisting wallet to disk.](https://trello.com/c/hOPxM9LB/236-wallet-bug-when-persisting-wallet-to-disk)
