### ISSUE TITLE
[BlockStore] Loop terminated on exception in DownloadAndStoreBlocks 

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#489]
```

[2017-09-23 10:16:54.5912 39] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__70_0 ======Node stats====== 09/23/2017 10:16:54 agent StratisBitcoin:1.0.2
Headers.Height:        322000   Headers.Hash:         d5f1b36bb55e75a2becceebe6bbc859c40ef236dfa4f6587d77fa23a38973ed4
Consensus.Height:      6596     Consensus.Hash:       4b15e4a646a8477bcc19a4b99df57b9e7b8bc8490187a29d2792ebedaf3e029e
BlockStore.Height:     6593     BlockStore.Hash:      7f2b77aa00f2bdbc4af942998138aec0000629be4cdb62c932e005a1187e4139
Wallet.Height:         322000   Wallet.Hash:          d5f1b36bb55e75a2becceebe6bbc859c40ef236dfa4f6587d77fa23a38973ed4

======Mempool======
MempoolSize: 0    DynamicSize: 0 kb   OrphanSize: 0

======Connection======
Node:::ffff:139.162.250.199:16178,       connected (outbound),      agent /Stratis:2.0.0.2/,  height=322000


[2017-09-23 10:16:56.2936 3] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext BlockStore.DownloadAndStoreBlocks stopping
[2017-09-23 10:16:56.3237 3] FATAL: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext BlockStore.DownloadAndStoreBlocks threw an unhandled exception
[2017-09-23 10:16:59.6113 48] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__70_0 ======Node stats====== 09/23/2017 10:16:59 agent StratisBitcoin:1.0.2
Headers.Height:        322000   Headers.Hash:         d5f1b36bb55e75a2becceebe6bbc859c40ef236dfa4f6587d77fa23a38973ed4
Consensus.Height:      7000     Consensus.Hash:       563785e85f209da4c02cc494a07809ca1f98024bb14150bc4de355e75dccfd32
BlockStore.Height:     6603     BlockStore.Hash:      265b53359a0ed3dbb373a3d5b46057ad44113e962695555e590f573515a104e3
Wallet.Height:         322000   Wallet.Hash:          d5f1b36bb55e75a2becceebe6bbc859c40ef236dfa4f6587d77fa23a38973ed4
```

Node had to be restarted because BS did not advance anymore after its loop terminated on exception.
Sadly no further logs were collected at this run, so we don't know the exception.

**Comment by Aprogiena** [comment]
fortunately reproduced:

```
[2017-09-23 14:45:01.4333 7] DEBUG: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext BlockStore.DownloadAndStoreBlocks threw an unhandled exception: System.NullReferenceException: Object reference not s
et to an instance of an object.
   at Stratis.Bitcoin.Features.BlockStore.LoopSteps.ProcessPendingStorageStep.<PushBlocksToRepository>d__7.MoveNext() in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.BlockStore\LoopSteps\ProcessPendingStorageStep.cs:line 1
63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Stratis.Bitcoin.Features.BlockStore.LoopSteps.ProcessPendingStorageStep.<ProcessWhenInIBD>d__4.MoveNext() in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.BlockStore\LoopSteps\ProcessPendingStorageStep.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Stratis.Bitcoin.Features.BlockStore.LoopSteps.ProcessPendingStorageStep.<ExecuteAsync>d__2.MoveNext() in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.BlockStore\LoopSteps\ProcessPendingStorageStep.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Stratis.Bitcoin.Features.BlockStore.BlockStoreStepChain.<Execute>d__2.MoveNext() in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.BlockStore\BlockStoreLoopStep.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Stratis.Bitcoin.Features.BlockStore.BlockStoreLoop.<DownloadAndStoreBlocks>d__36.MoveNext() in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.BlockStore\BlockStoreLoop.cs:line 263
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Stratis.Bitcoin.Features.BlockStore.BlockStoreLoop.<<StartLoop>b__35_0>d.MoveNext() in C:\StratisBitcoinFullNode\Stratis.Bitcoin.Features.BlockStore\BlockStoreLoop.cs:line 215
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass12_0.<<StartAsync>b__0>d.MoveNext() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 129
```

**Comment by fassadlr** [comment]
The issue was caused by context.PendingBlockPairToStore being null when checking to see if the hashes matched before pushing to the repository. PendingBlockPairToStore can be null when the next chained block doesn't exist in pending storage.

We need to get the last block in the stack's hash and then use that when pushing to the repo, therefore that check wasn't really necessary.
