### ISSUE TITLE
Exception thrown on closing node

### ISSUE THREAD

**Issue by bokobza** [stratisproject/StratisBitcoinFullNode#635]
Pressing ctrl+C on a Stratis node running on testnet.
Received this:
```
Application is shutting down...
info: Stratis.Bitcoin.Base.BaseFeature[0]
      FlushAddressManager stopping
info: Stratis.Bitcoin.Base.BaseFeature[0]
      FlushChain stopping
info: Stratis.Bitcoin.FullNode[0]
      BlockStore.DownloadAndStoreBlocks stopping
info: Stratis.Bitcoin.FullNode[0]
      Closing node pending...
info: Stratis.Bitcoin.FullNode[0]
      wallet persist job stopping
info: Stratis.Bitcoin.FullNode[0]
      BlockStore.RelayWorker stopping
info: Stratis.Bitcoin.FullNode[0]
      PeriodicLog stopping
info: Stratis.Bitcoin.FullNode[0]
      MemoryPool.RelayWorker stopping
PS G:\GitHub\StratisBitcoinFullNode\Stratis.StratisD> info: Stratis.Bitcoin.Connection.ConnectionManager[0]
      Node [::ffff:84.192.155.226]:26178 offline
info: Stratis.Bitcoin.Connection.ConnectionManager[0]
      Node [::ffff:51.140.104.135]:26178 offline
info: Stratis.Bitcoin.Connection.ConnectionManager[0]
      Node [::ffff:13.64.76.48]:26178 offline
info: Stratis.Bitcoin.FullNode[0]
      Waiting for wallet persist job to finish.
fail: Stratis.Bitcoin.Features.MemoryPool.MempoolBehavior[0]
      Exception occurred: System.Exception: Assertion failed
         at Stratis.Bitcoin.Utilities.Guard.Assert(Boolean condition) in G:\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\Guard.cs:line 22
         at Stratis.Bitcoin.Features.MemoryPool.MempoolBehavior.<ProcessInvAsync>d__29.MoveNext() in G:\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin.Features.MemoryPool\MempoolBehavior.cs:line 324
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.MemoryPool.MempoolBehavior.<AttachedNode_MessageReceivedAsync>d__26.MoveNext() in G:\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin.Features.MemoryPool\MempoolBehavior.cs:line 193

Unhandled Exception: System.Exception: Assertion failed
   at Stratis.Bitcoin.Utilities.Guard.Assert(Boolean condition) in G:\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\Guard.cs:line 22
   at Stratis.Bitcoin.Features.MemoryPool.MempoolBehavior.<ProcessInvAsync>d__29.MoveNext() in G:\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin.Features.MemoryPool\MempoolBehavior.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.MemoryPool.MempoolBehavior.<AttachedNode_MessageReceivedAsync>d__26.MoveNext() in G:\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin.Features.MemoryPool\MempoolBehavior.cs:line 209
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by bokobza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Mempool] Exception thrown on closing node](https://trello.com/c/mYee0M8Y/301-mempool-exception-thrown-on-closing-node)

**Comment by bokobza** [comment]
additional tracing around the exception:
```

**Comment by mikedennis** [comment]
Looks like it's failing on this guard https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs#L324

**Comment by dangershony** [comment]
Ahh I added this guard long time ago its not needed actually.
I think the problem is that this.AttachedNode became null for the shutdown.

**Comment by mikedennis** [comment]
@dangershony That is my suspicion as well. I am unable to reproduce so I added some logging and hopefully Jeremy can reproduce with his wallets to confirm our suspicions.

@bokobza If you could try with the above logging and see what happens. If the attached node is null as suspected we can probably downgrade the log from Error to Trace. I just want to make sure it's not something else before we put this one to bed.
