### ISSUE TITLE
DBreeze not closing properly

### ISSUE THREAD

**Issue by bokobza** [stratisproject/StratisBitcoinFullNode#653]
Sometimes the node is not closed properly and and startup we get this:
 ```
Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred starting the application: DBreeze.Exceptions.DBreezeException: Creation of the databas                                                                                                                   e folder failed! ---> DBreeze.Exceptions.DBreezeException: Database is not operable, please find out the probl                                                                                                                   em and restart the engine! FSR INIT FAILED: /home/stratis/.stratisnode/stratis/StratisTest/chain/_DBreezeSchem                                                                                                                   a ---> System.IO.IOException: The process cannot access the file '/home/stratis/.stratisnode/stratis/StratisTe                                                                                                                   st/chain/_DBreezeSchema' because it is being used by another process.
         at System.IO.FileStream.Init(FileMode mode, FileShare share)
         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 b                                                                                                                   ufferSize, FileOptions options)
         at DBreeze.Storage.FSR.InitFiles()
         --- End of inner exception stack trace ---
         at DBreeze.Storage.FSR.InitFiles()
         at DBreeze.Storage.StorageLayer..ctor(String fileName, TrieSettings trieSettings, DBreezeConfiguratio                                                                                                                   n configuration)
         at DBreeze.Scheme.OpenSchema()
         at DBreeze.DBreezeEngine.InitDb()
         --- End of inner exception stack trace ---
         at DBreeze.DBreezeEngine.InitDb()
         at Stratis.Bitcoin.Utilities.DBreezeSingleThreadSession.<>c__DisplayClass5_0.<.ctor>b__0() in /home/s                                                                                                                   tratis/StratisBitcoinFullNode/Stratis.Bitcoin/Utilities/DBreezeSingleThreadSession.cs:line 78
         at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback,                                                                                                                    Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Utilities.DBreezeSingleThreadSession..ctor(String threadName, String folder) in /h                                                                                                                   ome/stratis/StratisBitcoinFullNode/Stratis.Bitcoin/Utilities/DBreezeSingleThreadSession.cs:line 88
         at Stratis.Bitcoin.Base.ChainRepository..ctor(String folder) in /home/stratis/StratisBitcoinFullNode/                                                                                                                   Stratis.Bitcoin/Base/ChainRepository.cs:line 25
         at Stratis.Bitcoin.Base.ChainRepository..ctor(DataFolder dataFolder) in /home/stratis/StratisBitcoinF                                                                                                                   ullNode/Stratis.Bitcoin/Base/ChainRepository.cs:line 29
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Co                                                                                                                   nstructorCallSite constructorCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCal                                                                                                                   lSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedC                                                                                                                   allSite scopedCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(Sing                                                                                                                   letonCallSite singletonCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCal                                                                                                                   lSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Co                                                                                                                   nstructorCallSite constructorCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCal                                                                                                                   lSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedC                                                                                                                   allSite scopedCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(Sing                                                                                                                   letonCallSite singletonCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCal                                                                                                                   lSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__                                                                                                                   0(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
         at Stratis.Bitcoin.Builder.FullNodeServiceProvider.<get_Features>d__2.MoveNext() in /home/stratis/Str                                                                                                                   atisBitcoinFullNode/Stratis.Bitcoin/Builder/FullNodeServiceProvider.cs:line 38
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) i                                                                                                                   n /home/stratis/StratisBitcoinFullNode/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 98
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Start() in /home/stratis/StratisBitcoinFullNode/St                                                                                                                   ratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 56

Unhandled Exception: DBreeze.Exceptions.DBreezeException: Creation of the database folder failed! ---> DBreeze                                                                                                                   .Exceptions.DBreezeException: Database is not operable, please find out the problem and restart the engine! FS                                                                                                                   R INIT FAILED: /home/stratis/.stratisnode/stratis/StratisTest/chain/_DBreezeSchema ---> System.IO.IOException:                                                                                                                    The process cannot access the file '/home/stratis/.stratisnode/stratis/StratisTest/chain/_DBreezeSchema' beca                                                                                                                   use it is being used by another process.
   at System.IO.FileStream.Init(FileMode mode, FileShare share)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferS                                                                                                                   ize, FileOptions options)
   at DBreeze.Storage.FSR.InitFiles()
   --- End of inner exception stack trace ---
   at DBreeze.Storage.FSR.InitFiles()
   at DBreeze.Storage.StorageLayer..ctor(String fileName, TrieSettings trieSettings, DBreezeConfiguration conf                                                                                                                   iguration)
   at DBreeze.Scheme.OpenSchema()
   at DBreeze.DBreezeEngine.InitDb()
   --- End of inner exception stack trace ---
   at DBreeze.DBreezeEngine.InitDb()
   at Stratis.Bitcoin.Utilities.DBreezeSingleThreadSession.<>c__DisplayClass5_0.<.ctor>b__0() in /home/stratis                                                                                                                   /StratisBitcoinFullNode/Stratis.Bitcoin/Utilities/DBreezeSingleThreadSession.cs:line 78
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Objec                                                                                                                   t state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Utilities.DBreezeSingleThreadSession..ctor(String threadName, String folder) in /home/st                                                                                                                   ratis/StratisBitcoinFullNode/Stratis.Bitcoin/Utilities/DBreezeSingleThreadSession.cs:line 88
   at Stratis.Bitcoin.Base.ChainRepository..ctor(String folder) in /home/stratis/StratisBitcoinFullNode/Strati                                                                                                                   s.Bitcoin/Base/ChainRepository.cs:line 25
   at Stratis.Bitcoin.Base.ChainRepository..ctor(DataFolder dataFolder) in /home/stratis/StratisBitcoinFullNod                                                                                                                   e/Stratis.Bitcoin/Base/ChainRepository.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Construc                                                                                                                   torCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite                                                                                                                    callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSit                                                                                                                   e scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonC                                                                                                                   allSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite                                                                                                                    callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Construc                                                                                                                   torCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite                                                                                                                    callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSit                                                                                                                   e scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonC                                                                                                                   allSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite                                                                                                                    callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(Serv                                                                                                                   iceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Stratis.Bitcoin.Builder.FullNodeServiceProvider.<get_Features>d__2.MoveNext() in /home/stratis/StratisBi                                                                                                                   tcoinFullNode/Stratis.Bitcoin/Builder/FullNodeServiceProvider.cs:line 38
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in /hom                                                                                                                   e/stratis/StratisBitcoinFullNode/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 98
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Start() in /home/stratis/StratisBitcoinFullNode/Stratis.                                                                                                                   Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 62
   at Stratis.Bitcoin.FullNode.Start() in /home/stratis/StratisBitcoinFullNode/Stratis.Bitcoin/FullNode.cs:lin                                                                                                                   e 194
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.Run(IFullNode node, CancellationToken cancellationToken, St                                                                                                                   ring shutdownMessage, String shutdownCompleteMessage) in /home/stratis/StratisBitcoinFullNode/Stratis.Bitcoin/                                                                                                                   Utilities/FullNodeExtensions.cs:line 69
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.Run(IFullNode node) in /home/stratis/StratisBitcoinFullNode                                                                                                                   /Stratis.Bitcoin/Utilities/FullNodeExtensions.cs:line 53
   at Stratis.StratisD.Program.Main(String[] args) in /home/stratis/StratisBitcoinFullNode/Stratis.StratisD/Pr                                                                                                                   ogram.cs:line 35

```

It needs investigating asap as maybe this is something blocking the processes to be closed by the Breeze Wallet.

**Comment by Aprogiena** [comment]
i don't think this is an issue with DBreeze, it looks to me more like a node process being not correctly shutdown and hence if a new instance is launched, it can't get exclusive access to the database, which is expected

**Comment by bokobza** [comment]
This seems to be ok now.
