### ISSUE TITLE
Fullnode crashes

### ISSUE THREAD

**Issue by mtaipe** [stratisproject/StratisBitcoinFullNode#728]
The Fullnode on stacking mode randomly crashes. It also did the same on previous versions, same mode.

FN version used is StratisBitcoin:1.0.5
Environment: Ubuntu 16.04
```
info: Stratis.Bitcoin.Connection.ConnectionManagerBehavior[0]
      Node [::ffff:82.12.182.131]:62200 offline.
info: Stratis.Bitcoin.Connection.ConnectionManagerBehavior[0]
      Reason: Unexpected exception while connecting to socket
info: Stratis.Bitcoin.Features.Miner.PosMinting[0]
      Node staking with 937751.05170040 (44.82 % of the network weight 2092084.87058546), est. time to find new block is 00:02:22.
info: Stratis.Bitcoin.Connection.ConnectionManagerBehavior[0]
      Node [::ffff:169.1.126.177]:29906 offline.
info: Stratis.Bitcoin.Connection.ConnectionManagerBehavior[0]
      Reason: Unexpected exception while connecting to socket

Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Set()
   at NBitcoin.Protocol.Node.NodeConnection.EndListen(Exception unhandledException) in /home/mtaipe/src/StratisBitcoinFullNode/src/NBitcoin/Protocol/Node.cs:line 304
   at NBitcoin.Protocol.Node.NodeConnection.<BeginListen>b__16_1() in /home/mtaipe/src/StratisBitcoinFullNode/src/NBitcoin/Protocol/Node.cs:line 274
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted (core dumped)
```

**Comment by Aprogiena** [comment]
This does not sound related to staking.

**Comment by mtaipe** [comment]
Fetching new changes from the repo and running without the stacking option. I will report if the same problem arises.

**Comment by fassadlr** [comment]
Hi @mtaipe, can you confirm that this issue is still happening? 

Please ensure that you have the latest version of the code base 👍

**Comment by mtaipe** [comment]
It crashed again, but I was using code of 2 days ago, when I last reported. I will build again a try.

**Comment by mtaipe** [comment]
Hello @fassadlr, 

The FullNode crashed again. I will try to provide more debug information by running the FN with the parameter: -debug=NBitcoin.Protocol.

`Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Set()
   at NBitcoin.Protocol.Node.NodeConnection.EndListen(Exception unhandledException) in /home/mtaipe/src/StratisBitcoinFullNode/src/NBitcoin/Protocol/Node.cs:line 272
   at NBitcoin.Protocol.Node.NodeConnection.<BeginListen>b__22_1() in /home/mtaipe/src/StratisBitcoinFullNode/src/NBitcoin/Protocol/Node.cs:line 244
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted (core dumped)`

**Comment by fassadlr** [comment]
@mtaipe I believe one of our devs has also now experienced this issue. We'll look into this.

Thanks!

**Comment by fassadlr** [comment]
@mtaipe PS can you please provide us with the settings you run the node in?

**Comment by mtaipe** [comment]
@fassadlr Settings are, -testnet and -debug=NBitcoin.Protocol, however the last didn't provide any logs.

Also tried   adding this line in the NLog.config in their proper section without success:
`
    <target name=""debugNBitcoinProtocolFile"" xsi:type="AsyncWrapper" queueLimit="10000" overflowAction="Block" batchSize="1000">
      <target xsi:type="File" fileName="protocol.txt" layout="[${longdate:universalTime=true} ${threadid}${mdlc:item=id}] ${level:uppercase=true}: ${callsite} ${message}" encoding="utf-8" />
    </target>`

`<logger name="NBitcoin.Protocol.*" minlevel="Debug" writeTo="debugNBitcoinProtocolFile" />`

The FN crashed again after two days of running ,  and found this kernel messages:
`[897906.312054] TCP: too many orphaned sockets`

Let me know if there are some configurations for the NLog.config that could help get more info about this crash.

`Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Set()
   at NBitcoin.Protocol.Node.NodeConnection.EndListen(Exception unhandledException) in /home/mtaipe/src/StratisBitcoinFullNode/src/NBitcoin/Protocol/Node.cs:line 272
   at NBitcoin.Protocol.Node.NodeConnection.<BeginListen>b__22_1() in /home/mtaipe/src/StratisBitcoinFullNode/src/NBitcoin/Protocol/Node.cs:line 244
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted (core dumped)`

**Comment by Aprogiena** [comment]
Thanks @mtaipe. I don't think at this point we need more information. The Node class is subject to refactoring, which will change everything.

**Comment by fassadlr** [comment]
Hi @mtaipe there has been various improvements surrounding the disposing of node features, that might have fixed this issue. Can you maybe get the latest code and re-run for us? Thank you!

**Comment by fassadlr** [comment]
Closing this issue as @mtaipe has not gotten back to us with any new issues. Plus, a massive amount of refactoring has been done around NetworkPeer. If his issue happens again we can re-raise.

**Comment by Aprogiena** [comment]
Yes it is likely that the code causing this was removed.

**Comment by mtaipe** [comment]
Confirmed, no more crashes. A node with version StratisBitcoin:1.0.7 was running for more than a week without problems.
