### ISSUE TITLE
Daemon crashes if first ran as root, then as regular user on Linux

### ISSUE THREAD

**Issue by Auxon** [stratisproject/StratisBitcoinFullNode#76]
You may get the following exception if you first dotnet run the daemon as root, but then later run it as a regular user:
**Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Consensus.DBreezeCoinView.<Initialize>**b__3_0() in /home/auxon0/sources/StratisBitcoinFullNode/Stratis.Bitcoin/Consensus/CoinViews/DBreezeCoinView.cs:line 32
   at Stratis.Bitcoin.DBreezeSingleThreadSession.<>c__DisplayClass10_0.<Do>b__0() in /home/auxon0/sources/StratisBitcoinFullNode/Stratis.Bitcoin/DBreezeSingleThreadSession.cs:line 127
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Stratis.Bitcoin.Consensus.DBreezeCoinView..ctor(Network network, String folder) in /home/auxon0/sources/StratisBitcoinFullNode/Stratis.Bitcoin/Consensus/CoinViews/DBreezeCoinView.cs:line 25
   at Stratis.Bitcoin.Builder.FullNodeBuilderExtensions.<>c__DisplayClass2_0.<AddRequired>b__0(IServiceCollection service) in /home/auxon0/sources/StratisBitcoinFullNode/Stratis.Bitcoin/Builder/FullNodeBuilderExtensions.cs:line 48
   at Stratis.Bitcoin.Builder.FullNodeBuilder.BuildServices() in /home/auxon0/sources/StratisBitcoinFullNode/Stratis.Bitcoin/Builder/FullNodeBuilder.cs:line 153
   at Stratis.Bitcoin.Builder.FullNodeBuilder.Build() in /home/auxon0/sources/StratisBitcoinFullNode/Stratis.Bitcoin/Builder/FullNodeBuilder.cs:line 126
   at Stratis.BitcoinD.Program.Main(String[] args) in /home/auxon0/sources/StratisBitcoinFullNode/Stratis.BitcoinD/Program.cs:line 24

To workaround this issue, a user may simply use "sudo dotnet run" to launch the daemon.

A better error message explaining that access denied is recommended for a fix, and a documentation update explaining the issue and workaround.

**Comment by Auxon** [comment]
I have made a fix for this ... submitting a PR.

**Comment by Auxon** [comment]
Due to changes in the upstream master branch, I'll be re-jigging the patch before submitting a PR.

**Comment by Auxon** [comment]
Added a check on the data folders to Program.cs.  If access is denied, the following is logged:

crit: Configuration[0]
      Access to the path '/home/auxon0/.stratisbitcoin/Main/blocks' was denied.

**Comment by Auxon** [comment]
Fixed.
