### ISSUE TITLE
Mempool bug: 

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#87]
This bug found a few times (after running for about 24 hours or if mempool is really full)

```
fail: Mempool[0]
      System.ArgumentException: An item with the same key has already been added. Key: e492cffb55da94e2e4f5ecb29cb47a47365a1572867f8db523e7e323c315d52f
         at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
         at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
         at Stratis.Bitcoin.Consensus.UnspentOutputSet.SetCoins(FetchCoinsResponse coins) in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\UnspentOutputSet.cs:line 52
         at Stratis.Bitcoin.MemoryPool.MempoolCoinView.<LoadView>d__10.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MemPoolCoinView.cs:line 41
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.MemoryPool.MempoolValidator.<AcceptToMemoryPoolWorker>d__27.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolValidator.cs:line 107
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.MemoryPool.MempoolValidator.<AcceptToMemoryPoolWithTime>d__25.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolValidator.cs:line 71
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.MemoryPool.MempoolBehavior.<ProcessTxPayloadAsync>d__24.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolBehavior.cs:line 184
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.MemoryPool.MempoolBehavior.<AttachedNode_MessageReceived>d__20.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolBehavior.cs:line 70

Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: e492cffb55da94e2e4f5ecb29cb47a47365a1572867f8db523e7e323c315d52f
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Stratis.Bitcoin.Consensus.UnspentOutputSet.SetCoins(FetchCoinsResponse coins) in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\UnspentOutputSet.cs:line 52
   at Stratis.Bitcoin.MemoryPool.MempoolCoinView.<LoadView>d__10.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MemPoolCoinView.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.MemoryPool.MempoolValidator.<AcceptToMemoryPoolWorker>d__27.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolValidator.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.MemoryPool.MempoolValidator.<AcceptToMemoryPoolWithTime>d__25.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolValidator.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.MemoryPool.MempoolBehavior.<ProcessTxPayloadAsync>d__24.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolBehavior.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.MemoryPool.MempoolBehavior.<AttachedNode_MessageReceived>d__20.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolBehavior.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by Derrick-** [comment]
I bet this is similar to https://github.com/stratisproject/StratisBitcoinFullNode/issues/102

Also rooted in the MessageReceived event.

The NodeConnections are running on other threads, and occasionally there's going to be the same message coming in at the same time. I'm looking at adding semaphores around the collections, but in case of TxMempool, the inner dictionary isn't concurrent as it is with the BlockPuller problem.

**Comment by dangershony** [comment]
yeha with the mempool I took a different approach of a lock free implementation, all the thread synchronization happens at the scheduler pair level (i.e asyncLock.Read and asynclock.Write)

**Comment by Derrick-** [comment]
Happend to me. this probably doesn't add any additional useful info, but here it is:

```
info: Stratis.Bitcoin.MemoryPool[0]
      accepted orphan tx b2bd50f96457c25e62a8f13e66bc1122d384ff9430c0f86c8c42960bcda14224
info: Stratis.Bitcoin.MemoryPool[0]
      accepted orphan tx 8dcdbb062488a8e3d0bc775dd8b6b947205cee14b57a07c26509cc27c375b7ba
fail: Stratis.Bitcoin.MemoryPool[0]
      System.ArgumentException: An item with the same key has already been added. Key: 412f49eb4f70d08af9adb1cacf2454aec7499b83eb9740d71f5f16dc64476dfc
         at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
         at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
         at Stratis.Bitcoin.Consensus.UnspentOutputSet.SetCoins(FetchCoinsResponse coins) in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\UnspentOutputSet.cs:line 52
         at Stratis.Bitcoin.MemoryPool.MempoolCoinView.<LoadView>d__10.MoveNext() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MemPoolCoinView.cs:line 41
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
         at Stratis.Bitcoin.MemoryPool.MempoolValidator.<AcceptToMemoryPoolWorker>d__27.MoveNext() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolValidator.cs:line 107
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
         at Stratis.Bitcoin.MemoryPool.MempoolValidator.<AcceptToMemoryPoolWithTime>d__25.MoveNext() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolValidator.cs:line 71
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at Stratis.Bitcoin.MemoryPool.MempoolBehavior.<ProcessTxPayloadAsync>d__24.MoveNext() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolBehavior.cs:line 184
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
         at Stratis.Bitcoin.MemoryPool.MempoolBehavior.<AttachedNode_MessageReceived>d__20.MoveNext() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolBehavior.cs:line 70

Unhandled Exception: info: Stratis.Bitcoin.MemoryPool[0]
      accepted orphan tx fb1644ca0174367fb58707af1856bfc4671b485b351fcc8498740350724604e4
System.ArgumentException: An item with the same key has already been added. Key: 412f49eb4f70d08af9adb1cacf2454aec7499b83eb9740d71f5f16dc64476dfc
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Stratis.Bitcoin.Consensus.UnspentOutputSet.SetCoins(FetchCoinsResponse coins) in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\UnspentOutputSet.cs:line 52
   at Stratis.Bitcoin.MemoryPool.MempoolCoinView.<LoadView>d__10.MoveNext() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MemPoolCoinView.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Stratis.Bitcoin.MemoryPool.MempoolValidator.<AcceptToMemoryPoolWorker>d__27.MoveNext() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolValidator.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Stratis.Bitcoin.MemoryPool.MempoolValidator.<AcceptToMemoryPoolWithTime>d__25.MoveNext() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolValidator.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Stratis.Bitcoin.MemoryPool.MempoolBehavior.<ProcessTxPayloadAsync>d__24.MoveNext() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolBehavior.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Stratis.Bitcoin.MemoryPool.MempoolBehavior.<AttachedNode_MessageReceived>d__20.MoveNext() in D:\Dev\StratisBitcoinFullNode\Stratis.Bitcoin\MemoryPool\MempoolBehavior.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by dangershony** [comment]
The fix is probably easy, when we come from the mempool we can check if a trx is already in the utxo set.
But I want to be sure this is the case.
