### ISSUE TITLE
Race condition on peer discovery

### ISSUE THREAD

**Issue by NicolasDorier** [stratisproject/StratisBitcoinFullNode#949]
Copying a potential bug someone reported me

```
On another note, I switched to Stratis yesterday and was able to build it and run it under the debugger. I read a lot of the P2P networking code and managed to disable Peer Server and "Advertise" so the node functions as a passive node. I also suppressed the Mining and RPC features to minimize background noise so I can focus on the peer discovery portion of the node for now. The code is rather well structured and much easier to follow so kudos there.

 

I don't know if you've seen this, but one thing I noticed is that it seems like the Async Loops are somewhat instable, especially when you jack up the Parallelism in the Peer Discovery code. It looks like the loops will stop after a while and both the node and VS debugger will freeze and I am forced to kill the dotnet process. This can be reproduced quite regularly under the debugger. After a few minutes, both the Peer Discovery Loop and the periodic Stat updates on the console stop, and it never recovers.

 

I think I might have found a potential memory corruption issue in the Peer Discovery Loop (PeerDiscoveryLoop.cs). As I increase the Parallelism in the discovery loop, I noticed I start seeing some thread-safe insert issues in line 148 at this line:

 

clonedParameters.TemplateBehaviors.Add(addressManagerBehaviour);

 

Specifically, a null pointer exception. Digging deeper, I noticed that clonedParameters was instantiated in line 127 (outside of the lambda function that references it):

 

var clonedParameters = this.currentParameters.Clone();

 

I think all the parallel discovery threads are referencing the same instance of clonedParameters and causing corruption. I moved that line inside the lambda function (e.g. line 141) and the null pointer exceptions went away.

 

However, once I got past the null pointer exceptions, I started seeing a lot of OperationCanceledException's being thrown after the call to this.networkPeerFactory.CreateConnectedNetworkPeerAsync succeeds in line 150. This tells me that the cancelation is happening in either line 151, 152 or 154:

 

await networkPeer.VersionHandshakeAsync(connectTokenSource.Token).ConfigureAwait(false);

await networkPeer.SendMessageAsync(new GetAddrPayload(), connectTokenSource.Token).ConfigureAwait(false);

connectTokenSource.Token.WaitHandle.WaitOne(TimeSpan.FromSeconds(5));

 

I'm still investigating but the code there looks pretty fragile and does not handle error cases well. I've also seen unhandled exceptions being thrown in the FullNode.PeriodicLog Async Loop, causing the stats display to stop. Looking into that one too.

 

In any case, I think Stratis is an excellent codebase to help a newbie like me explore the underlying infrastructure Bitcoin and the BlockChain, and I want to thank you and the others for making this Open Source for others to follow and learn. So far it's pretty fascinating!

 
```

**Comment by fassadlr** [comment]
Thanks for logging this issue @NicolasDorier. It isn't really an issue that each discovery thread is using the same parameters but I can see how it can potentially cause issues with threading. We'll move the cloning into the thread. Also, I highly doubt that we'll ever start up more than 5 threads for peer discovery as its just not a scenario which will be of benefit to us.

The OperationCanceledException's are to be expected and is valid as we want the connection/handshake timeouts to happen so that we can move onto trying the next peer.

**Comment by NicolasDorier** [comment]
@fassadlr the problem is not about being able to have more threads. Adding more thread is just a way to better discover race conditions. (and it did)

For the `OperationCanceledException` the problem is that it is something expected, but still logging in the show without having debug logs turned on?

**Comment by fassadlr** [comment]
@NicolasDorier I don't understand what the "race" condition is here? Can you please explain to me?

Also, what do you mean, still logging to the "show"?

Sorry dude, just trying to get the root of the problem  👍

**Comment by NicolasDorier** [comment]
When `a null pointer exception` happen when you only increase the number of thread, it proves the code has a race condition.

The guy explained where it comes from:
```
I think all the parallel discovery threads are referencing the same instance of clonedParameters and causing corruption. I moved that line inside the lambda function (e.g. line 141) and the null pointer exceptions went away.
```

**Comment by fassadlr** [comment]
Ah OK wait I see now where the issue is @NicolasDorier !

Here we clone the parameters (**outside**) thread startup: 

```
var clonedParameters = this.currentParameters.Clone();

Parallel.ForEach(peersToDiscover, new ParallelOptions()
{
````

Then within each thread we add to the behaviour collection here:

```
var addressManagerBehaviour = clonedParameters.TemplateBehaviors.Find<PeerAddressManagerBehaviour>();
clonedParameters.TemplateBehaviors.Clear();
clonedParameters.TemplateBehaviors.Add(addressManagerBehaviour);
```

I have checked and we don't modify parameters anywhere further down the execution path but in this instance, you are right, its a classic race condition as we modify shared data within each thread, which is not good. I'll fix this.

Thanks!

**Comment by fassadlr** [comment]
PS Please let me know regarding:

> Also, what do you mean, still logging to the "show"?

**Comment by Aprogiena** [comment]
I've seen this one:
```
crit: Stratis.Bitcoin.FullNode[0]
      PeriodicLog threw an unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Connection.ConnectionManager.GetNodeStats() in C:\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin\Connection\ConnectionManager.cs:line 292
   at Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__69_0(CancellationToken cancellation) in C:\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin\FullNode.cs:line 232
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass12_0.<<StartAsync>b__0>d.MoveNext() in C:\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 129
```

it is probably one of those the OP reported

**Comment by fassadlr** [comment]
@NicolasDorier we have identified the issue with logging as well. A fix has been submitted. 👍

**Comment by NicolasDorier** [comment]
@fassadlr  He said

```
I started seeing a lot of OperationCanceledException'
```

You replied that it was expected. So my question was: if it is expected, why was he able to see it at all?
