### ISSUE TITLE
Btc testnet IBD stuck. Throws after node's restart

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#999]
Node's log at the moment it stuck at height 1012555.

```
======Mempool======
MempoolSize: 0    DynamicSize: 0 kb   OrphanSize: 0   
======Connection======
Peer:::ffff:103.233.2.108:18333,         connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:38.27.100.44:18333,          connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:198.251.83.19:18333,         connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:104.130.141.235:18333,       connected (outbound),      agent /Satoshi:0.12.1/,  height=1256485
Peer:::ffff:159.203.183.25:18333,        connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:144.76.136.19:18333,         connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:76.85.20.142:18333,          connected (outbound),      agent /Satoshi:0.15.0/,  height=1256485
Peer:::ffff:34.242.92.67:18333,          connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
[2017-12-28 16:23:51.8488 31] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__73_0 ======Node stats====== 12/28/2017 16:23:51 agent StratisBitcoin:1.0.7
Headers.Height:      1256485  Headers.Hash:     0000000000000656f2fba348adf99772754a7b2a4888eafe1d41746bde3603d2
Consensus.Height:    1012555  Consensus.Hash:   000000000000039a2d017d8c35a4044f641c54775d43657cc7622f8bfba84653
BlockStore.Height:   1012555  BlockStore.Hash:  000000000000039a2d017d8c35a4044f641c54775d43657cc7622f8bfba84653
Wallet.Height:       No Wallet
======Mempool======
MempoolSize: 0    DynamicSize: 0 kb   OrphanSize: 0   
======Connection======
Peer:::ffff:103.233.2.108:18333,         connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:38.27.100.44:18333,          connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:198.251.83.19:18333,         connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:104.130.141.235:18333,       connected (outbound),      agent /Satoshi:0.12.1/,  height=1256485
Peer:::ffff:159.203.183.25:18333,        connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:144.76.136.19:18333,         connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:76.85.20.142:18333,          connected (outbound),      agent /Satoshi:0.15.0/,  height=1256485
Peer:::ffff:34.242.92.67:18333,          connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
[2017-12-28 16:23:56.8638 12] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__73_0 ======Node stats====== 12/28/2017 16:23:56 agent StratisBitcoin:1.0.7
Headers.Height:      1256485  Headers.Hash:     0000000000000656f2fba348adf99772754a7b2a4888eafe1d41746bde3603d2
Consensus.Height:    1012555  Consensus.Hash:   000000000000039a2d017d8c35a4044f641c54775d43657cc7622f8bfba84653
BlockStore.Height:   1012555  BlockStore.Hash:  000000000000039a2d017d8c35a4044f641c54775d43657cc7622f8bfba84653
Wallet.Height:       No Wallet
======Mempool======
MempoolSize: 0    DynamicSize: 0 kb   OrphanSize: 0   
======Connection======
Peer:::ffff:103.233.2.108:18333,         connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:38.27.100.44:18333,          connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:198.251.83.19:18333,         connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:104.130.141.235:18333,       connected (outbound),      agent /Satoshi:0.12.1/,  height=1256485
Peer:::ffff:159.203.183.25:18333,        connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:144.76.136.19:18333,         connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
Peer:::ffff:76.85.20.142:18333,          connected (outbound),      agent /Satoshi:0.15.0/,  height=1256485
Peer:::ffff:34.242.92.67:18333,          connected (outbound),      agent /Satoshi:0.15.1/,  height=1256485
[2017-12-28 16:24:00.1281 23] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext PeerConnectorAddNode.ConnectAsync stopping
[2017-12-28 16:24:00.1281 29] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext Consensus Loop stopping
[2017-12-28 16:24:00.1281 22] INFO: Stratis.Bitcoin.FullNode.Dispose Closing node pending...
[2017-12-28 16:24:00.1281 10] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext MemoryPool.RelayWorker stopping
[2017-12-28 16:24:00.1281 23] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext wallet persist job stopping
[2017-12-28 16:24:00.1281 23] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext BlockStore.RelayWorker stopping
[2017-12-28 16:24:00.1281 23] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext PeriodicLog stopping
[2017-12-28 16:24:00.1281 23] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext PeerConnectorDiscovery.ConnectAsync stopping
[2017-12-28 16:24:00.1281 23] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext FlushChain stopping
[2017-12-28 16:24:00.1281 23] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext Periodic peer flush... stopping
[2017-12-28 16:24:00.1281 23] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext BlockStore.DownloadAndStoreBlocks stopping
[2017-12-28 16:24:00.1433 23] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0+<<StartAsync>b__0>d.MoveNext DiscoverPeersAsync stopping
[2017-12-28 16:24:00.1433 22] INFO: Stratis.Bitcoin.Connection.ConnectionManager.Dispose Stopping peer discovery...
[2017-12-28 16:24:00.1583 22] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.Dispose Waiting for DiscoverPeersAsync to finish.
[2017-12-28 16:24:00.1583 22] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.Dispose Waiting for PeerConnectorAddNode.ConnectAsync to finish.
[2017-12-28 16:24:00.1754 22] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.Dispose Waiting for PeerConnectorDiscovery.ConnectAsync to finish.
[2017-12-28 16:24:00.1754 22] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Peer '[::ffff:103.233.2.108]:18333' offline, reason: 'unknown'.
[2017-12-28 16:24:00.1754 22] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Peer '[::ffff:38.27.100.44]:18333' offline, reason: 'unknown'.
[2017-12-28 16:24:00.1754 22] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Peer '[::ffff:198.251.83.19]:18333' offline, reason: 'unknown'.
[2017-12-28 16:24:00.1754 22] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Peer '[::ffff:104.130.141.235]:18333' offline, reason: 'unknown'.
[2017-12-28 16:24:00.1900 22] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Peer '[::ffff:159.203.183.25]:18333' offline, reason: 'unknown'.
[2017-12-28 16:24:00.1900 22] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Peer '[::ffff:144.76.136.19]:18333' offline, reason: 'unknown'.
[2017-12-28 16:24:00.1900 22] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Peer '[::ffff:76.85.20.142]:18333' offline, reason: 'unknown'.
[2017-12-28 16:24:00.1900 22] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Peer '[::ffff:34.242.92.67]:18333' offline, reason: 'unknown'.
[2017-12-28 16:24:00.2175 22] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.Dispose Waiting for PeriodicLog to finish.
[2017-12-28 16:24:00.2214 22] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.Dispose Waiting for wallet persist job to finish.
[2017-12-28 16:24:00.2214 22] INFO: Stratis.Bitcoin.Features.MemoryPool.MempoolFeature.Dispose Saving Memory Pool...
[2017-12-28 16:24:00.2214 22] INFO: Stratis.Bitcoin.Features.MemoryPool.MempoolFeature.Dispose ...Memory Pool Saved 0 transactions
[2017-12-28 16:24:00.2214 22] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.Dispose Waiting for MemoryPool.RelayWorker to finish.
[2017-12-28 16:24:00.2214 22] INFO: Stratis.Bitcoin.Features.BlockStore.BlockStoreFeature.Dispose Stopping BlockStore...
[2017-12-28 16:24:00.2214 22] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.Dispose Waiting for BlockStore.RelayWorker to finish.
[2017-12-28 16:24:00.2214 22] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.Dispose Waiting for BlockStore.DownloadAndStoreBlocks to finish.
[2017-12-28 16:24:00.2214 22] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.Dispose Waiting for Consensus Loop to finish.
[2017-12-28 16:24:00.2214 22] INFO: Stratis.Bitcoin.Features.Consensus.ConsensusFeature.Dispose Flushing Cache CoinView...
[2017-12-28 16:24:01.8502 22] INFO: Stratis.Bitcoin.Base.BaseFeature.Dispose Flushing peers...
[2017-12-28 16:24:01.8502 22] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.Dispose Waiting for Periodic peer flush... to finish.
[2017-12-28 16:24:01.8651 22] INFO: Stratis.Bitcoin.Base.BaseFeature.Dispose Flushing headers chain...
[2017-12-28 16:24:01.8651 22] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.Dispose Waiting for FlushChain to finish.
```

After restarting node throws: 
```
[2017-12-28 16:24:10.3801 1] INFO: Stratis.Bitcoin.FullNode.Initialize Full node initialized on TestNet
[2017-12-28 16:24:10.4116 1] INFO: Stratis.Bitcoin.FullNode.Start Starting node...
[2017-12-28 16:24:10.5016 1] INFO: Stratis.Bitcoin.Base.BaseFeature.StartChainAsync Loading chain
[2017-12-28 16:24:23.5532 7] INFO: Stratis.Bitcoin.Base.BaseFeature+<StartChainAsync>d__22.MoveNext Chain loaded at height 1256485
[2017-12-28 16:24:23.5532 5] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0.<StartAsync>b__0 FlushChain starting
[2017-12-28 16:24:23.5532 1] INFO: Stratis.Bitcoin.Base.BaseFeature.StartAddressManager Loading peers from : C:\Users\user\AppData\Roaming\StratisNode\bitcoin\TestNet...
[2017-12-28 16:24:23.6989 4] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0.<StartAsync>b__0 Periodic peer flush... starting
[2017-12-28 16:24:23.7143 6] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0.<StartAsync>b__0 Consensus Loop starting
[2017-12-28 16:24:23.7476 5] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0.<StartAsync>b__0 BlockStore.RelayWorker starting
[2017-12-28 16:24:23.7476 7] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0.<StartAsync>b__0 BlockStore.DownloadAndStoreBlocks starting
[2017-12-28 16:24:23.7476 1] INFO: Stratis.Bitcoin.Features.MemoryPool.MempoolManager.LoadPoolAsync Loading Memory Pool...
[2017-12-28 16:24:23.7540 4] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0.<StartAsync>b__0 MemoryPool.RelayWorker starting
[2017-12-28 16:24:23.8283 1] INFO: Stratis.Bitcoin.Features.RPC.RPCFeature.Initialize RPC Server listening on: 
http://[::1]:18332/
http://127.0.0.1:18332/
[2017-12-28 16:24:23.8325 5] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass12_0.<StartAsync>b__0 wallet persist job starting
[2017-12-28 16:24:23.8325 1] INFO: Stratis.Bitcoin.Features.Wallet.WalletSyncManager.Start WalletSyncManager initialized. Wallet at block 1256485.
[2017-12-28 16:24:23.8519 1] ERROR: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Initialize An error occurred starting the application: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Connection.ConnectionManager.AddDiscoveredNodesRequirement(NetworkPeerServices services) in C:\Users\user\Desktop\TEST\src\Stratis.Bitcoin\Connection\ConnectionManager.cs:line 224
   at Stratis.Bitcoin.Features.Consensus.ConsensusFeature.Initialize() in C:\Users\user\Desktop\TEST\src\Stratis.Bitcoin.Features.Consensus\ConsensusFeature.cs:line 120
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in C:\Users\user\Desktop\TEST\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 57
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in C:\Users\user\Desktop\TEST\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 102
   --- End of inner exception stack trace ---
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in C:\Users\user\Desktop\TEST\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 120
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Initialize() in C:\Users\user\Desktop\TEST\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 57
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Connection.ConnectionManager.AddDiscoveredNodesRequirement(NetworkPeerServices services) in C:\Users\user\Desktop\TEST\src\Stratis.Bitcoin\Connection\ConnectionManager.cs:line 224
   at Stratis.Bitcoin.Features.Consensus.ConsensusFeature.Initialize() in C:\Users\user\Desktop\TEST\src\Stratis.Bitcoin.Features.Consensus\ConsensusFeature.cs:line 120
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in C:\Users\user\Desktop\TEST\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 57
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in C:\Users\user\Desktop\TEST\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 102<---
```

Cleaning cache and syncing from scratch fixes it.

**Comment by noescape00** [comment]
Update: 
Most likely this bug is introduced by https://github.com/stratisproject/StratisBitcoinFullNode/pull/998 so it's not on master yet. 
It is confirmed that not only I got this bug.

**Comment by fassadlr** [comment]
Ah it seems that peerConnector.Requirement was null after startup?

This can't be right, I'll investigate.

**Comment by fassadlr** [comment]
I have a fix for this, just waiting for my bitcoin chain to sync to that block...

**Comment by noescape00** [comment]
>Ah it seems that peerConnector.Requirement was null after startup?

Correct. 

>I have a fix for this, just waiting for my bitcoin chain to sync to that block...

Awesome, thx!
